kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sysbench-sc
provisioner: pxd.portworx.com
parameters:
  # Tests:
  # * FlashArray Direct Access w/ filesystem
  # * Specifying filesystem type, creation options, and mount options
  # * Specifying QoS
  backend: "pure_block"
  max_iops: "1000"
  max_bandwidth: "1G"
  csi.storage.k8s.io/fstype: ext4
  createoptions: -b 4096
mountOptions:
  - nosuid
  - discard
allowVolumeExpansion: true