---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: vdbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vdbench
  template:
    metadata:
      labels:
        app: vdbench
    spec:
      containers:
        - name: vdbench
          image: openebs/tests-vdbench
          command: ["./bench_runner.sh"]
          args: ["Basic", "5400"]
          volumeMounts:
            - name: vdbench-persistent-storage
              mountPath: /datadir1
      volumes:
        - name: vdbench-persistent-storage
          persistentVolumeClaim:
            claimName: vdbench-pvc