apiVersion: v1
kind: Secret
metadata:
  name: volume-secrets
  type: Opaque
data:
    test-secret: WW91IHNuZWFreSBsaXR0bGUgcGlnbGV0IQ==
---
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-sv4-sc-svc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  sharedv4: "true"
  sharedv4_svc_type: "ClusterIP"
allowVolumeExpansion: true
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-sv4-pvc-svc-enc
  annotations:
    px/secret-name: volume-secrets
    px/secret-namespace: "_NAMESPACE_"
    px/secret-key: test-secret
    px/secure: "true"
spec:
  storageClassName: test-sv4-sc-svc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

