#!/bin/bash
set +xe
# Loop through all arguments
for arg in "$@"; do
    # Use grep and awk to find and extract the key-value pairs
    if echo "$arg" | grep -q '='; then
        key=$(echo "$arg" | awk -F= '{print $1}')
        value=$(echo "$arg" | awk -F= '{print $2}')
        echo "Setting environment variable: $key=$value"
        export "$key"="$value"
    fi
done

echo $AWS_REGION
echo $SAN_CRED_PSW
echo argsMap.AWS_REGION
sed -i "s/AWS_ACCESS_KEY_ID/$PXB_AWS_ACCESS_KEY_ID_PSW/g" $FILEPATH
sed -i "s/AWS_SECRET_ACCESS_KEY/$SAN_CRED_PSW/g" $FILEPATH
sed -i "s/AWS_REGION/$AWS_REGION/g" $FILEPATH
sed -i "s/AZURE_ACCOUNT_NAME/$SAN_CRED_PSW}/g" "$FILEPATH"
sed -i "s/AZURE_ACCOUNT_KEY/$PXB_AZURE_ACCOUNT_KEY_PSW}/g" $FILEPATH
sed -i "s/AZURE_SUBSCRIPTION_ID/$PXB_AZURE_SUBSCRIPTION_ID_PSW}/g" $FILEPATH
sed -i "s/AZURE_CLIENT_ID/$AZURE_CLIENT_ID_PSW}/g" $FILEPATH
sed -i "s/AZURE_CLIENT_SECRET/$PXB_AZURE_CLIENT_SECRET_PSW}/g" $FILEPATH
sed -i "s/AZURE_TENANT_ID/$AZURE_TENANT_ID_PSW}/g" $FILEPATH
sed -i "s/GCP_PROJECT_ID/$PXB_GCP_PROJECT_ID_PSW}/g" $FILEPATH
sed -i "s/GKE_CLUSTER_NAME/$GKE_CLUSTER_NAME/g" $FILEPATH
sed -i "s/GKE_CLUSTER_LOCATION/$GKE_CLUSTER_LOCATION/g" $FILEPATH
sed -i "s/GKE_PATH_TO_SERVICE_ACCOUNT_JSON/$GKE_PATH_TO_SERVICE_ACCOUNT_JSON/g" $FILEPATH
sed -i "s/IBM_CLOUD_API_KEY/$PXB_IBM_CLOUD_API_KEY_PSW}/g" $FILEPATH
sed -i "s/IBM_CLOUD_ACCOUNT_NAME/$PXB_IBM_CLOUD_ACCOUNT_NAME_PSW}/g" $FILEPATH
sed -i "s/IBM_CLOUD_REGION/$IBM_CLOUD_REGION/g" $FILEPATH
sed -i "s/IBM_CLOUD_RESOURCE_GROUP/$IBM_CLOUD_RESOURCE_GROUP/g" $FILEPATH
sed -i "s/RANCHER_USERNAME/$PXB_RANCHER_USERNAME_USR}/g" $FILEPATH
sed -i "s/RANCHER_PASSWORD/$PXB_RANCHER_PASSWORD_PSW}/g" $FILEPATH
sed -i "s/CLOUD_BUCKET_NAME/$CLOUD_BUCKET_NAME/g" $FILEPATH
sed -i "s/S3_ACCESS_KEY_ID/$PXB_S3_ACCESS_KEY_ID_PSW/g" $FILEPATH
sed -i "s/S3_SECRET_ACCESS_KEY/$PXB_S3_SECRET_ACCESS_KEY_PSW/g" $FILEPATH
sed -i "s/S3_REGION/$S3_REGION/g" $FILEPATH
sed -i "s/SERVER_NAME/$SERVER_NAME/g" $FILEPATH
sed -i "s/SERVER_IP/$PXB_SERVER_IP_USR/g" $FILEPATH
sed -i "s/EXPORT_PATH/$EXPORT_PATH/g" $FILEPATH
sed -i "s/SUB_PATH/$SUB_PATH/g" $FILEPATH
sed -i "s/MOUNT_OPTIONS/$MOUNT_OPTIONS/g" $FILEPATH
sed -i "s/ENCRYPTION_KEY/$ENCRYPTION_KEY/g" $FILEPATH