#!/bin/bash
set +xe
for ARGUMENT in "$@"
do
   KEY=$(echo $ARGUMENT | cut -f1 -d=)
   KEY_LENGTH=${#KEY}
   VALUE="${ARGUMENT:$KEY_LENGTH+1}"
   export "$KEY"="$VALUE"
done

sed -i "s/AWS_ACCESS_KEY_ID/$PSB_AWS_ACCESS_KEY_ID_PSW}/g" $FILEPATH
sed -i "s/AWS_SECRET_ACCESS_KEY/$SAN_CRED_PSW}/g" $FILEPATH
echo $FILEPATH
echo $SAN_CRED_PSW
sed -i "s/AWS_REGION/$AWS_REGION/g" $FILEPATH
sed -i "s/AZURE_ACCOUNT_NAME/$SAN_CRED_PSW}/g" "$FILEPATH"
sed -i "s/AZURE_ACCOUNT_KEY/$PSB_AZURE_ACCOUNT_KEY_PSW}/g" $FILEPATH
sed -i "s/AZURE_SUBSCRIPTION_ID/$AZURE_SUBSCRIPTION_ID_PSW}/g" $FILEPATH
sed -i "s/AZURE_CLIENT_ID/$AZURE_CLIENT_ID_PSW}/g" $FILEPATH
sed -i "s/AZURE_CLIENT_SECRET/$PSB_AZURE_CLIENT_SECRET_PSW}/g" $FILEPATH
sed -i "s/AZURE_TENANT_ID/$AZURE_TENANT_ID_PSW}/g" $FILEPATH
sed -i "s/GCP_PROJECT_ID/$PSB_GCP_PROJECT_ID_PSW}/g" $FILEPATH
sed -i "s/GKE_CLUSTER_NAME/$GKE_CLUSTER_NAME/g" $FILEPATH
sed -i "s/GKE_CLUSTER_LOCATION/$GKE_CLUSTER_LOCATION/g" $FILEPATH
sed -i "s/GKE_PATH_TO_SERVICE_ACCOUNT_JSON/$GKE_PATH_TO_SERVICE_ACCOUNT_JSON/g" $FILEPATH
sed -i "s/IBM_CLOUD_API_KEY/$PSB_IBM_CLOUD_API_KEY_PSW}/g" $FILEPATH
sed -i "s/IBM_CLOUD_ACCOUNT_NAME/$PSB_IBM_CLOUD_ACCOUNT_NAME_PSW}/g" $FILEPATH
sed -i "s/IBM_CLOUD_REGION/$IBM_CLOUD_REGION/g" $FILEPATH
sed -i "s/IBM_CLOUD_RESOURCE_GROUP/$IBM_CLOUD_RESOURCE_GROUP/g" $FILEPATH
sed -i "s/RANCHER_USERNAME/$PSB_RANCHER_USERNAME_USR}/g" $FILEPATH
sed -i "s/RANCHER_PASSWORD/$PSB_RANCHER_PASSWORD_PSW}/g" $FILEPATH
sed -i "s/CLOUD_BUCKET_NAME/$CLOUD_BUCKET_NAME/g" $FILEPATH
sed -i "s/S3_ACCESS_KEY_ID/env.PSB_S3_ACCESS_KEY_ID_PSW/g" $FILEPATH
sed -i "s/S3_SECRET_ACCESS_KEY/env.PSB_S3_SECRET_ACCESS_KEY_PSW/g" $FILEPATH
sed -i "s/S3_REGION/$S3_REGION/g" $FILEPATH
sed -i "s/SERVER_NAME/$SERVER_NAME/g" $FILEPATH
sed -i "s/SERVER_IP/env.PSB_SERVER_IP_USR/g" $FILEPATH
sed -i "s/EXPORT_PATH/$EXPORT_PATH/g" $FILEPATH
sed -i "s/SUB_PATH/$SUB_PATH/g" $FILEPATH
sed -i "s/MOUNT_OPTIONS/$MOUNT_OPTIONS/g" $FILEPATH
sed -i "s/ENCRYPTION_KEY/$ENCRYPTION_KEY/g" $FILEPATH