apiVersion: v1
kind: ServiceAccount
metadata:
  name: torpedo-account
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
   name: torpedo-role
rules:
  -
    apiGroups:
      # have access to everything except Secrets
      - "*"
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: torpedo-role-binding
subjects:
- apiVersion: v1
  kind: ServiceAccount
  name: torpedo-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: torpedo-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: torpedo
spec:
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Equal
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
  containers:
  - name: torpedo
    image: harshpx/torpedo:latest
<<<<<<< HEAD
    command: ["./torpedo", "fire", "--scheduler", "k8s", "--storage", "pxd", "--node-driver", "ssh", "--tests", "testSetupTearDown", "--log-location", "/mnt/torpedo_support_bundle" ]
    tty: true
    volumeMounts:
    - mountPath: /mnt/torpedo_support_bundle
=======
    #command: ["./torpedo", "fire", "--scheduler", "k8s", "--storage", "pxd", "--node-driver", "ssh" ]
    command: ["./torpedo", "fire", "--scheduler", "k8s", "--storage", "pxd", "--node-driver", "ssh", "--tests", "testSetupTearDown", "--log-location", "/mnt/tsb" ]
    tty: true
    volumeMounts:
    - mountPath: /mnt/tsb
>>>>>>> 9b4d1b2... Adding a log location attribute to torpedo obj, specifying defaults
      name: support-bundle-path
  restartPolicy: Never
  serviceAccountName: torpedo-account
  volumes:
    - name: support-bundle-path
      hostPath:
<<<<<<< HEAD
        path: /mnt/torpedo_support_bundle
=======
        path: /mnt/tsb
>>>>>>> 9b4d1b2... Adding a log location attribute to torpedo obj, specifying defaults
