##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-sc-trim
provisioner: kubernetes.io/portworx-volume
parameters:
  {{ if .Repl }}
  repl: "{{ .Repl }}"
  {{ else }}
  repl: "2"{{ end }}
  priority_io: "high"
  io_profile: "db_remote"
  nodiscard: "true"
allowVolumeExpansion: true
---
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-log-trim
provisioner: kubernetes.io/portworx-volume
parameters:
  {{ if .Repl }}
  repl: "{{ .Repl }}"
  {{ else }}
  repl: "3"{{ end }}
  priority_io: "high"
  io_profile: "db_remote"
  nodiscard: "true"
allowVolumeExpansion: true
