apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim-legacy-shared
  labels:
    app: wordpress
spec:
  storageClassName: wordpress-sc-legacy-shared
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-1
spec:
  storageClassName: wordpress-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
