##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-cloudsnap-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  {{ if .Repl }}
  repl: "{{ .Repl }}"
  {{ else }}
  repl: "3"{{ end }}
  priority_io: "high"
  io_profile: "db_remote"
  snapshotschedule.stork.libopenstorage.org/interval-schedule: |
    schedulePolicyName: intervalpolicy
    annotations:
      portworx/snapshot-type: cloud
allowVolumeExpansion: true
