{{- $defaultClaimsCount := 8 }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: yes-and-fio-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-bionic
        kubevirt-key: kubevirt-val
        app: yes-and-fio-vm
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - name: containervolume
              disk:
                bus: virtio
            {{- if gt .ClaimsCount 0}}
            {{- range $i := Iterate .ClaimsCount}}
            - name: datavolume{{ $i }}
              disk:
                bus: virtio
              {{- end}}
            {{- else}}
            {{- range $i := Iterate $defaultClaimsCount}}
            - name: datavolume{{ $i }}
              disk:
                bus: virtio
              {{- end}}
            {{- end}}
            - name: cloudinitvolume
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            cpu: 4
            memory: 8192M
      networks:
        - name: default
          pod: {}
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
        - name: containervolume
          persistentVolumeClaim:
            claimName: fio-boot-pvc
        {{- if .ClaimsCount }}
        {{- range $val := Iterate .ClaimsCount }}
        - name: datavolume{{ $val }}
          persistentVolumeClaim:
            claimName: fio-disk-{{ $val }}
          {{- end }}
        {{- else }}
        {{- range $val := Iterate $defaultClaimsCount }}
        - name: datavolume{{ $val }}
          persistentVolumeClaim:
            claimName: fio-disk-{{ $val }}
          {{- end }}
        {{- end }}
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              packages:
                - fio
              chpasswd:
                list: |
                  ubuntu:ubuntu
                  root:toor
                expire: False
              runcmd:
                - mkdir -p /mnt/data
                - |
                  # Run fio to generate disk I/O
                  fio --name=randrw --rw=randrw --bs=4k --size=1G --numjobs=1 --time_based --runtime=300 --group_reporting --directory=/mnt/data &
                - |
                  # Use yes to generate file-based I/O by redirecting output to a file on a disk backed by a PVC
                  yes "This is disk I/O generated by yes" > /mnt/data/yes_output.txt &