apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: large-data-gen-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  priority_io: "high"
  io_profile: "db_remote"
  repl: "3"
  sharedv4: "true"
allowVolumeExpansion: true