sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.11.2
before_install:
  - sudo apt-get update -yq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -yq docker-ce
script:
  - curl -s -L https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - make vendor
  - make all
after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin;
      make container;
      sudo docker tag "${DOCKER_HUB_REPO}/${DOCKER_HUB_TORPEDO_IMAGE}:${DOCKER_HUB_TAG}" "${DOCKER_HUB_REPO}/${DOCKER_HUB_TORPEDO_IMAGE}:${TRAVIS_BRANCH}";
      sudo docker push "${DOCKER_HUB_REPO}/${DOCKER_HUB_TORPEDO_IMAGE}:${DOCKER_HUB_TAG}";
      sudo docker push "${DOCKER_HUB_REPO}/${DOCKER_HUB_TORPEDO_IMAGE}:${TRAVIS_BRANCH}";
    fi
notifications:
  email:
    recipients:
      - aditya@portworx.com
      - piyush@portworx.com
      - harsh@portworx.com
    on_success: change
    on_failure: always
