##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nginx-sc-auth-cloud
provisioner: kubernetes.io/portworx-volume
parameters:
  openstorage.io/auth-secret-name: px-user-token
  # This will be fixed to have non hard code value for namespace - PTX-27677
  openstorage.io/auth-secret-namespace: kube-system
  repl: "2"
  snapshotschedule.stork.libopenstorage.org/test-schedule: |
    schedulePolicyName: auto-schedule-policy
    reclaimPolicy: Delete
    annotations:
      portworx/snapshot-type: cloud
allowVolumeExpansion: true