##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-sv4-sc-svc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  {{ if .StorageClassSharedv4 }}
  sharedv4: {{ .StorageClassSharedv4 }}
  {{ else }}
  sharedv4: "true"{{ end }}
allowVolumeExpansion: true
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-sv4-pvc-svc
spec:
  storageClassName: test-sv4-sc-svc
  accessModes:
  {{ if .PVCAccessMode }}
    - {{ .PVCAccessMode }}
  {{ else }}
   - ReadWriteMany {{ end }}
  resources:
    requests:
      storage: 50Gi

