---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vdbench-sc-sv4
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  sharedv4: "true"
  mount_options: "nodiscard=true"
allowVolumeExpansion: true