##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-overlapping-io-sc
provisioner: pxd.portworx.com
parameters:
  backend: "pure_block"
  max_bandwidth: "2G"
  csi.storage.k8s.io/fstype: xfs
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-overlapping-io-pvc
spec:
  storageClassName: fio-overlapping-io-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi