##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-sharedv4-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  sharedv4: "true"
  sharedv4_svc_type: ""
allowVolumeExpansion: true
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-sharedv4-pvc
spec:
  storageClassName: test-sharedv4-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

