---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vdbench-sc-sharedv4
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  sharedv4: "true"
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vdbench-pvc-sharedv4
spec:
  storageClassName: vdbench-sc-sharedv4
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi