apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-validation-write-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: data-validation-sc