apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
  clusterIP: None
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: discovery.type
              value: single-node
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: elasticsearch-sc
        resources:
          requests:
            storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: io-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: io-app
  template:
    metadata:
      labels:
        app: io-app
    spec:
      containers:
        - name: io-container
          image: appropriate/curl
          command: ["/bin/sh", "-c", "while true; do \
          timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ); \
          value=$((RANDOM % 100)); \
          user_id=$((RANDOM % 1000)); \
          status=$(if [ $((RANDOM % 2)) -eq 0 ]; then echo \"active\"; else echo \"inactive\"; fi); \
          large_text=$(head -c 10000 </dev/urandom | tr -dc A-Za-z0-9); \
          json_payload=$(printf '{\"timestamp\": \"%s\", \"message\": \"Hello from the I/O app\", \"value\": %d, \"user_id\": %d, \"status\": \"%s\", \"large_text\": \"%s\"}' \"$timestamp\" \"$value\" \"$user_id\" \"$status\" \"$large_text\"); \
          curl -X POST \"http://elasticsearch:9200/my-index/_doc/\" -H 'Content-Type: application/json' -d \"$json_payload\"; \
          done"]