##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: px-nginx-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   fs: "ext4"
   block_size: "512b"
   repl: "3"
   aggregation_level: "1"
   io_profile: "sequential"
   priority_io: "high"
   shared: "true"
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-nginx-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: px-nginx-sc
spec:
   accessModes:
     - ReadWriteMany
   resources:
     requests:
       storage: 1Gi
