apiVersion: v1
kind: Pod
metadata:
  name: querying-app-5
spec:
  restartPolicy: Never
  containers:
    - name: ml-workload
      image: portworx/ml-workload:v2
      command:
        - /bin/bash
        - -c
      args:
        - python query.py && sleep 100
      env:
        - name: OUTPUT_FILE
          value: query_output_5.csv
      volumeMounts:
        - name: ml-shared-data
          mountPath: /mnt/data
  volumes:
    - name: ml-shared-data
      persistentVolumeClaim:
        claimName: ml-workload-pvc
  imagePullSecrets: []
