---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: 3
  selector:
    matchLabels:
      component: elasticsearch
      role: data
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      securityContext:
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - data
                topologyKey: kubernetes.io/hostname
      initContainers:
        - name: init-sysctl
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: es-data
          image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              value: my-es
            - name: NUMBER_OF_MASTERS
              value: "2"
            - name: NODE_MASTER
              value: "false"
            - name: NODE_INGEST
              value: "false"
            - name: NODE_DATA
              value: "true"
            - name: HTTP_ENABLE
              value: "true"
            - name: NETWORK_HOST
              value: _site_
            - name: DISCOVERY_SERVICE
              value: elasticsearch-discovery
#            - name: ES_JAVA_OPTS
#              value: -Xms256m -Xmx256m
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          resources:
            limits:
              cpu: 1
          ports:
            - containerPort: 9300
              name: transport
          volumeMounts:
            - name: es-data
              mountPath: /data/data
            - name: es-log
              mountPath: /data/log
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-config
          configMap:
            name: es-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        storageClassName: elasticsearch-sc
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 256Gi
    - metadata:
        name: es-log
      spec:
        storageClassName: elasticsearch-sc
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 128Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  labels:
    component: elasticsearch
    role: data
spec:
  ports:
    - port: 9300
      name: transport
  clusterIP: None
  selector:
    component: elasticsearch
    role: data