---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  elasticsearch.yml: |
    cluster:
      name: ${CLUSTER_NAME}
      routing:
        use_adaptive_replica_selection: true
    node:
      master: ${NODE_MASTER}
      data: ${NODE_DATA}
      name: ${NODE_NAME}
      ingest: ${NODE_INGEST}
      max_local_storage_nodes: 1
    processors: ${PROCESSORS:1}
    network.host: ${NETWORK_HOST}
    path:
      data: /data/data
      logs: /data/log
    bootstrap:
      memory_lock: false
    http:
      enabled: ${HTTP_ENABLE}
      compression: true
      cors:
        enabled: true
        allow-origin: "*"
    discovery:
      zen:
        ping.unicast.hosts: ${DISCOVERY_SERVICE}
        minimum_master_nodes: ${NUMBER_OF_MASTERS}
    xpack.ml.enabled: false
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    thread_pool:
      write:
        queue_size: 500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-master
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 3
  selector:
    matchLabels:
      component: elasticsearch
      role: master
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - master
                topologyKey: kubernetes.io/hostname
      initContainers:
        - name: init-sysctl
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: es-master
          image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              value: my-es
            - name: NUMBER_OF_MASTERS
              value: "2"
            - name: NODE_MASTER
              value: "true"
            - name: NODE_INGEST
              value: "false"
            - name: NODE_DATA
              value: "false"
            - name: HTTP_ENABLE
              value: "true"
            - name: NETWORK_HOST
              value: _site_
            - name: DISCOVERY_SERVICE
              value: elasticsearch-discovery
#            - name: ES_JAVA_OPTS
#              value: -Xms256m -Xmx256m
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          resources:
            limits:
              cpu: 1
          ports:
            - containerPort: 9300
              name: transport
          volumeMounts:
            - name: es-data
              mountPath: /data
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-config
          configMap:
            name: es-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
        - emptyDir:
            medium: ""
          name: "es-data"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master
  ports:
    - name: transport
      port: 9300
      protocol: TCP
  clusterIP: None