##### Portworx PVC clone from VolumeSnapshot using Stork
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mysql-snap-clone
   annotations:
     snapshot.alpha.kubernetes.io/snapshot: mysql-snapshot
     torpedo/resize-supported: "false"
spec:
   storageClassName: stork-snapshot-sc
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
