apiVersion: v1
kind: Secret
metadata:
  name: volume-secrets
type: Opaque
data:
  mysql-secret: WW91IHNuZWFreSBsaXR0bGUgcGlnbGV0IQ==
---
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-mysql-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  fs: "ext4"
  block_size: "512b"
  repl: "3"
  aggregation_level: "1"
  io_profile: "db"
  priority_io: "high"
  shared: "false"
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data
  annotations:
    px/secret-name: volume-secrets
    px/secret-namespace: "{{NAMESPACE}}"
    px/secret-key: mysql-secret
    volume.beta.kubernetes.io/storage-class: px-mysql-sc
spec:
  storageClassName: px-mysql-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
