apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql-stork-clone
  labels:
    app: mysql-stork-clone
spec:
  selector:
    matchLabels:
      app: mysql-stork-clone
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-stork-clone
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      - name: mysqlslap
        image: piyushpx/mysqlslap
        imagePullPolicy: "Always"
        env:
        - name: MYSQL_HOST
          value: localhost
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: password
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-snap-clone
