apiVersion: v1
kind: Service
metadata:
  name: mysql-clone
  labels:
    app: mysql-clone
spec:
  ports:
  - port: 3307
    targetPort: 3306
  selector:
    app: mysql-clone
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql-clone
  labels:
    app: mysql-clone
spec:
  selector:
    matchLabels:
      app: mysql-clone
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-clone
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: ns.{{NAMESPACE}}-name.mysql-snap-clone
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysqlslap-clone
  labels:
    app: mysql-clone
spec:
  selector:
    matchLabels:
      app: mysql-clone
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-clone
    spec:
      containers:
      - name: mysqlslap
        image: adityadani/mysqlslap
        imagePullPolicy: "Always"
        env:
        - name: MYSQL_SERVICE_HOST
          value: mysql-clone.default.svc.cluster.local
        - name: MYSQL_SERVICE_PORT
          value: "3307"
        - name: MYSQL_ROOT_PASSWORD
          value: password
