##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-throttle-io-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  priority_io: "high"
  repl: "1"
  fs: "ext4"
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-throttle-io-pvc
spec:
  storageClassName: fio-throttle-io-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
