apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-longevity-multi-disk
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: http://kubevirt-disk-registry.pwx.dev.purestorage.com/more_images/debian-12-4.qcow2
spec:
  storageClassName: kubevirt-longevity-multi-pvc-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
