##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-vps-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  placement_strategy: "fastpath-repl1-fio-vps"
  repl: "1"
  priority_io: "high"
allowVolumeExpansion: true
---
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-vps-log
provisioner: kubernetes.io/portworx-volume
parameters:
  placement_strategy: "fastpath-repl1-fio-vps"
  repl: "1"
  priority_io: "high"
allowVolumeExpansion: true
