##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-sv4-svc-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  priority_io: "high"
  io_profile: "db_remote"
  repl: "3"
  sharedv4: "true"
  sharedv4_svc_type: "ClusterIP"
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-sv4-svc-pvc
spec:
  storageClassName: fio-sv4-svc-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      {{ if .VolumeSize }}
      storage: {{ .VolumeSize }}
      {{ else }}
      storage: 2000Gi{{ end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-sv4-svc-output-pvc
spec:
  storageClassName: fio-sv4-svc-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi