---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio
  labels:
    app: fio
spec:
  serviceName: fio
  {{ if .Replicas }}
  replicas: {{ .Replicas }}
  {{ else }}
  replicas: 25{{ end }}
  selector:
    matchLabels:
      app: fio
  template:
    metadata:
      labels:
        app: fio
    spec:
      schedulerName: stork
      containers:
        - name: fio
          image: joshuarobinson/fio:3.19
          command: ["sh"]
          args: ["-c", "mkdir -p /scratch/$(POD_NAME) /var/log/$(POD_NAME) && fio /configs/fio.job --eta=never --directory=/scratch/$(POD_NAME) --output=/var/log/$(POD_NAME)/fio.log"]
          volumeMounts:
            - env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
            - name: fio-config-vol
              mountPath: /configs
            - name: fio-data
              mountPath: /scratch
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "500m"
              memory: 4Gi
            requests:
              cpu: "500m"
              memory: 4Gi
      restartPolicy: Always
      volumes:
        - name: fio-config-vol
          configMap:
            name: fio-job-config
        - name: fio-data
          persistentVolumeClaim:
            claimName: fio-sv4-svc-pvc