apiVersion: v1
kind: Secret
metadata:
  name: volume-secrets
data:
  encryption-key: "RW5DcllwVGlPbjRFdjNyCg=="
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-vol-encryption
data:
  SECRET_NAME: "dm9sdW1lLXNlY3JldHM="
  SECRET_KEY: "ZW5jcnlwdGlvbi1rZXk="
  SECRET_CONTEXT: "_NAMESPACE_" # this will be replaced with app namespace in base64
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: elasticsearch-enc-sc
provisioner: pxd.portworx.com
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: elasticsearch-vol-encryption
  csi.storage.k8s.io/controller-expand-secret-namespace: "_NAMESPACE_"
  csi.storage.k8s.io/node-publish-secret-name: elasticsearch-vol-encryption
  csi.storage.k8s.io/node-publish-secret-namespace: "_NAMESPACE_"
  csi.storage.k8s.io/provisioner-secret-name: elasticsearch-vol-encryption
  csi.storage.k8s.io/provisioner-secret-namespace: "_NAMESPACE_"
  csi.storage.k8s.io/fstype: ext4
  {{ if .PureFaPodName }}
  pure_fa_pod_name: "{{ .PureFaPodName }}"
  {{ end }}
  backend: "pure_block"
  max_iops: "30000"
  max_bandwidth: "10G"
  secure: "true"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true