package tests

import (
	"context"
	"fmt"
	"os"
	"time"

	. "github.com/onsi/ginkgo/v2"
	"github.com/pborman/uuid"
	api "github.com/portworx/px-backup-api/pkg/apis/v1"
	"github.com/pure-px/torpedo/drivers/backup"
	"github.com/pure-px/torpedo/drivers/scheduler"
	"github.com/pure-px/torpedo/pkg/log"
	. "github.com/pure-px/torpedo/tests"
)

var _ = Describe("{BackupScheduleEnumerate}", Ordered, Label(TestCaseLabelsMap[BackupScheduleEnumerate]...), func() {
	var (
		scheduledAppContexts                  []*scheduler.Context
		providers                             []string = GetBackupProviders()
		bkpNamespaces                         []string
		backupScheduleList                    []string
		schedulePolicyName, schedulePolicyUid string
		cloudCredName, cloudCredUID           string
		backupLocationMap                     map[string]string
		adminContext                          context.Context
		sourceClusterUID                      string
		backupLocationUID                     string
		bkpLocationName                       string
		numberOfSchedules                     uint64
	)
	BeforeAll(func() {
		backupLocationMap = make(map[string]string)

		// Schedule an Application
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}

		// Validate the application
		ValidateApplications(scheduledAppContexts)

		// Get Admin User Context
		var err error
		adminContext, err = backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin user ctx")

		// Create Schedule Policy
		log.InfoD("Creating backup monthly schedule policy")
		schedulePolicyName = fmt.Sprintf("%s-%s", "monthly", RandomString(5))
		schedulePolicyUid = uuid.New()
		monthlySchedulePolicyInfo := Inst().Backup.CreateMonthlySchedulePolicy(1, 29, "9:20AM", 2)
		monthlyPolicyStatus := Inst().Backup.BackupSchedulePolicy(schedulePolicyName, schedulePolicyUid, BackupOrgID, monthlySchedulePolicyInfo)
		dash.VerifyFatal(monthlyPolicyStatus, nil, "Creating monthly schedule policy")

		cloudCredName, cloudCredUID = "", uuid.New()
		for _, provider := range providers {
			// Create Cloud Credential
			cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
			err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))

			// Create BackupLocation
			bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
			backupLocationUID = uuid.New()
			backupLocationMap[backupLocationUID] = bkpLocationName
			err = CreateBackupLocationWithContext(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", adminContext, true)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
		}

		// Create a cluster object with User1
		err = AddSourceCluster(adminContext)
		dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of source [%s] cluster with admin ctx", SourceClusterName))
		sourceClusterUID, err = Inst().Backup.GetClusterUID(adminContext, BackupOrgID, SourceClusterName)
		dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))

		// Create monthly backup schedule objects
		backupScheduleList = make([]string, 0)
		numberOfSchedules = 5
		for i := 0; i < int(numberOfSchedules); i++ {
			scheduleName := fmt.Sprintf("schedule-bkp-%v", RandomString(5))
			_, err := CreateScheduleBackupWithoutCheck(scheduleName, SourceClusterName, sourceClusterUID, bkpLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", schedulePolicyName, schedulePolicyUid, adminContext, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of scheduled backup with schedule name [%s]", scheduleName))
			backupScheduleList = append(backupScheduleList, scheduleName)
		}
	})

	// This testcase is to verify Max Objects should return only maximum number of objects during the backupSchedule enumerate.
	It("VerifyMaxObjects", func() {
		StartPxBackupTorpedoTest("VerifyMaxObjects", "Verify maximum number of schedule objects where return during the schedule enumerate", nil, 302831, "sgajawada", Q3FY25)
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		Step("Enumerate BackupSchedule to test MaxObjects", func() {
			var maxObjects uint64 = 3
			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					MaxObjects: maxObjects,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), int(maxObjects), fmt.Sprintf("verify max objects %v in backup schedule enumerate response", maxObjects))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), numberOfSchedules, fmt.Sprintf("verify total count %v in backup schedule enumerate response", numberOfSchedules))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), false, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", false))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetBackupSchedules()[0].Name, backupScheduleList[4], fmt.Sprintf("verify initial object: %v in the response", backupScheduleList[4]))
		})
	})

	// This testcase is to verify Object Index should return only from starting index of list during the backupSchedule enumerate.
	It("VerifyStartingIndex", func() {
		StartPxBackupTorpedoTest("VerifyStartingIndex", "Verify all the objects before starting index where skipped during the schedule enumerate", nil, 302832, "sgajawada", Q3FY25)
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		Step("Enumerate BackupSchedule to test ObjectIndex", func() {
			var startingIndex uint64 = 1
			var remainingObjects int = 4

			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					ObjectIndex: startingIndex,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), remainingObjects, fmt.Sprintf("verify remaining objects %v in backup schedule enumerate response", remainingObjects))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), numberOfSchedules, fmt.Sprintf("verify total count %v in backup schedule enumerate response", numberOfSchedules))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), false, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", false))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetBackupSchedules()[0].Name, backupScheduleList[3], fmt.Sprintf("verify initial object: %v in the response", backupScheduleList[3]))
		})
	})

	// This testcase is to verify Object Index and Max Objects should return maximum objects from starting index of list during the backupSchedule enumerate.
	It("VerifyMaxObjectsWithStartingIndex", func() {
		StartPxBackupTorpedoTest("VerifyMaxObjectsWithStartingIndex", "Verify all the objects before starting index where skipped and only maximum objects where return during the schedule enumerate", nil, 302833, "sgajawada", Q3FY25)
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		Step("Enumerate BackupSchedule to test MaxObjects and ObjectIndex", func() {
			var maxObjects uint64 = 3
			var startingIndex uint64 = 2

			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					MaxObjects:  maxObjects,
					ObjectIndex: startingIndex,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), int(maxObjects), fmt.Sprintf("verify max objects %v in backup schedule enumerate response", maxObjects))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), numberOfSchedules, fmt.Sprintf("verify total count %v in backup schedule enumerate response", numberOfSchedules))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), true, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", true))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetBackupSchedules()[0].Name, backupScheduleList[2], fmt.Sprintf("verify initial object: %v in the response", backupScheduleList[2]))
		})
	})

	// This testcase is to verify name filter should return matched objects during the backupSchedule enumerate.
	It("VerifyNameFilter", func() {
		StartPxBackupTorpedoTest("VerifyNameFilter", "Verify matched objects where return during the schedule enumerate", nil, 302834, "sgajawada", Q3FY25)
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		Step("Enumerate BackupSchedule to test NameFilter", func() {
			searchString := backupScheduleList[1][:len(backupScheduleList[1])-1]
			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					NameFilter: searchString,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), 1, fmt.Sprintf("verify name matching objects %v in backup schedule enumerate response", 1))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), uint64(1), fmt.Sprintf("verify total count %v in backup schedule enumerate response", 1))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), true, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", true))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetBackupSchedules()[0].Name, backupScheduleList[1], fmt.Sprintf("verify initial object: %v in the response", backupScheduleList[2]))
		})
	})

	// This testcase is to verify name filter with object index and max objects should return maximum matched objects from starting index of list during the backupSchedule enumerate.
	It("VerifyNameFilterWithObjectIndexAndMaxObjects", func() {
		StartPxBackupTorpedoTest("VerifyNameFilterWithObjectIndexAndMaxObjects", "Verify all the matched objects before starting index where skipped and only maximum objects where return during the schedule enumerate", nil, 302835, "sgajawada", Q3FY25)
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		var newBackupScheduleList []string

		Step("Create 5 BackupSchedule Objects", func() {
			// Create monthly backup schedule objects
			newBackupScheduleList = make([]string, 0)
			for i := 0; i < 5; i++ {
				scheduleName := fmt.Sprintf("new-schedule-bkp-%v", RandomString(5))
				_, err := CreateScheduleBackupWithoutCheck(scheduleName, SourceClusterName, sourceClusterUID, bkpLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", schedulePolicyName, schedulePolicyUid, adminContext, false)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of scheduled backup with schedule name [%s]", scheduleName))
				newBackupScheduleList = append(newBackupScheduleList, scheduleName)
			}
		})

		Step("Enumerate BackupSchedule to test NameFilter with MaxObjects and ObjectIndex", func() {
			var maxObjects uint64 = 3
			var startingIndex uint64 = 1
			searchString := "new"

			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					MaxObjects:  maxObjects,
					ObjectIndex: startingIndex,
					NameFilter:  searchString,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), int(maxObjects), fmt.Sprintf("verify max objects %v in backup schedule enumerate response", maxObjects))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), uint64(5), fmt.Sprintf("verify total count %v in backup schedule enumerate response", 5))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), false, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", false))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetBackupSchedules()[0].Name, newBackupScheduleList[3], fmt.Sprintf("verify initial object: %v in the response", backupScheduleList[2]))
		})

		Step("Enumerate BackupSchedule Object Again", func() {
			var maxObjects uint64 = 3
			var startingIndex uint64 = 4
			searchString := "new"

			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					MaxObjects:  maxObjects,
					ObjectIndex: startingIndex,
					NameFilter:  searchString,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), 1, fmt.Sprintf("verify max objects %v in backup schedule enumerate response", 1))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), uint64(5), fmt.Sprintf("verify total count %v in backup schedule enumerate response", 5))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), true, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", true))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetBackupSchedules()[0].Name, newBackupScheduleList[0], fmt.Sprintf("verify initial object: %v in the response", backupScheduleList[2]))
		})

		Step("Cleanup", func() {
			searchString := "new"
			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					NameFilter: searchString,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), 5, fmt.Sprintf("verify max objects %v in backup schedule enumerate response", 5))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), uint64(5), fmt.Sprintf("verify total count %v in backup schedule enumerate response", 5))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), true, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", true))

			for _, schedule := range backupScheduleEnumerateResponse.BackupSchedules {
				err = DeleteScheduleWithUIDAndWait(schedule.Name, schedule.Uid, SourceClusterName, sourceClusterUID, BackupOrgID, adminContext)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of backup schedule [%s]", schedule))
			}
		})

	})

	AfterAll(func() {
		// Delete the backup schedules
		scheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
			OrgId: BackupOrgID,
		}
		scheduleList, err := Inst().Backup.EnumerateBackupSchedule(adminContext, scheduleEnumerateRequest)
		log.FailOnError(err, "failed to enumerate backup schedules")
		for _, schedule := range scheduleList.BackupSchedules {
			err = DeleteScheduleWithUIDAndWait(schedule.Name, schedule.Uid, SourceClusterName, sourceClusterUID, BackupOrgID, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of backup schedule [%s]", schedule))
		}

		// Delete the schedule policy
		log.InfoD("Deleting schedule policy [%s]", schedulePolicyName)
		schedulePolicyDeleteRequest := &api.SchedulePolicyDeleteRequest{
			Name:  schedulePolicyName,
			Uid:   schedulePolicyUid,
			OrgId: BackupOrgID,
		}
		_, err = Inst().Backup.DeleteSchedulePolicy(adminContext, schedulePolicyDeleteRequest)
		log.FailOnError(err, "failed to delete schedule policy [%s]", schedulePolicyName)

		// Delete the backups
		backupEnumerateRequest := &api.BackupEnumerateRequest{
			OrgId: BackupOrgID,
		}
		backupList, err := Inst().Backup.EnumerateBackup(adminContext, backupEnumerateRequest)
		log.FailOnError(err, "failed to enumerate backups")
		for _, backup := range backupList.Backups {
			err = DeleteBackupAndWaitForCompletion(backup.Name, backup.Uid, BackupOrgID, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backup))
		}

		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		log.InfoD("Deleting deployed applications")
		DestroyApps(scheduledAppContexts, opts)
		err = DeleteNamespaces(bkpNamespaces)
		log.FailOnError(err, "failed to delete namespaces")
		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, adminContext)
	})
})

// Change the schedule policy associated with a generic backup
var _ = Describe("{ChangeSchedulePolicyAssociatedWithGenericBackup}", Label(TestCaseLabelsMap[ChangeSchedulePolicyAndVerifyBackups]...), func() {

	var (
		scheduledAppContexts        []*scheduler.Context
		bkpNamespaces               []string
		clusterUid                  string
		clusterStatus               api.ClusterInfo_StatusInfo_Status
		backupLocationUID           string
		cloudCredName               string
		cloudCredUID                string
		primarySchedulePolicyName   string
		primarySchedulePolicyUID    string
		secondarySchedulePolicyName string
		secondarySchedulePolicyUID  string
		schedulePolicyMap           map[string]string
		scheduleName                string
		bkpLocationName             string
		backupNames                 []string
		providers                   []string
		labelSelectors              = make(map[string]string)
		adminCtx                    context.Context
		backupLocationMap           map[string]string
		schedulePolicyInterval      int64
		retainCountOne              int64
		retainCountTwo              int64
		scheduleNames               []string
		firstScheduleBackupName     string
		backupWaitTime              time.Duration
		backupTypeEnvVar            string
	)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyChangeSchedulePolicyAssociatedWithGenericBackup", "Change the schedule policy associated with a generic backup", nil, 300170, ABadgujar, Q1FY25)
		providers = GetBackupProviders()
		backupLocationMap = make(map[string]string)
		bkpNamespaces = make([]string, 0)
		backupNames = make([]string, 0)
		scheduleNames = make([]string, 0)
		schedulePolicyMap = make(map[string]string)
		schedulePolicyInterval = 15
		retainCountOne = 2
		retainCountTwo = 1
		scheduledAppContexts = make([]*scheduler.Context, 0)
		var err error
		adminCtx, err = backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		backupWaitTime = time.Duration(time.Minute) * 16

		//Get Environment variable
		backupTypeEnvVar = os.Getenv("BACKUP_TYPE")

		err = os.Setenv("BACKUP_TYPE", "direct_kdmp")
		log.FailOnError(err, "Setting BACKUP_TYPE env variable")

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
	})

	// Change the schedule policy associated with a generic backup
	It("Change the schedule policy associated with a generic backup", func() {
		// 1. Validate application
		Step("Validate applications", func() {
			log.InfoD("Validating applications")
			ValidateApplications(scheduledAppContexts)
		})

		// 2. Create primary schedule policy
		Step("Create primary schedule policy", func() {
			log.InfoD("Create primary schedule policy")
			primarySchedulePolicyName = fmt.Sprintf("%s-%v", "periodic-schedule-policy", 1)
			primarySchedulePolicyUID = uuid.New()
			schedulePolicyMap[primarySchedulePolicyUID] = primarySchedulePolicyName
			err := CreateBackupScheduleIntervalPolicy(retainCountOne, schedulePolicyInterval, 5, primarySchedulePolicyName, primarySchedulePolicyUID, BackupOrgID, adminCtx, false, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of schedule policy %s", primarySchedulePolicyName))
		})

		// 3. Create secondary schedule policy
		Step("Create secondary schedule policy", func() {
			log.InfoD("Create secondary schedule policy")
			secondarySchedulePolicyName = fmt.Sprintf("%s-%v", "periodic-schedule-policy", 2)
			secondarySchedulePolicyUID = uuid.New()
			schedulePolicyMap[secondarySchedulePolicyUID] = secondarySchedulePolicyName
			err := CreateBackupScheduleIntervalPolicy(retainCountTwo, schedulePolicyInterval, 5, secondarySchedulePolicyName, secondarySchedulePolicyUID, BackupOrgID, adminCtx, false, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of schedule policy %s", secondarySchedulePolicyName))
		})

		// 4. Create cloud credentials and backup location
		Step("Creating cloud credentials and backup location", func() {
			log.InfoD("Creating cloud credentials and backup location")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cloudcred", provider, time.Now().Unix())
				bkpLocationName = fmt.Sprintf("%s-%s-%v-bl", provider, getGlobalBucketName(provider), time.Now().Unix())
				cloudCredUID = uuid.New()
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, adminCtx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				err = CreateBackupLocation(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		// 5. Create application cluster for backup
		Step("Register cluster for backup", func() {
			log.InfoD("Register cluster for backup")
			err := CreateApplicationClusters(BackupOrgID, "", "", adminCtx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, adminCtx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = Inst().Backup.GetClusterUID(adminCtx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
			log.InfoD("Uid of [%s] cluster is %s", SourceClusterName, clusterUid)
		})

		// 5. Take the backup of bkNamespaces setting retain count to 2
		Step("Take the backup of bkNamespaces setting retain count to 2", func() {
			log.InfoD("Take the backup of bkNamespaces setting retain count to 2")
			var err error
			appContextsToBackup := FilterAppContextsByNamespace(scheduledAppContexts, bkpNamespaces)
			scheduleName = fmt.Sprintf("%s-%s-%s", "schedule", "backup", "1")
			scheduleNames = append(scheduleNames, scheduleName)
			firstScheduleBackupName, err = CreateScheduleBackupWithValidation(adminCtx, scheduleName, SourceClusterName, clusterUid, bkpLocationName, backupLocationUID, appContextsToBackup, labelSelectors, BackupOrgID, "", "", "", "", primarySchedulePolicyName, primarySchedulePolicyUID, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of schedule backup with schedule name [%s]", primarySchedulePolicyName))
			backupNames = append(backupNames, firstScheduleBackupName)
			_, err = GetNextScheduleBackupName(scheduleName, time.Duration(schedulePolicyInterval), adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching name of the scheduled backup with schedule after setting retain count to 2 -[%s]", scheduleName))
		})

		//6. Enumerate Backups and check the number of backups retained
		Step("Enumerate Backups and check the number of backups retained", func() {
			log.InfoD("Enumerate Backups and check the number of backups retained")
			backupEnumerateRequest := &api.BackupEnumerateRequest{
				OrgId: BackupOrgID,
			}
			backupList, err := Inst().Backup.EnumerateBackup(adminCtx, backupEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")
			noOfBackups := GetNumberOfScheduleBackupsFromListOfAllBackups(scheduleName, backupList)
			dash.VerifyFatal(noOfBackups, 2, fmt.Sprintf("Number of backups retained should be 2 for schedule policy %s and schedule name %s", primarySchedulePolicyName, scheduleName))
		})

		// 7. Update Backup Schedule and change retain count to 1
		Step("Update Backup Schedule and change retain count to 1", func() {
			log.InfoD("Update Backup Schedule and change retain count to 1")
			scheduleUID, err := GetScheduleUID(scheduleName, BackupOrgID, adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Gotten schedule UID- %v for schedule Name-%v", scheduleUID, scheduleName))
			log.InfoD("Schedule Name is - %v", scheduleName)
			err = UpdateBackupSchedulePolicy(scheduleName, scheduleUID, secondarySchedulePolicyName, secondarySchedulePolicyUID, adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Updating backup schedule [%s]", scheduleName))
			time.Sleep(backupWaitTime)

		})

		//8. Enumerate Backups and check the number of backups retained
		Step("Enumerate Backups and check the number of backups retained", func() {
			log.InfoD("Enumerate Backups and check the number of backups retained")
			backupEnumerateRequest := &api.BackupEnumerateRequest{
				OrgId: BackupOrgID,
			}
			backupList, err := Inst().Backup.EnumerateBackup(adminCtx, backupEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")
			noOfBackups := GetNumberOfScheduleBackupsFromListOfAllBackups(scheduleName, backupList)
			dash.VerifyFatal(noOfBackups, 1, fmt.Sprintf("Number of backups retained should be 1 for schedule policy %s and schedule name %s", secondarySchedulePolicyName, scheduleName))
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		//unset env for backup type
		defer func() {
			log.Infof("Unsetting BACKUP_TYPE env variable")
			err := os.Unsetenv("BACKUP_TYPE")
			log.FailOnError(err, "Unsetting BACKUP_TYPE env variable")
		}()

		//Set env back to original value
		err := os.Setenv("BACKUP_TYPE", backupTypeEnvVar)
		log.FailOnError(err, "Setting BACKUP_TYPE env variable")

		//Delete Schedules and Backups
		for _, scheduleName := range scheduleNames {
			err := DeleteSchedule(scheduleName, SourceClusterName, BackupOrgID, adminCtx, true)
			dash.VerifySafely(err, nil, fmt.Sprintf("Verification of deleting backup schedule - %s", scheduleName))
		}
		// Delete the schedule policies
		for schedulePolicyUID, schedulePolicyName := range schedulePolicyMap {
			log.InfoD("Deleting schedule policy [%s]", schedulePolicyName)
			schedulePolicyDeleteRequest := &api.SchedulePolicyDeleteRequest{
				Name:  schedulePolicyName,
				Uid:   schedulePolicyUID,
				OrgId: BackupOrgID,
			}
			_, err := Inst().Backup.DeleteSchedulePolicy(adminCtx, schedulePolicyDeleteRequest)
			log.FailOnError(err, "failed to delete schedule policy [%s]", schedulePolicyName)
		}

		//Delete apps
		log.InfoD("Deleting the deployed apps after the testcase")
		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		DestroyApps(scheduledAppContexts, opts)
		err = DeleteNamespaces(bkpNamespaces)
		log.FailOnError(err, "failed to delete namespaces")

		//CleanupCloudSettingsAndClusters
		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, adminCtx)

	})
})

// This test case verifies that the specified number of backups are retained according to the retention count set in the backup schedule policy
var _ = Describe("{BackupRetentionCountVerification}", Label(TestCaseLabelsMap[PxBackupLabel]...), func() {

	var (
		providers              []string
		scheduledAppContexts   []*scheduler.Context
		clusterStatus          api.ClusterInfo_StatusInfo_Status
		adminContext           context.Context
		backupLocationMap      map[string]string
		bkpNamespaces          []string
		bkpLocationName        string
		backupLocationUID      string
		cloudCredName          string
		cloudCredUID           string
		sourceClusterUID       string
		schedulePolicyName     string
		schedulePolicyUid      string
		scheduleName           string
		schedulePolicyInterval int64
		retentionCount         int64
		backupWaitTime         time.Duration
		err                    error
	)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("BackupRetentionCountVerification",
			"Verifies that only the specified number of backups are retained according to the retain parameter", nil, 300831, Nvettaiyan, Q1FY25)

		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)
		schedulePolicyInterval = 15
		retentionCount = 2
		backupWaitTime = time.Duration(time.Minute) * 40

		providers = GetBackupProviders()
		backupLocationMap = make(map[string]string)
		adminContext, err = backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")

		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
	})

	It("Validates that the backup retention follows the specified count in the retain parameter", func() {

		Step("Validate applications", func() {
			log.InfoD("Validating applications")
			ValidateApplications(scheduledAppContexts)
		})

		Step("Creating backup location and cloud setting", func() {
			log.InfoD("Creating backup location and cloud setting")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cloudcred", provider, RandomString(5))
				bkpLocationName = fmt.Sprintf("%s-%s-%v-bl", provider, getGlobalBucketName(provider), RandomString(5))
				cloudCredUID = uuid.New()
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err = CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, adminContext)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				err = CreateBackupLocation(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		Step("Register cluster for backup", func() {
			log.InfoD("Register cluster for backup")
			err = CreateApplicationClusters(BackupOrgID, "", "", adminContext)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, adminContext)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			sourceClusterUID, err = Inst().Backup.GetClusterUID(adminContext, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
			log.InfoD("Uid of [%s] cluster is %s", SourceClusterName, sourceClusterUID)
		})

		Step("Create schedule policy with retention count", func() {
			log.InfoD("Create schedule policy with retention count")
			schedulePolicyName = fmt.Sprintf("%s-%v", "retention-schedule-policy", RandomString(5))
			schedulePolicyUid = uuid.New()
			err = CreateBackupScheduleIntervalPolicy(retentionCount, schedulePolicyInterval, 0, schedulePolicyName, schedulePolicyUid, BackupOrgID, adminContext, false, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creating schedule policy %s with retention count %d", schedulePolicyName, retentionCount))
		})

		Step("Create backup schedule and verify initial backup", func() {
			log.InfoD("Create backup schedule and verify initial backup")
			scheduleName = fmt.Sprintf("retention-schedule-%v", RandomString(5))
			scheduleBackupName, err := CreateScheduleBackupWithValidation(
				adminContext, scheduleName, SourceClusterName, sourceClusterUID,
				bkpLocationName, backupLocationUID, scheduledAppContexts,
				make(map[string]string), BackupOrgID, "", "", "", "",
				schedulePolicyName, schedulePolicyUid, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creating scheduled backup with name [%s]", scheduleName))
			err = IsFullBackup(scheduleBackupName, BackupOrgID, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying initial backup [%s] is full backup", scheduleBackupName))
			time.Sleep(backupWaitTime)
		})

		Step("Enumerate Backups and check the number of backups retained", func() {
			log.InfoD("Enumerate Backups and check the number of backups retained")
			backupEnumerateRequest := &api.BackupEnumerateRequest{
				OrgId: BackupOrgID,
			}
			backupList, err := Inst().Backup.EnumerateBackup(adminContext, backupEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups: %v", err)
			log.InfoD("Enumerating backups:")
			for _, backup := range backupList.GetBackups() {
				log.InfoD("Backup Name: %s, UID: %s, Status: %s",
					backup.GetName(), backup.GetUid(), backup.GetStatus())
			}
			noOfBackups := GetNumberOfScheduleBackupsFromListOfAllBackups(scheduleName, backupList)
			dash.VerifyFatal(noOfBackups, int(retentionCount), fmt.Sprintf("Successfully verified that the number of backups retained for schedule '%s' is exactly %d.", scheduleName, retentionCount))
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		//Delete Schedules and Backups
		err = DeleteSchedule(scheduleName, SourceClusterName, BackupOrgID, adminContext, true)
		dash.VerifySafely(err, nil, fmt.Sprintf("Verification of deleting backup schedule - %s", scheduleName))

		//Delete schedule policy
		log.InfoD("Deleting schedule policy [%s]", schedulePolicyName)
		schedulePolicyDeleteRequest := &api.SchedulePolicyDeleteRequest{
			Name:  schedulePolicyName,
			Uid:   schedulePolicyUid,
			OrgId: BackupOrgID,
		}
		_, err = Inst().Backup.DeleteSchedulePolicy(adminContext, schedulePolicyDeleteRequest)
		dash.VerifySafely(err, nil, fmt.Sprintf("Successfully deleted schedule policy [%s]", schedulePolicyName))

		//Delete apps
		log.InfoD("Deleting the deployed apps after the testcase")
		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		DestroyApps(scheduledAppContexts, opts)
		err = DeleteNamespaces(bkpNamespaces)
		dash.VerifySafely(err, nil, "Successfully deleted namespaces")
		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, adminContext)
	})
})
