package tests

import (
	"fmt"
	"time"

	. "github.com/onsi/ginkgo/v2"
	"github.com/pborman/uuid"
	api "github.com/portworx/px-backup-api/pkg/apis/v1"
	"github.com/pure-px/torpedo/drivers/backup"
	"github.com/pure-px/torpedo/drivers/scheduler"
	"github.com/pure-px/torpedo/pkg/log"
	. "github.com/pure-px/torpedo/tests"
)

// Verify PxBackupClusterCount from metris
var _ = Describe("{PxBackupTotalSize}", Label(TestCaseLabelsMap[ValidateMetrics]...), func() {
	var (
		contexts             []*scheduler.Context
		pxbNamespace         string
		scheduledAppContexts []*scheduler.Context
		cloudCredName        string
		cloudCredUID         string
		backupLocationUID    string
		providers            []string
		backupLocation       string
		allMetricsData       []string
		totalBackupSize      uint64
	)

	backupLocationMap := make(map[string]string)
	labelSelectors := make(map[string]string)
	bkpNamespaces := make([]string, 0)
	backupNames := make([]string, 0)
	clusterMap := make(map[string]string)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyPxBackupTotalSize", "Verify px-backup total size from metrics.", nil, 91962, Pingle, Q2FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
	})

	// Validate px-backup total size from metrics
	It("Validate px-backup total size from metrics", func() {
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin ctx")
		numOfBackup := 1
		clusterCount := 2
		//1. Create cloud credentials.
		Step("Creating cloud credentials", func() {
			log.InfoD("Creating cloud credentials")
			providers := GetBackupProviders()
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
				cloudCredUID = uuid.New()
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
			}
		})

		//2. Create backup location
		Step("Creating backup location", func() {
			log.InfoD("Creating backup location")
			providers = GetBackupProviders()
			for _, provider := range providers {
				backupLocation = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = backupLocation
				err := CreateBackupLocation(provider, backupLocation, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", backupLocation))
			}
		})

		//3 . Create multiple clusters
		Step("Register cluster for backup", func() {
			clusterSuffix := RandomString(5)
			clusterMap, err = CreateDuplicateApplicationClusters(BackupOrgID, ctx, SourceClusterName, clusterCount, clusterSuffix)
			dash.VerifyFatal(err, nil, "Creating multiple clusters")
		})

		//4. Take the backup of bkNamespaces.
		Step("Taking backup of applications", func() {
			for clusterName, clusterUid := range clusterMap {
				log.InfoD("taking backup of app")
				for i := 0; i < numOfBackup; i++ {
					backupName := fmt.Sprintf("%s-%s-%v", BackupNamePrefix, bkpNamespaces[0], time.Now().Unix())
					appContextsToBackup := FilterAppContextsByNamespace(scheduledAppContexts, bkpNamespaces)
					err = CreateBackupWithValidation(ctx, backupName, clusterName, backupLocation, backupLocationUID, appContextsToBackup, labelSelectors, BackupOrgID, clusterUid, "", "", "", "")
					dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of backup [%s]", backupName))
					backupNames = append(backupNames, backupName)
				}
			}
		})

		//5. Fetch namespace of px-backup
		Step("Get namespace of px-backup deployment", func() {
			//Get namespace of px-backup deployment
			pxbNamespace, err = backup.GetPxBackupNamespace()
			log.FailOnError(err, "Getting px-backup namespace")
			log.Infof("namespace is [%v]", pxbNamespace)
		})

		//6. Fetch all metrics datas from endpoint
		Step("Fetch all metrics data from endpoint", func() {
			//Fetch all datas from endpoint
			allMetricsData, err = RunCurlCmd(pxbNamespace)
			log.Infof("All Data recieved:[%v]", allMetricsData)
			log.FailOnError(err, "Fetching metrics data")
		})

		//7. Fetch actual volumes backup size from cluster
		Step("Get total Actual backup size volumes from cluster", func() {
			enumerateBatchSize := 100
			bkpEnumerateReq := &api.BackupEnumerateRequest{OrgId: BackupOrgID}
			bkpEnumerateReq.EnumerateOptions = &api.EnumerateOptions{MaxObjects: uint64(enumerateBatchSize), ObjectIndex: 0}

			enumerateRsp, err := Inst().Backup.EnumerateBackup(ctx, bkpEnumerateReq)
			dash.VerifyFatal(err, nil, "Backup enumeration for the ctx")

			for i, bk := range enumerateRsp.GetBackups() {
				for _, volume := range bk.GetVolumes() {
					totalBackupSize = totalBackupSize + volume.ActualSize
					log.InfoD("Verify backup size [%v] [%d]", i, totalBackupSize)
				}
			}
			log.InfoD("total backup size from cluster: [%v]", totalBackupSize)
		})

		//8. Check and validate the pxbackup_backup_size_bytes with actual cluster size
		Step("Verify the pxbackup cluster count from metrics endpoint", func() {
			metricsName := "pxbackup_backup_size_bytes"
			actual := totalBackupSize
			log.InfoD("started backup count ")
			var expected uint64
			for i := 0; i < numOfBackup*clusterCount; i++ {
				totalBKSizeFromMetrics := GetMetricValue(allMetricsData, metricsName, backupNames[i])
				currentMetricsBkSize, err := ConvertSciNotationFloat64ToUint64(totalBKSizeFromMetrics)
				log.FailOnError(err, "Error while converting value to uint64")
				expected = expected + currentMetricsBkSize
			}

			log.InfoD("total backup size from multiple cluster metrics: [%v]", expected)
			dash.VerifyFatal(actual, expected, "Verify the cluster backup size with metrics size from metrics endpoint")
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(contexts)
		// Clean up the cluster
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		CleanupCloudSettingsAndClusters(nil, "", "", ctx)

	})
})
