package tests

import (
	"fmt"
	"time"

	. "github.com/onsi/ginkgo/v2"
	"github.com/pborman/uuid"
	api "github.com/portworx/px-backup-api/pkg/apis/v1"
	"github.com/pure-px/torpedo/drivers/backup"
	"github.com/pure-px/torpedo/drivers/scheduler"
	"github.com/pure-px/torpedo/pkg/log"
	. "github.com/pure-px/torpedo/tests"
)

// Verify PxBackupClusterCount from metris
var _ = Describe("{PxBackupTotalSize}", Label(TestCaseLabelsMap[ValidateMetrics]...), func() {
	var (
		contexts             []*scheduler.Context
		pxbNamespace         string
		scheduledAppContexts []*scheduler.Context
		cloudCredName        string
		cloudCredUID         string
		backupLocationUID    string
		providers            []string
		backupLocation       string
		allMetricsData       []string
		totalBackupSize      uint64
	)

	backupLocationMap := make(map[string]string)
	labelSelectors := make(map[string]string)
	bkpNamespaces := make([]string, 0)
	backupNames := make([]string, 0)
	clusterMap := make(map[string]string)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyPxBackupTotalSize", "Verify px-backup total size from metrics.", nil, 91962, Pingle, Q2FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
	})

	// Validate px-backup total size from metrics
	It("Validate px-backup total size from metrics", func() {
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin ctx")
		numOfBackup := 1
		clusterCount := 2
		//1. Create cloud credentials.
		Step("Creating cloud credentials", func() {
			log.InfoD("Creating cloud credentials")
			providers := GetBackupProviders()
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
				cloudCredUID = uuid.New()
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
			}
		})

		//2. Create backup location
		Step("Creating backup location", func() {
			log.InfoD("Creating backup location")
			providers = GetBackupProviders()
			for _, provider := range providers {
				backupLocation = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = backupLocation
				err := CreateBackupLocation(provider, backupLocation, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", backupLocation))
			}
		})

		//3 . Create multiple clusters
		Step("Register cluster for backup", func() {
			clusterSuffix := RandomString(5)
			clusterMap, err = CreateDuplicateApplicationClusters(BackupOrgID, ctx, SourceClusterName, clusterCount, clusterSuffix)
			dash.VerifyFatal(err, nil, "Creating multiple clusters")
		})

		//4. Take the backup of bkNamespaces.
		Step("Taking backup of applications", func() {
			for clusterName, clusterUid := range clusterMap {
				log.InfoD("taking backup of app")
				for i := 0; i < numOfBackup; i++ {
					backupName := fmt.Sprintf("%s-%s-%v", BackupNamePrefix, bkpNamespaces[0], time.Now().Unix())
					appContextsToBackup := FilterAppContextsByNamespace(scheduledAppContexts, bkpNamespaces)
					err = CreateBackupWithValidation(ctx, backupName, clusterName, backupLocation, backupLocationUID, appContextsToBackup, labelSelectors, BackupOrgID, clusterUid, "", "", "", "")
					dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of backup [%s]", backupName))
					backupNames = append(backupNames, backupName)
				}
			}
		})

		//5. Fetch namespace of px-backup
		Step("Get namespace of px-backup deployment", func() {
			//Get namespace of px-backup deployment
			pxbNamespace, err = backup.GetPxBackupNamespace()
			log.FailOnError(err, "Getting px-backup namespace")
			log.Infof("namespace is [%v]", pxbNamespace)
		})

		//6. Fetch all metrics datas from endpoint
		Step("Fetch all metrics data from endpoint", func() {
			//Fetch all datas from endpoint
			allMetricsData, err = RunCurlCmd(pxbNamespace)
			log.Infof("All Data recieved:[%v]", allMetricsData)
			log.FailOnError(err, "Fetching metrics data")
		})

		//7. Fetch actual volumes backup size from cluster
		Step("Get total Actual backup size volumes from cluster", func() {
			enumerateBatchSize := 100
			bkpEnumerateReq := &api.BackupEnumerateRequest{OrgId: BackupOrgID}
			bkpEnumerateReq.EnumerateOptions = &api.EnumerateOptions{MaxObjects: uint64(enumerateBatchSize), ObjectIndex: 0}

			enumerateRsp, err := Inst().Backup.EnumerateBackup(ctx, bkpEnumerateReq)
			dash.VerifyFatal(err, nil, "Backup enumeration for the ctx")

			for i, bk := range enumerateRsp.GetBackups() {
				for _, volume := range bk.GetVolumes() {
					totalBackupSize = totalBackupSize + volume.ActualSize
					log.InfoD("Verify backup size [%v] [%d]", i, totalBackupSize)
				}
			}
			log.InfoD("total backup size from cluster: [%v]", totalBackupSize)
		})

		//8. Check and validate the pxbackup_backup_size_bytes with actual cluster size
		Step("Verify the pxbackup cluster count from metrics endpoint", func() {
			metricsName := "pxbackup_backup_size_bytes"
			actual := totalBackupSize
			log.InfoD("started backup count ")
			var expected uint64
			for i := 0; i < numOfBackup*clusterCount; i++ {
				totalBKSizeFromMetrics := GetMetricValue(allMetricsData, metricsName, backupNames[i])
				currentMetricsBkSize, err := ConvertSciNotationFloat64ToUint64(totalBKSizeFromMetrics)
				log.FailOnError(err, "Error while converting value to uint64")
				expected = expected + currentMetricsBkSize
			}

			log.InfoD("total backup size from multiple cluster metrics: [%v]", expected)
			dash.VerifyFatal(actual, expected, "Verify the cluster backup size with metrics size from metrics endpoint")
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(contexts)
		// Clean up the cluster
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		CleanupCloudSettingsAndClusters(nil, "", "", ctx)

	})
})

// Verify PxRestoreStatus from metris and validate for success.
var _ = Describe("{PxRestoreStatus}", Label(TestCaseLabelsMap[ValidateMetrics]...), func() {
	var (
		scheduledAppContexts []*scheduler.Context
		appContextsToBackup  []*scheduler.Context
		bkpNamespaces        []string
		clusterUid           string
		destClusterUid       string
		clusterStatus        api.ClusterInfo_StatusInfo_Status
		backupLocationUID    string
		cloudCredName        string
		cloudCredUID         string
		bkpLocationName      string
		backupNames          []string
		restoreName          string
		restoreNames         []string
	)

	backupLocationMap := make(map[string]string)
	bkpNamespaces = make([]string, 0)
	backupNames = make([]string, 0)
	labelSelectors := make(map[string]string)
	metricsName := "pxbackup_restore_status"
	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyPxRestoreStatus", "Verify px-backup-restore status from metrics.", nil, 91966, Pingle, Q2FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
	})

	//Verify px backup-restore success/fail status from metris and validate.
	It("Verify px backup-restore success/fail status from metris and validate", func() {
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin ctx")
		numOfBackup := 1

		// 1. validate application
		Step("Validate applications", func() {
			log.InfoD("Validating applications")
			ValidateApplications(scheduledAppContexts)
		})

		// 2. Create backup location and cloud setting
		Step("Creating backup location and cloud setting", func() {
			log.InfoD("Creating backup location and cloud setting")
			providers := GetBackupProviders()
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cloudcred", provider, time.Now().Unix())
				bkpLocationName = fmt.Sprintf("%s-%s-%v-bl", provider, getGlobalBucketName(provider), time.Now().Unix())
				cloudCredUID = uuid.New()
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				err = CreateBackupLocation(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		// 3. Create application cluster for backup.
		Step("Register cluster for backup", func() {
			err = CreateApplicationClusters(BackupOrgID, "", "", ctx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, ctx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = Inst().Backup.GetClusterUID(ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
			log.InfoD("Uid of [%s] cluster is %s", SourceClusterName, clusterUid)
			destClusterUid, err = Inst().Backup.GetClusterUID(ctx, BackupOrgID, DestinationClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] dest cluster uid", SourceClusterName))
		})

		// 4. take backup
		Step("Taking backup of applications", func() {
			for i := 0; i < numOfBackup; i++ {
				backupName := fmt.Sprintf("%s-%s-%v", BackupNamePrefix, bkpNamespaces[0], time.Now().Unix())
				appContextsToBackup = FilterAppContextsByNamespace(scheduledAppContexts, bkpNamespaces)
				err = CreateBackupWithValidation(ctx, backupName, SourceClusterName, bkpLocationName, backupLocationUID, appContextsToBackup, labelSelectors, BackupOrgID, clusterUid, "", "", "", "")
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of backup [%s]", backupName))
				backupNames = append(backupNames, backupName)
			}
		})

		//5. Create restore of backup
		Step("Create restore", func() {
			log.Infof("Restore for success case started")
			backupName := backupNames[0]
			restoreName = fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			appContextsToBackup = FilterAppContextsByNamespace(scheduledAppContexts, bkpNamespaces)
			err = CreateRestoreWithValidation(ctx, restoreName, backupName, make(map[string]string), make(map[string]string), DestinationClusterName, destClusterUid, BackupOrgID, appContextsToBackup)
			log.FailOnError(err, "Restoring of backup [%s] has failed with name - [%s]", backupName, restoreName)
			restoreNames = append(restoreNames, restoreName)
		})

		// 6. Verify the success status of the restore from metrics endpoint
		Step("Verify the success status of the backup-restore from metrics endpoint", func() {
			pxbNamespace, err := backup.GetPxBackupNamespace()
			dash.VerifyFatal(err, nil, "Getting px-backup namespace")

			allMetricsData, err := RunCurlCmd(pxbNamespace)
			log.FailOnError(err, "Fetching metrics data")

			expected := "6"
			status := GetMetricValue(allMetricsData, metricsName, restoreName)
			log.Infof("pxbackup_restore_status recived:", status)
			dash.VerifyFatal(status, expected, "Verify the success status of the pxbackup_backup_restore_status from metrics endpoint")
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		log.InfoD("Deleting the deployed apps after the testcase")
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")

		err = DeleteRestore(restoreNames[0], BackupOrgID, ctx)
		dash.VerifySafely(err, nil, fmt.Sprintf("Deleting restore[0] %s", restoreName))

		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		DestroyApps(scheduledAppContexts, opts)

		// Clean up the cluster
		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)

	})
})

// Verify VerifyPxBackupStatus from metris and validate for success.
var _ = Describe("{PxBackupStatus}", Label(TestCaseLabelsMap[ValidateMetrics]...), func() {
	var (
		scheduledAppContexts []*scheduler.Context
		appContextsToBackup  []*scheduler.Context
		bkpNamespaces        []string
		clusterUid           string
		clusterStatus        api.ClusterInfo_StatusInfo_Status
		namespace            string
		backupLocationUID    string
		cloudCredName        string
		cloudCredUID         string
		bkpLocationName      string
		backupNames          []string
	)

	backupLocationMap := make(map[string]string)
	bkpNamespaces = make([]string, 0)
	backupNames = make([]string, 0)
	labelSelectors := make(map[string]string)
	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyPxBackupStatus", "Verify px-backup status from metrics.", nil, 91965, Pingle, Q2FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace = GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
	})

	//Verify px backup success status from metris and validate.
	It("Verify px backup success/fail status from metris and validate", func() {
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin ctx")
		numOfBackup := 1

		// 1. validate application
		Step("Validate applications", func() {
			log.InfoD("Validating applications")
			ValidateApplications(scheduledAppContexts)
		})

		// 2. Create backup location and cloud setting
		Step("Creating backup location and cloud setting", func() {
			log.InfoD("Creating backup location and cloud setting")
			providers := GetBackupProviders()
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cloudcred", provider, time.Now().Unix())
				bkpLocationName = fmt.Sprintf("%s-%s-%v-bl", provider, getGlobalBucketName(provider), time.Now().Unix())
				cloudCredUID = uuid.New()
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				err = CreateBackupLocation(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		// 3. Create application cluster for backup.
		Step("Register cluster for backup", func() {
			err = CreateApplicationClusters(BackupOrgID, "", "", ctx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, ctx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = Inst().Backup.GetClusterUID(ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
			log.InfoD("Uid of [%s] cluster is %s", SourceClusterName, clusterUid)
		})
		// 4. take backup
		Step("Taking backup of applications", func() {
			for i := 0; i < numOfBackup; i++ {
				backupName := fmt.Sprintf("%s-%s-%v", BackupNamePrefix, bkpNamespaces[0], time.Now().Unix())
				appContextsToBackup = FilterAppContextsByNamespace(scheduledAppContexts, bkpNamespaces)
				err = CreateBackupWithValidation(ctx, backupName, SourceClusterName, bkpLocationName, backupLocationUID, appContextsToBackup, labelSelectors, BackupOrgID, clusterUid, "", "", "", "")
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of backup [%s]", backupName))
				backupNames = append(backupNames, backupName)
			}
		})

		// 5. Verify the success status of the backup from metrics endpoint
		Step("Verify the status of the backup from metrics endpoint", func() {
			pxbNamespace, err := backup.GetPxBackupNamespace()
			dash.VerifyFatal(err, nil, "Getting px-backup namespace")

			allMetricsData, err := RunCurlCmd(pxbNamespace)
			log.FailOnError(err, "Fetching metrics data")

			expected := "6"
			status := GetMetricValue(allMetricsData, PxBackupMetricsName, backupNames[0])
			log.Infof("pxbackup_backup_count status recived:", status)
			dash.VerifyFatal(status, expected, "Verify the status of the pxbackup_backup_count from metrics endpoint")
		})

	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		log.InfoD("Deleting the deployed apps after the testcase")
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin user ctx")

		// Delete the backups
		for _, backup := range backupNames {
			backupUid, err := Inst().Backup.GetBackupUID(ctx, backup, BackupOrgID)
			log.FailOnError(err, "Unable to fetch backup UID")
			err = DeleteBackupAndWaitForCompletion(backup, backupUid, BackupOrgID, ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backup))
		}

		err = DeleteNamespaces(bkpNamespaces)
		log.FailOnError(err, "failed to delete namespaces")

		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true

		DestroyApps(scheduledAppContexts, opts)

		// Clean up the cluster
		log.FailOnError(err, "Fetching px-central-admin ctx")
		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)

	})
})

// Verify PxBackupClusterCount from metrics
var _ = Describe("{VerifyPxBackupClusterCount}", Label(TestCaseLabelsMap[ValidateMetrics]...), func() {
	var (
		contexts     []*scheduler.Context
		pxbNamespace string
		clusterCount int
	)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyPxBackupClusterCount", "Verify px-backup cluster count from metrics.", nil, 91949, Prikumar, Q2FY25)
	})

	// Validate px-backup cluster count from metrics
	It("Validate px-backup cluster count from metrics", func() {
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin ctx")

		// Creating multiple clusters for backup
		Step("Register cluster for backup", func() {
			clusterCount = 4
			clusterSuffix := fmt.Sprintf("%s-%s", "cluster", RandomString(5))
			_, err = CreateDuplicateApplicationClusters(BackupOrgID, ctx, SourceClusterName, clusterCount, clusterSuffix)
			dash.VerifyFatal(err, nil, "Creating duplicate cluster object")

		})

		// Check and validate the PxBackup_cluster_status count
		Step("Verify the pxbackup cluster count from metrics endpoint", func() {
			metricsName := "pxbackup_cluster_status"

			// Get namespace of px-backup deployment
			pxbNamespace, err = backup.GetPxBackupNamespace()
			log.FailOnError(err, "Getting px-backup namespace")
			log.Infof("namespace is [%v]", pxbNamespace)

			// Fetch all datas from endpoint
			allMetricsData, err := RunCurlCmd(pxbNamespace)
			log.FailOnError(err, "Fetching metrics data")

			// Get total px-backup cluster count
			count, err := GetPxBackupClusterCount(allMetricsData, metricsName)
			log.Infof("pxbackup_cluster_count", count)
			dash.VerifyFatal(clusterCount, count, "Validate cluster count")
			dash.VerifyFatal(err, nil, "Verify the status of the pxbackup_cluster_status count from metrics endpoint")
		})

	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(contexts)
		// Clean up the cluster
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		CleanupCloudSettingsAndClusters(nil, "", "", ctx)

	})
})

// Verify PxBackup cloud credentials count from metrics
var _ = Describe("{VerifyPxBackupCloudCredCount}", func() {
	var (
		contexts      []*scheduler.Context
		cloudCredName string
		cloudCredUID  string
		pxbNamespace  string
		credCount     int
	)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyPxBackupCloudCredCount", "Verify px-backup cloud credentials count from metrics.", nil, 91950, Prikumar, Q2FY25)
	})

	// Validate px-backup cloud credentials count from metrics
	It("Validate px-backup cloud credentials count from metrics", func() {
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin ctx")

		// Creating cloud credentials
		Step("Creating cloud credentials", func() {
			log.InfoD("Creating cloud credentials")
			credCount = 4
			providers := GetBackupProviders()
			for _, provider := range providers {
				for i := 0; i < credCount; i++ {
					cloudCredName = fmt.Sprintf("%s-%s-%v", "cloudcred", provider, i)
					cloudCredUID = uuid.New()
					err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
					dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				}
			}
		})

		// Check and validate the PxBackup_cloudcred_metrics count
		Step("Verify the pxbackup cloud credential count from metrics endpoint", func() {
			metricsName := "pxbackup_cloudcred_metrics"

			// Get namespace of px-backup deployment
			pxbNamespace, err = backup.GetPxBackupNamespace()
			log.FailOnError(err, "Getting px-backup namespace")
			log.Infof("namespace is [%v]", pxbNamespace)

			// Fetch all datas from endpoint
			allMetricsData, err := RunCurlCmd(pxbNamespace)
			log.FailOnError(err, "Fetching metrics data")

			// Get total px-backup cluster count
			count, err := GetPxBackupCloudCredCount(allMetricsData, metricsName)
			log.Infof("pxbackup_cloudcred_metrics count", count)
			dash.VerifyFatal(credCount, count, "Validate cloud credential count")
			dash.VerifyFatal(err, nil, "Verify the status of the pxbackup_cloudcred_metrics count from metrics endpoint")
		})

	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(contexts)
		// Clean up the cluster
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		CleanupCloudSettingsAndClusters(nil, cloudCredName, cloudCredUID, ctx)

	})
})

// Verify Backup location count from metrics
var _ = Describe("{VerifyBackupLocationCount}", Label(TestCaseLabelsMap[ValidateMetrics]...), func() {
	var (
		contexts          []*scheduler.Context
		cloudCredName     string
		cloudCredUID      string
		bkpLocationName   string
		backupLocationUID string
		bkpLocationCount  int
	)

	backupLocationMap := make(map[string]string)
	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyBackupLocationCount", "Verify backup location count from metrics.", nil, 91952, Prikumar, Q2FY25)
	})

	// Validate backup location count from metrics
	It("Validate backup location count from metrics", func() {
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin ctx")

		// Creating backup location
		Step("Creating backup location", func() {
			log.InfoD("Creating backup location")
			bkpLocationCount = 3
			providers := GetBackupProviders()
			for _, provider := range providers {
				for i := 0; i < bkpLocationCount; i++ {
					cloudCredName = fmt.Sprintf("%s-%s-%v", "cloudcred", provider, time.Now().Unix())
					cloudCredUID = uuid.New()
					bkpLocationName = fmt.Sprintf("%s-%s-%v-bl", provider, getGlobalBucketName(provider), i)
					backupLocationUID = uuid.New()
					backupLocationMap[backupLocationUID] = bkpLocationName
					err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
					dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
					err = CreateBackupLocation(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
					dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
				}
			}
		})

		// Check and validate the backup location status count
		Step("Verify the backup location count from metrics endpoint", func() {
			metricsName := "pxbackup_backup_location_status"

			// Get namespace of px-backup deployment
			pxbNamespace, err := backup.GetPxBackupNamespace()
			log.FailOnError(err, "Getting px-backup namespace")
			log.Infof("namespace is [%v]", pxbNamespace)

			// Fetch all datas from endpoint
			allMetricsData, err := RunCurlCmd(pxbNamespace)
			log.FailOnError(err, "Fetching metrics data")

			// Get total px-backup location count
			count, err := GetBackupLocationCount(allMetricsData, metricsName)
			log.Infof("pxbackup_backup_location_status count", count)
			dash.VerifyFatal(bkpLocationCount, count, "Validate backup location count")
			dash.VerifyFatal(err, nil, "Verify the status of the  pxbackup_backup_location_status count from metrics endpoint")
		})

	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(contexts)

		// Clean up the cluster
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)

	})
})

// Verify VerifyPxBackupTotalDuration from metrics
var _ = Describe("{PxBackupTotalDuration}", Label(TestCaseLabelsMap[ValidateMetrics]...), func() {
	var (
		contexts             []*scheduler.Context
		pxbNamespace         string
		scheduledAppContexts []*scheduler.Context
		cloudCredName        string
		cloudCredUID         string
		backupLocationUID    string
		providers            []string
		backupLocation       string
		allMetricsData       []string
		totalBackupDuration  int64
	)

	backupLocationMap := make(map[string]string)
	labelSelectors := make(map[string]string)
	bkpNamespaces := make([]string, 0)
	backupNames := make([]string, 0)
	clusterMap := make(map[string]string)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyPxBackupTotalDuration", "Verify px-backup total duration from metrics.", nil, 91958, Pingle, Q2FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
	})

	//1. Validate px-backup total duration from metrics
	It("Validate px-backup total size from metrics", func() {
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin ctx")
		numOfBackup := 1
		clusterCount := 2
		//1. Create cloud credentials.
		Step("Creating cloud credentials", func() {
			log.InfoD("Creating cloud credentials")
			providers := GetBackupProviders()
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
				cloudCredUID = uuid.New()
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
			}
		})

		//2. Create backup location
		Step("Creating backup location", func() {
			log.InfoD("Creating backup location")
			providers = GetBackupProviders()
			for _, provider := range providers {
				backupLocation = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = backupLocation
				err := CreateBackupLocation(provider, backupLocation, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", backupLocation))
			}
		})

		//3 . Create multiple clusters
		Step("Register cluster for backup", func() {
			clusterSuffix := RandomString(5)
			clusterMap, err = CreateDuplicateApplicationClusters(BackupOrgID, ctx, SourceClusterName, clusterCount, clusterSuffix)
			dash.VerifyFatal(err, nil, "Creating multiple clusters")
		})

		//4. Take the backup of bkNamespaces.
		Step("Taking backup of applications", func() {
			for clusterName, clusterUid := range clusterMap {
				log.InfoD("taking backup of app")
				for i := 0; i < numOfBackup; i++ {
					backupName := fmt.Sprintf("%s-%s-%v", BackupNamePrefix, bkpNamespaces[0], time.Now().Unix())
					appContextsToBackup := FilterAppContextsByNamespace(scheduledAppContexts, bkpNamespaces)
					err = CreateBackupWithValidation(ctx, backupName, clusterName, backupLocation, backupLocationUID, appContextsToBackup, labelSelectors, BackupOrgID, clusterUid, "", "", "", "")
					dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of backup [%s]", backupName))
					backupNames = append(backupNames, backupName)
				}
			}
		})

		//5. Fetch namespace of px-backup
		Step("Get namespace of px-backup deployment", func() {
			pxbNamespace, err = backup.GetPxBackupNamespace()
			log.FailOnError(err, "Getting px-backup namespace")
			log.Infof("namespace is [%v]", pxbNamespace)
		})

		//6. Fetch all metrics datas from endpoint
		Step("Fetch all metrics data from endpoint", func() {
			allMetricsData, err = RunCurlCmd(pxbNamespace)
			log.FailOnError(err, "Fetching metrics data")
		})

		//7. Fetch actual backup duration from cluster
		Step("Get total actual backup duration from clusterr", func() {
			enumerateBatchSize := 100
			bkpEnumerateReq := &api.BackupEnumerateRequest{OrgId: BackupOrgID}
			bkpEnumerateReq.EnumerateOptions = &api.EnumerateOptions{MaxObjects: uint64(enumerateBatchSize), ObjectIndex: 0}

			enumerateRsp, err := Inst().Backup.EnumerateBackup(ctx, bkpEnumerateReq)
			dash.VerifyFatal(err, nil, "Backup enumeration for the ctx")

			i := 1
			for _, bk := range enumerateRsp.GetBackups() {
				diff := bk.GetLastUpdateTime().Seconds - bk.GetCreateTime().Seconds
				totalBackupDuration = totalBackupDuration + diff
				log.InfoD(" Backup duration of %d: is %d", i, diff)
				i++
			}
			log.InfoD("total backup is [%d] and total duration from cluster is: [%v]", i-1, totalBackupDuration)
		})

		//8. Check and validate the pxbackup_backup_duration_seconds with actual cluster duration
		Step("Verify the pxbackup cluster count from metrics endpoint", func() {
			metricsName := "pxbackup_backup_duration_seconds"
			actual := uint64(totalBackupDuration)
			log.InfoD("started backup count ")
			var expected uint64
			for i := 0; i < numOfBackup*clusterCount; i++ {
				totalBkDurationFromMetrics := GetMetricValue(allMetricsData, metricsName, backupNames[i])
				currentMetricsBkDuration, err := ConvertSciNotationFloat64ToUint64(totalBkDurationFromMetrics)
				log.FailOnError(err, "Error while converting value to uint64")
				expected = expected + currentMetricsBkDuration
			}

			log.InfoD("total backup duration from multiple cluster: [%v]", expected)
			dash.VerifyFatal(actual, expected, "Verify the cluster backup duration with metrics size from metrics endpoint")
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(contexts)
		// Clean up the cluster
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		// Delete all backups
		last := len(backupNames) - 1
		for i := last; i >= 0; i-- {
			backupUid, err := Inst().Backup.GetBackupUID(ctx, backupNames[i], BackupOrgID)
			log.FailOnError(err, "Unable to fetch backup UID")
			err = DeleteBackupAndWaitForCompletion(backupNames[i], backupUid, BackupOrgID, ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backupNames[i]))
		}

		err = DeleteNamespaces(bkpNamespaces)
		log.FailOnError(err, "failed to delete namespaces")

		CleanupCloudSettingsAndClusters(nil, "", "", ctx)

	})
})

// Verify PxBackup schedule policy count from metrics
var _ = Describe("{VerifyPxBackupSchedulePolicyCount}", Label(TestCaseLabelsMap[ValidateMetrics]...), func() {
	var (
		contexts            []*scheduler.Context
		pxbNamespace        string
		schedulePolicyNames []string
		schedulePolicyCount int
	)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyPxBackupSchedulePolicyCount", "Verify px-backup schedule policy count from metrics.", nil, 91951, Prikumar, Q2FY25)
	})

	// Validate px-backup schedule policy count from metrics
	It("Validate px-backup schedule policy count from metrics", func() {
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin ctx")

		// Creating multiple schedule policies for backup
		Step("Create schedule policy for backup schedules", func() {
			log.InfoD("Create schedule policy for backup schedules")
			schedulePolicyCount = 4
			for i := 0; i < schedulePolicyCount; i++ {
				periodicSchedulePolicyName := fmt.Sprintf("%s-%v", "periodic", i)
				periodicSchedulePolicyUid := uuid.New()
				periodicSchedulePolicyInterval := int64(15)
				err = CreateBackupScheduleIntervalPolicy(5, periodicSchedulePolicyInterval, 5, periodicSchedulePolicyName, periodicSchedulePolicyUid, BackupOrgID, ctx, false, false)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of periodic schedule policy of interval [%v] minutes named [%s]", periodicSchedulePolicyInterval, periodicSchedulePolicyName))
				schedulePolicyNames = append(schedulePolicyNames, periodicSchedulePolicyName)
			}
		})

		// Check and validate the PxBackup_schedulepolicy_metrics count
		Step("Verify the pxbackup schedule policy count from metrics endpoint", func() {
			metricsName := "pxbackup_schedpolicy_metrics"

			// Get namespace of px-backup deployment
			pxbNamespace, err = backup.GetPxBackupNamespace()
			log.FailOnError(err, "Getting px-backup namespace")
			log.Infof("namespace is [%v]", pxbNamespace)

			// Fetch all datas from endpoint
			allMetricsData, err := RunCurlCmd(pxbNamespace)
			log.FailOnError(err, "Fetching metrics data")

			// Get total px-backup schedule policy count
			count, err := GetPxBackupSchedulePolicyCount(allMetricsData, metricsName, BackupOrgID)
			log.Infof("pxbackup_cschedulePolicy count", count)
			dash.VerifyFatal(schedulePolicyCount, count, "Validate the count")
			dash.VerifyFatal(err, nil, "Verify the status of pxbackup schedule policy count from metrics endpoint")
		})

	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(contexts)
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin ctx")

		// Delete all schedule policies
		log.Infof("Deleting backup schedule policy")
		schedulePolicyNames, _ := Inst().Backup.GetAllSchedulePolicies(ctx, BackupOrgID)
		for _, schedulePolicyName := range schedulePolicyNames {
			err = Inst().Backup.DeleteBackupSchedulePolicy(BackupOrgID, []string{schedulePolicyName})
			dash.VerifySafely(err, nil, fmt.Sprintf("Deleting backup schedule policy %s ", []string{schedulePolicyName}))
		}
		// Clean up the cluster
		CleanupCloudSettingsAndClusters(nil, "", "", ctx)
	})
})

// Verify PxBackup Restore Duration from metrics
var _ = Describe("{VerifyTotalRestoreDuration}", Label(TestCaseLabelsMap[ValidateMetrics]...), func() {
	var (
		contexts             []*scheduler.Context
		pxbNamespace         string
		scheduledAppContexts []*scheduler.Context
		cloudCredName        string
		cloudCredUID         string
		backupLocationUID    string
		providers            []string
		backupLocation       string
		allMetricsData       []string
		totRestoreDuration   int64
	)

	backupLocationMap := make(map[string]string)
	labelSelectors := make(map[string]string)
	bkpNamespaces := make([]string, 0)
	backupNames := make([]string, 0)
	restoreNames := make([]string, 0)
	clusterMap := make(map[string]string)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyTotalRestoreDuration", "Verify total restore duration from metrics.", nil, 91960, Prikumar, Q3FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
	})

	// Validate px-backup total restore duration from metrics
	It("Validate px-backup total restore duration from metrics", func() {
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin ctx")
		numOfBackup := 1
		restoreCount := 2
		clusterCount := 2
		// Creating cloud credentials and backup location
		Step("Creating cloud credentials and backup location", func() {
			log.InfoD("Creating cloud credentials and backup location")
			providers = GetBackupProviders()
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
				cloudCredUID = uuid.New()
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				log.InfoD("Created Cloud Credentials with name - %s", cloudCredName)
				backupLocation = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = backupLocation
				err = CreateBackupLocation(provider, backupLocation, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %v", backupLocation))
				log.InfoD("Created Backup Location with name - %s", backupLocation)

			}
		})

		// Create multiple clusters
		Step("Register cluster for backup", func() {
			clusterSuffix := fmt.Sprintf("%s-%s", "cluster", RandomString(5))
			clusterMap, err = CreateDuplicateApplicationClusters(BackupOrgID, ctx, SourceClusterName, clusterCount, clusterSuffix)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creating duplicate cluster object using clusterConfigPath [%v]", clusterMap))
		})

		// Taking backup of applications
		Step("Taking backup of applications", func() {
			for clusterName, clusterUid := range clusterMap {
				log.InfoD("clusterName [%v] clusterUid [%v]", clusterName, clusterUid)
				log.InfoD("Taking backup of app")
				for i := 0; i < numOfBackup; i++ {
					backupName := fmt.Sprintf("%s-%v-%v", BackupNamePrefix, i, time.Now().Unix())
					appContextsToBackup := FilterAppContextsByNamespace(scheduledAppContexts, bkpNamespaces)
					err = CreateBackupWithValidation(ctx, backupName, clusterName, backupLocation, backupLocationUID, appContextsToBackup, labelSelectors, BackupOrgID, clusterUid, "", "", "", "")
					dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of backup [%s]", backupName))
					backupNames = append(backupNames, backupName)
				}
			}
			log.InfoD("List of backups [%v]", backupNames)
		})

		// Taking restore of backups
		Step("Taking restore of backups", func() {
			log.InfoD("Taking restore of backups")
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			for clusterName, clusterUid := range clusterMap {
				for i := 0; i < restoreCount; i++ {
					restoreName := fmt.Sprintf("%s-%s-%v", RestoreNamePrefix, backupNames[i], time.Now().Unix())
					log.Infof("Started restore [%s] for backup [%s]", restoreName, backupNames[i])
					err = CreateRestore(restoreName, backupNames[i], make(map[string]string), clusterName, clusterUid, BackupOrgID, ctx, make(map[string]string))
					dash.VerifyFatal(err, nil, fmt.Sprintf("Creating restore [%s]", restoreName))
					restoreNames = append(restoreNames, restoreName)
				}
			}
			log.Infof("List of restores [%v]", restoreNames)
		})

		// Fetch all metrics datas from endpoint
		Step("Fetch all metrics data from endpoint", func() {
			// Get namespace of px-backup deployment
			pxbNamespace, err = backup.GetPxBackupNamespace()
			log.FailOnError(err, "Getting px-backup namespace")
			log.Infof("namespace is [%v]", pxbNamespace)

			// Fetch all datas from endpoint
			allMetricsData, err = RunCurlCmd(pxbNamespace)
			log.Infof("All Data recieved:[%v]", allMetricsData)
			log.FailOnError(err, "Fetching metrics data")
		})

		// Fetch total restore duration from cluster
		Step("Get total restore duration from cluster", func() {
			restoreEnumerateRequest := &api.RestoreEnumerateRequest{
				OrgId: BackupOrgID,
			}
			restoreResponse, err := Inst().Backup.EnumerateRestore(ctx, restoreEnumerateRequest)
			dash.VerifyFatal(err, nil, "Restore enumeration for the ctx")

			for i, restoreObj := range restoreResponse.GetRestores() {
				restoreDuration := restoreObj.GetLastUpdateTime().Seconds - restoreObj.GetCreateTime().Seconds
				totRestoreDuration = totRestoreDuration + restoreDuration
				log.InfoD("verify the restore duration [%v][%d]", i, totRestoreDuration)
			}

			log.InfoD("Total restore duration from cluster [%v]", totRestoreDuration)
		})

		// Check and validate the pxbackup_restore_duration_seconds with actual restore duration from cluster
		Step("Verify the pxbackup restore duration from metrics endpoint", func() {
			metricsName := "pxbackup_restore_duration_seconds"
			actual := uint64(totRestoreDuration)
			var expected uint64
			log.InfoD("Started restore count")
			for i := 0; i < restoreCount*clusterCount; i++ {
				totRestoreDurationFromMetrics := GetMetricValue(allMetricsData, metricsName, restoreNames[i])
				currentMetricsRestoreDuration, err := ConvertSciNotationFloat64ToUint64(totRestoreDurationFromMetrics)
				log.FailOnError(err, "Error while converting value to uint64")
				expected = expected + currentMetricsRestoreDuration
			}
			log.InfoD("total restore duration from metrics: [%v]", expected)
			dash.VerifyFatal(actual, expected, "Verify the cluster restore duration with actual restore duration from metrics endpoint")
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(contexts)
		ctx, err := backup.GetAdminCtxFromSecret()
		log.Info("Delete restores")
		for _, restoreName := range restoreNames {
			err = DeleteRestore(restoreName, BackupOrgID, ctx)
			dash.VerifySafely(err, nil, fmt.Sprintf("Deleting restore [%s]", restoreName))
		}
		// Clean up the cluster
		log.FailOnError(err, "Fetching px-central-admin ctx")
		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)
	})
})
