package tests

import (
	"fmt"
	"strings"
	"time"

	. "github.com/onsi/ginkgo/v2"
	"github.com/pborman/uuid"
	api "github.com/portworx/px-backup-api/pkg/apis/v1"
	"github.com/portworx/torpedo/drivers/backup"
	"github.com/portworx/torpedo/drivers/scheduler"
	"github.com/portworx/torpedo/pkg/log"
	. "github.com/portworx/torpedo/tests"
	"golang.org/x/sync/errgroup"
)

// Test to validate the deletion of cloud credential from user ctx while backup in progress
var _ = Describe("{DeleteCloudCredentialFromUserCtx}", func() {
	var (
		backupName           string
		scheduledAppContexts []*scheduler.Context
		bkpNamespaces        []string
		clusterUid           string
		clusterStatus        api.ClusterInfo_StatusInfo_Status
		cloudCredName        string
		cloudCredUID         string
		backupLocationUID    string
		providers            []string
		backupLocationMap    map[string]string
		labelSelectors       map[string]string
		backupLocation       string
		controlChannel       chan string
		errorGroup           *errgroup.Group
		customUser           string
		customRoleName       backup.PxBackupRole = backup.InfrastructureOwner
	)
	JustBeforeEach(func() {
		bkpNamespaces = make([]string, 0)
		backupLocationMap = make(map[string]string)
		labelSelectors = make(map[string]string)
		providers = GetBackupProviders()

		StartPxBackupTorpedoTest("DeleteCloudCredentialFromUserCtx", "Delete cloud credential from user context", nil, 300502, Prikumar, Q3FY25)
		log.InfoD("Deploy applications")

		scheduledAppContexts = make([]*scheduler.Context, 0)
		for i := 0; i < Inst().GlobalScaleFactor; i++ {
			taskName := fmt.Sprintf("%s-%d", TaskNamePrefix, i)
			appContexts := ScheduleApplications(taskName)
			for _, ctx := range appContexts {
				ctx.ReadinessTimeout = AppReadinessTimeout
				namespace := GetAppNamespace(ctx, taskName)
				bkpNamespaces = append(bkpNamespaces, namespace)
				scheduledAppContexts = append(scheduledAppContexts, ctx)
			}
		}
	})
	//Share cloud credential from admin ctx to user and try to delete the credential while backup in progress
	It("Test to validate and delete cloud credential before completion of backup", func() {
		Step("Validate applications", func() {
			ctx, _ := backup.GetAdminCtxFromSecret()
			controlChannel, errorGroup = ValidateApplicationsStartData(scheduledAppContexts, ctx)
		})

		//Create cloud credential and backup location
		Step("Creating cloud credentials and backup location", func() {
			log.InfoD("Creating cloud credentials and backup location")
			providers = GetBackupProviders()
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
				cloudCredUID = uuid.New()
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				log.InfoD("Created Cloud Credentials with name - %s", cloudCredName)
				backupLocation = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = backupLocation
				err = CreateBackupLocation(provider, backupLocation, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %v", backupLocation))
				log.InfoD("Created Backup Location with name - %s", backupLocation)

			}
		})

		Step("Register cluster for backup", func() {
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			err = CreateApplicationClusters(BackupOrgID, "", "", ctx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, ctx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = Inst().Backup.GetClusterUID(ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
		})

		//Create user
		Step(fmt.Sprintf("Create a new user [%s]", customRoleName), func() {
			customUser = fmt.Sprintf("testuser-%s", RandomString(5))
			firstName := fmt.Sprintf("FirstName-%s", customUser)
			lastName := fmt.Sprintf("LastName-%s", customUser)
			email := fmt.Sprintf("%v@cnbu.com", customUser)
			err := backup.AddUser(customUser, firstName, lastName, email, CommonPassword)
			log.FailOnError(err, "Failed to create user - %s", customUser)
		})

		//Add custom role to the User
		Step(fmt.Sprintf("Add custom role [%s] to the user", customRoleName), func() {
			log.InfoD(fmt.Sprintf("Add role to the user [%s]", customRoleName))
			err := backup.AddRoleToUser(customUser, customRoleName, fmt.Sprintf("Adding %v role to %s", customRoleName, customUser))
			log.FailOnError(err, "failed to add role %s to the user %s", customRoleName, customUser)
			log.Infof("username %s common password %s", customUser, CommonPassword)
		})

		//Share cloud credential from admin ctx to user
		Step(fmt.Sprintf("share cloud credentials to the user [%s]", customUser), func() {
			log.InfoD("sharing credentials")
			adminCtx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-admin ctx")
			err = AddCloudCredentialOwnership(cloudCredName, cloudCredUID, []string{customUser}, nil, Admin, Invalid, adminCtx, BackupOrgID)
			log.FailOnError(err, "Sharing CloudCredential Object %s with testuser", cloudCredName)
		})

		Step("Taking backup of applications", func() {
			log.InfoD("Taking Backup of application")
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			backupName = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			_, err = CreateBackupWithoutCheck(ctx, backupName, SourceClusterName, backupLocation, backupLocationUID, scheduledAppContexts, labelSelectors, BackupOrgID, clusterUid, "", "", "", "")
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))
		})

		//Try to delete the cloud credential from user ctx while backup in progress
		Step("Delete cloud credential from user", func() {
			log.InfoD("Delete cloud credential from testuser")
			backupDriver := Inst().Backup
			ctx, err := backup.GetNonAdminCtx(customUser, CommonPassword)
			log.FailOnError(err, "Failed to fetch user %s ctx", customUser)
			credDeleteRequest := &api.CloudCredentialDeleteRequest{
				Name:  cloudCredName,
				OrgId: BackupOrgID,
				Uid:   cloudCredUID,
			}
			_, err = backupDriver.DeleteCloudCredential(ctx, credDeleteRequest)
			log.Infof("Not able to delete while backup in progress %s", err)
			dash.VerifyFatal(strings.Contains(err.Error(), "has reference to cloud credential"), true, fmt.Sprintf("Verifying deletion of cloud cred [%s]", cloudCredName))
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		log.InfoD("Deleting the deployed apps after the testcase")
		// Cleaning up applications created
		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		err := DestroyAppsWithData(scheduledAppContexts, opts, controlChannel, errorGroup)
		log.FailOnError(err, "Data validations failed")

		// Cleaning up px-backup cluster
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)
	})
})
