package tests

import (
	"fmt"
	"strings"
	"time"

	. "github.com/onsi/ginkgo/v2"
	"github.com/pborman/uuid"
	api "github.com/portworx/px-backup-api/pkg/apis/v1"
	"github.com/portworx/sched-ops/k8s/core"
	"github.com/pure-px/torpedo/drivers/backup"
	"github.com/pure-px/torpedo/drivers/node"
	"github.com/pure-px/torpedo/drivers/scheduler"
	"github.com/pure-px/torpedo/pkg/log"
	. "github.com/pure-px/torpedo/tests"
	corev1 "k8s.io/api/core/v1"
	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Paralle Scheduled Backup Test Suite
var _ = Describe("{ParallelBackupScheduleTestSuite}", Ordered, Label(TestCaseLabelsMap[ParallelBackupScheduleTestSuite]...), func() {
	var (
		scheduledAppContexts                   []*scheduler.Context
		providers                              []string = GetBackupProviders()
		bkpNamespaces                          []string
		schedulePolicyName, schedulePolicyUid  string
		cloudCredName, cloudCredUID            string
		backupLocationMap                      map[string]string
		sourceClusterUID                       string
		backupLocationUID                      string
		bkpLocationName                        string
		nsLabelsMap                            map[string]string
		randomStringLength                                   = 10
		parallelScheduledBackupNamespacePrefix               = "parallel-scheduled-backup"
		defaultWaitInterval                    time.Duration = 20 * time.Second
		pxNamespace                                          = "portworx"
	)
	BeforeAll(func() {
		backupLocationMap = make(map[string]string)
		// Schedule a pxd Volume Application
		scheduledAppContexts = make([]*scheduler.Context, 0)
		pipelineAppList := Inst().AppList
		Inst().AppList = []string{"busybox-pxd"}
		originalAppList := Inst().AppList
		//Resetting the pipeline app list
		defer func() {
			Inst().AppList = pipelineAppList
		}()

		namespace := fmt.Sprintf("%s-%s", parallelScheduledBackupNamespacePrefix, RandomString(10))
		log.InfoD("Creating namespace %v", namespace)
		_, err := core.Instance().CreateNamespace(&corev1.Namespace{
			ObjectMeta: metav1.ObjectMeta{
				Name: namespace,
			},
		})
		if err != nil && !k8serrors.IsAlreadyExists(err) {
			log.FailOnError(err, fmt.Sprintf("Failed to create namespace %s on source cluster", namespace))
		}

		for i := 0; i < len(originalAppList); i++ {
			taskName := fmt.Sprintf("%s-%s", TaskNamePrefix, RandomString(randomStringLength))
			appContexts := ScheduleApplicationsOnNamespace(namespace, taskName)
			for _, ctx := range appContexts {
				ctx.ReadinessTimeout = AppReadinessTimeout
				namespace := GetAppNamespace(ctx, taskName)
				bkpNamespaces = append(bkpNamespaces, namespace)
				scheduledAppContexts = append(scheduledAppContexts, ctx)
			}
		}

		err = ThrottleNetworkSpeed(10)
		if err != nil {
			log.FailOnError(err, "Unable to update the network bandwidth usage")
		}

	})

	JustBeforeEach(func() {
		// Get Admin User Context
		adminContext, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin user ctx")
		cloudCredName, cloudCredUID = "", uuid.New()
		for _, provider := range providers {
			// Create Cloud Credential
			cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
			err = CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))

			// Create BackupLocation
			bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
			backupLocationUID = uuid.New()
			backupLocationMap[backupLocationUID] = bkpLocationName
			err = CreateBackupLocationWithContext(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", adminContext, true)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
		}
		// Create a cluster
		err = AddSourceCluster(adminContext)
		dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of source [%s] cluster with admin ctx", SourceClusterName))
		sourceClusterUID, err = Inst().Backup.GetClusterUID(adminContext, BackupOrgID, SourceClusterName)
		dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))

		// Create Schedule Policy
		log.InfoD("Creating backup interval schedule policy")
		schedulePolicyUid = uuid.New()
		schedulePolicyName = fmt.Sprintf("%s-%s", "periodic", RandomString(6))
		periodicSchedulePolicyInfo := Inst().Backup.CreateIntervalSchedulePolicy(10, 15, 2)
		periodicPolicyStatus := Inst().Backup.BackupSchedulePolicy(schedulePolicyName, schedulePolicyUid, BackupOrgID, periodicSchedulePolicyInfo)
		dash.VerifyFatal(periodicPolicyStatus, nil, fmt.Sprintf("Creation of periodic schedule policy - %s", schedulePolicyName))
		log.Infof("Schedule policy status, name, uid: %v, %v, %v", periodicPolicyStatus, schedulePolicyName, schedulePolicyUid)
	})

	// Testrail id - T90054302 verify ParallelBackupSchedule for Pxd volumes
	It("VerifyPxdVolumeParallelScheduledBackups", func() {
		StartPxBackupTorpedoTest("VerifyPxdVolumeParallelScheduledBackups", "verify ParallelBackupSchedule for Pxd volumes", nil, 90054302, Shkumari, Q4FY25)
		var (
			scheduleName = fmt.Sprintf("schedule-bkp-%v", RandomString(5))
		)
		Step("create parallel backup schedule for Pxd volumes and Verify", func() {
			// Get Admin User Context
			adminContext, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")
			// Create periodic backup schedule objects
			_, err = CreateScheduleBackupWithoutCheck(scheduleName, SourceClusterName, sourceClusterUID, bkpLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", schedulePolicyName, schedulePolicyUid, adminContext, true)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of scheduled backup with schedule name [%s]", scheduleName))

			// Validate Parallel Backup Schedule
			err = ValidateNumberOfParallelScheduledBackups(scheduleName, BackupOrgID, 15, adminContext, 2)
			if err != nil {
				log.FailOnError(err, "VerifyNumberOfParallelScheduledBackupsCreated")
			}
			log.InfoD("Validated Parallel Backup Schedule")
		})

		Step("cleanup- delete the created resources", func() {
			// Get Admin User Context
			adminContext, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")
			// Suspend the backup schedule so that no new backup is created while we are deleting the schedule
			err = SuspendBackupSchedule(scheduleName, schedulePolicyName, BackupOrgID, adminContext)
			log.FailOnError(err, "failed to suspend backup schedule")
			backupScheduleUID, err := GetScheduleUID(scheduleName, BackupOrgID, adminContext)
			log.FailOnError(err, "failed to get schedule uid")
			err = DeleteScheduleWithUIDAndWait(scheduleName, backupScheduleUID, SourceClusterName, sourceClusterUID, BackupOrgID, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of backup schedule [%s]", scheduleName))

			// Delete the schedule policy
			log.InfoD("Deleting schedule policy [%s]", schedulePolicyName)
			schedulePolicyDeleteRequest := &api.SchedulePolicyDeleteRequest{
				Name:  schedulePolicyName,
				Uid:   schedulePolicyUid,
				OrgId: BackupOrgID,
			}
			_, err = Inst().Backup.DeleteSchedulePolicy(adminContext, schedulePolicyDeleteRequest)
			log.FailOnError(err, "failed to delete schedule policy [%s]", schedulePolicyName)

			// Delete the backups
			backupEnumerateRequest := &api.BackupEnumerateRequest{
				OrgId: BackupOrgID,
			}
			backupList, err := Inst().Backup.EnumerateBackup(adminContext, backupEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")
			for _, backup := range backupList.Backups {
				err = DeleteBackupAndWaitForCompletion(backup.Name, backup.Uid, BackupOrgID, adminContext)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backup))
			}
			CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, adminContext)
		})
	})

	// Testrail id - T90054303 verify BackupSchedule for Pxd volume with parallel-backup flag disabled
	It("VerifyScheduledBackupsParallelBackupsDisabled", func() {
		StartPxBackupTorpedoTest("VerifyScheduledBackupsParallelBackupsDisabled", "verify ParallelBackupSchedule for Pxd volumes with parallel-backup flag disabled", nil, 90054303, Shkumari, Q4FY25)
		var (
			scheduleName = fmt.Sprintf("schedule-bkp-%v", RandomString(5))
		)
		Step("create parallel backup schedule for Pxd volumes with parallel-backup flag disabled and Verify", func() {
			// Get Admin User Context
			adminContext, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")
			// Create periodic backup schedule objects
			_, err = CreateScheduleBackupWithoutCheck(scheduleName, SourceClusterName, sourceClusterUID, bkpLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", schedulePolicyName, schedulePolicyUid, adminContext, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of scheduled backup with schedule name [%s]", scheduleName))

			// Validate parallel backups disabled scheduled backups
			err = ValidateNumberOfParallelScheduledBackups(scheduleName, BackupOrgID, 15, adminContext, 2)
			log.FailOnNoError(err, "VerifyScheduledBackupsParallelBackupsDisabled")
			if !strings.Contains(err.Error(), "not been created up to the provided ordinal value") {
				log.FailOnError(err, "next scheduled backup has been created before first was successful")
			}
			log.InfoD("Validated parallel backups disabled scheduled backups")

			// Validate next scheduled backup is in progress after the first backup is completed, at next interval
			err = ValidateParallelBackupScheduleNonPxdVolume(scheduleName, BackupOrgID, 15, adminContext)
			if err != nil {
				log.FailOnError(err, "VerifyScheduledBackupsParallelBackupsDisabled")
			}
			log.InfoD("Validated next scheduled backup is in progress after the first backup is completed, at next interval")
		})

		Step("cleanup- delete the created resources", func() {
			// Get Admin User Context
			adminContext, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")
			// Suspend the backup schedule so that no new backup is created while we are deleting the schedule
			err = SuspendBackupSchedule(scheduleName, schedulePolicyName, BackupOrgID, adminContext)
			log.FailOnError(err, "failed to suspend backup schedule")
			backupScheduleUID, err := GetScheduleUID(scheduleName, BackupOrgID, adminContext)
			log.FailOnError(err, "failed to get schedule uid")

			// Validate that the next backup is completed
			err = Inst().Backup.BackupScheduleWaitForNBackupsCompletion(
				adminContext,
				scheduleName,
				BackupOrgID,
				2,
				BackupCompletionWaitTime,
				defaultWaitInterval,
			)
			log.FailOnError(err, "failed to wait for next backup completion")

			err = DeleteScheduleWithUIDAndWait(scheduleName, backupScheduleUID, SourceClusterName, sourceClusterUID, BackupOrgID, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of backup schedule [%s]", scheduleName))

			// Delete the schedule policy
			log.InfoD("Deleting schedule policy [%s]", schedulePolicyName)
			schedulePolicyDeleteRequest := &api.SchedulePolicyDeleteRequest{
				Name:  schedulePolicyName,
				Uid:   schedulePolicyUid,
				OrgId: BackupOrgID,
			}
			_, err = Inst().Backup.DeleteSchedulePolicy(adminContext, schedulePolicyDeleteRequest)
			log.FailOnError(err, "failed to delete schedule policy [%s]", schedulePolicyName)

			// Delete the backups
			backupEnumerateRequest := &api.BackupEnumerateRequest{
				OrgId: BackupOrgID,
			}
			backupList, err := Inst().Backup.EnumerateBackup(adminContext, backupEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")
			for _, backup := range backupList.Backups {
				err = DeleteBackupAndWaitForCompletion(backup.Name, backup.Uid, BackupOrgID, adminContext)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backup))
			}
			CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, adminContext)
		})
	})

	// Testrail id - T90054307 verify ParallelBackupSchedule for Pxd volumes with NameSpace Label
	It("VerifyNumberOfParallelScheduledBackupsCreatedNSLabel", func() {
		StartPxBackupTorpedoTest("VerifyNumberOfParallelScheduledBackupsCreatedNSLabel", "verify ParallelBackupSchedule for Pxd volumes with NameSpace Label", nil, 90054307, Shkumari, Q4FY25)
		var (
			scheduleName = fmt.Sprintf("schedule-bkp-%v", RandomString(5))
		)

		Step("create parallel backup schedule for Pxd volumes with NameSpace Label and Verify", func() {
			// Get Admin User Context
			adminContext, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")
			log.InfoD("Adding labels to namespaces")
			nsLabelsMap = GenerateRandomLabels(20)
			err = AddLabelsToMultipleNamespaces(nsLabelsMap, bkpNamespaces)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Adding labels [%v] to namespaces [%v]", nsLabelsMap, bkpNamespaces))

			log.InfoD("Generating namespace label string from label map for namespaces")
			nsLabelString := MapToKeyValueString(nsLabelsMap)
			log.Infof("label string for namespaces %s", nsLabelString)
			labelSelectors := make(map[string]string)

			// Create periodic backup schedule objects with namespace label
			_, err = CreateScheduleBackupWithNamespaceLabelWithoutCheck(scheduleName, SourceClusterName, sourceClusterUID, bkpLocationName, backupLocationUID, labelSelectors, BackupOrgID, "", "", "", "", schedulePolicyName, schedulePolicyUid, nsLabelString, adminContext, true)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of schedule backup with schedule name [%s]", scheduleName))
			err = ValidateNumberOfParallelScheduledBackups(scheduleName, BackupOrgID, 15, adminContext, 2)
			if err != nil {
				log.FailOnError(err, "VerifyNumberOfParallelScheduledBackupsCreated")
			}
			log.InfoD("Validated Parallel Backup Schedule With Namespace Label")
		})

		Step("cleanup- delete the created resources", func() {
			// Get Admin User Context
			adminContext, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")
			// Delete the backup schedules
			scheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
			}
			scheduleList, err := Inst().Backup.EnumerateBackupSchedule(adminContext, scheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backup schedules")
			log.InfoD("Number of backupschedules to delete [%d]", len(scheduleList.BackupSchedules))
			for _, schedule := range scheduleList.BackupSchedules {
				err = DeleteScheduleWithUIDAndWait(schedule.Name, schedule.Uid, SourceClusterName, sourceClusterUID, BackupOrgID, adminContext)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of backup schedule [%s]", schedule))
			}

			// Delete the schedule policy
			log.InfoD("Deleting schedule policy [%s]", schedulePolicyName)
			schedulePolicyDeleteRequest := &api.SchedulePolicyDeleteRequest{
				Name:  schedulePolicyName,
				Uid:   schedulePolicyUid,
				OrgId: BackupOrgID,
			}
			_, err = Inst().Backup.DeleteSchedulePolicy(adminContext, schedulePolicyDeleteRequest)
			log.FailOnError(err, "failed to delete schedule policy [%s]", schedulePolicyName)

			// Delete the backups
			backupEnumerateRequest := &api.BackupEnumerateRequest{
				OrgId: BackupOrgID,
			}
			backupList, err := Inst().Backup.EnumerateBackup(adminContext, backupEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")
			for _, backup := range backupList.Backups {
				err = DeleteBackupAndWaitForCompletion(backup.Name, backup.Uid, BackupOrgID, adminContext)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backup))
			}
			CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, adminContext)
		})
	})

	// Testrail id - 90054312 Restart the portworx pods/ nodes and verify the parallel scheduled backups
	It("VerifyPxdVolumeParallelScheduledBackupsPXPodRestart", func() {
		StartPxBackupTorpedoTest("VerifyPxdVolumeParallelScheduledBackupsPXPodRestart", "Restart the portworx pods/ nodes and verify the parallel scheduled backups", nil, 90054312, Shkumari, Q4FY25)
		var (
			scheduleName = fmt.Sprintf("schedule-bkp-%v", RandomString(5))
		)
		Step("create parallel backup schedule for Pxd volumes, delete PX pods while the snapshot upload is in progress", func() {
			// Get Admin User Context
			adminContext, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")
			// Create periodic backup schedule objects
			_, err = CreateScheduleBackupWithoutCheck(scheduleName, SourceClusterName, sourceClusterUID, bkpLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", schedulePolicyName, schedulePolicyUid, adminContext, true)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of scheduled backup with schedule name [%s]", scheduleName))
			// Wait for 5 mins for the local snapshot to complete
			log.FailOnError(err, "failed to get portworx namespace")
			DeletePXPods(pxNamespace)
			// Wait for PX pods to be up
			log.Info("Waiting for Volume Driver to be up and running")
			for _, n := range node.GetWorkerNodes() {
				err = Inst().V.WaitForPxPodsToBeUp(n)
				dash.VerifyFatal(err, nil, fmt.Sprintf("px pod failed to come up in a node: [%s]", n.Name))
			}
			// Validate Parallel Backup Schedule
			err = ValidateNumberOfParallelScheduledBackups(scheduleName, BackupOrgID, 15, adminContext, 2)
			if err != nil {
				log.FailOnError(err, "VerifyNumberOfParallelScheduledBackupsCreated")
			}
			log.InfoD("Validated Parallel Backup Schedule")
		})
		Step("cleanup- delete the created resources", func() {
			// Get Admin User Context
			adminContext, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")
			// Suspend the backup schedule so that no new backup is created while we are deleting the schedule
			err = SuspendBackupSchedule(scheduleName, schedulePolicyName, BackupOrgID, adminContext)
			log.FailOnError(err, "failed to suspend backup schedule")
			backupScheduleUID, err := GetScheduleUID(scheduleName, BackupOrgID, adminContext)
			log.FailOnError(err, "failed to get schedule uid")
			err = DeleteScheduleWithUIDAndWait(scheduleName, backupScheduleUID, SourceClusterName, sourceClusterUID, BackupOrgID, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of backup schedule [%s]", scheduleName))
			// Delete the schedule policy
			log.InfoD("Deleting schedule policy [%s]", schedulePolicyName)
			schedulePolicyDeleteRequest := &api.SchedulePolicyDeleteRequest{
				Name:  schedulePolicyName,
				Uid:   schedulePolicyUid,
				OrgId: BackupOrgID,
			}
			_, err = Inst().Backup.DeleteSchedulePolicy(adminContext, schedulePolicyDeleteRequest)
			log.FailOnError(err, "failed to delete schedule policy [%s]", schedulePolicyName)
			// Delete the backups
			backupEnumerateRequest := &api.BackupEnumerateRequest{
				OrgId: BackupOrgID,
			}
			backupList, err := Inst().Backup.EnumerateBackup(adminContext, backupEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")
			for _, backup := range backupList.Backups {
				err = DeleteBackupAndWaitForCompletion(backup.Name, backup.Uid, BackupOrgID, adminContext)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backup))
			}
			CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, adminContext)
		})
	})

	AfterAll(func() {
		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		log.InfoD("Deleting deployed applications")
		DestroyApps(scheduledAppContexts, opts)
		err := DeleteNamespaces(bkpNamespaces)
		log.FailOnError(err, "failed to delete namespaces")
		err = ThrottleNetworkSpeed(0)
		if err != nil {
			log.FailOnError(err, "Unable to update the network bandwidth usage")
		}
		log.InfoD("All test cases completed successfully")
	})
})
