package tests

import (
	"context"
	"fmt"
	"os"
	"regexp"
	"strings"
	"time"

	. "github.com/onsi/ginkgo/v2"
	"github.com/pborman/uuid"
	api "github.com/portworx/px-backup-api/pkg/apis/v1"
	"github.com/portworx/sched-ops/k8s/core"
	"github.com/pure-px/stork/pkg/k8sutils"
	"github.com/pure-px/torpedo/drivers"
	"github.com/pure-px/torpedo/drivers/backup"
	"github.com/pure-px/torpedo/drivers/scheduler"
	"github.com/pure-px/torpedo/pkg/log"
	. "github.com/pure-px/torpedo/tests"
	"golang.org/x/sync/errgroup"
	corev1 "k8s.io/api/core/v1"
)

// This test deletes backup custom resource.
var _ = Describe("{DeleteCustomResourceBackup}", func() {
	var (
		backupName           string
		scheduledAppContexts []*scheduler.Context
		bkpNamespaces        []string
		namespace            string
		clusterUid           string
		clusterStatus        api.ClusterInfo_StatusInfo_Status
		cloudCredName        string
		cloudCredUID         string
		backupLocationUID    string
		providers            []string
		backupLocationMap    map[string]string
		labelSelectors       map[string]string
		backupLocation       string
		controlChannel       chan string
		errorGroup           *errgroup.Group
	)
	JustBeforeEach(func() {
		bkpNamespaces = make([]string, 0)
		backupLocationMap = make(map[string]string)
		labelSelectors = make(map[string]string)
		providers = GetBackupProviders()

		StartPxBackupTorpedoTest("DeleteCustomResourceBackup", "Delete custom resource backup", nil, 300500, Prikumar, Q3FY25)
		log.InfoD("Deploy applications")

		scheduledAppContexts = make([]*scheduler.Context, 0)
		for i := 0; i < Inst().GlobalScaleFactor; i++ {
			taskName := fmt.Sprintf("%s-%d", TaskNamePrefix, i)
			appContexts := ScheduleApplications(taskName)
			for _, ctx := range appContexts {
				ctx.ReadinessTimeout = AppReadinessTimeout
				namespace = GetAppNamespace(ctx, taskName)
				bkpNamespaces = append(bkpNamespaces, namespace)
				scheduledAppContexts = append(scheduledAppContexts, ctx)
			}
		}
	})
	//Test case to delete custom resource while backup in progress
	It("Test to validate and delete CRs before completion of backup", func() {
		Step("Validate applications", func() {
			ctx, _ := backup.GetAdminCtxFromSecret()
			controlChannel, errorGroup = ValidateApplicationsStartData(scheduledAppContexts, ctx)
		})

		Step("Creating cloud credentials", func() {
			log.InfoD("Creating cloud credentials")
			providers := GetBackupProviders()
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
				cloudCredUID = uuid.New()
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
			}
		})

		Step("Register cluster for backup", func() {
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			err = CreateApplicationClusters(BackupOrgID, "", "", ctx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, ctx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = Inst().Backup.GetClusterUID(ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
		})

		Step("Creating backup location", func() {
			log.InfoD("Creating backup location")
			providers = GetBackupProviders()
			for _, provider := range providers {
				backupLocation = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = backupLocation
				err := CreateBackupLocation(provider, backupLocation, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", backupLocation))
			}
		})

		Step("Taking backup of applications", func() {
			log.InfoD("Taking Backup of application")
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			backupName = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			appContextsToBackup := FilterAppContextsByNamespace(scheduledAppContexts, []string{namespace})
			_, err = CreateBackupWithoutCheck(ctx, backupName, SourceClusterName, backupLocation, backupLocationUID, appContextsToBackup, labelSelectors, BackupOrgID, clusterUid, "", "", "", "")
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))
		})

		Step("Delete the backups CR", func() {
			log.InfoD("Delete the backups CR")
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			err = DeleteBackupCR(namespace, backupName, SourceClusterName, clusterUid, BackupOrgID, ctx)
			log.InfoD("started deleting the cr")
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying backup CR %s deletion", backupName))
			err = BackupFailedCheck(backupName, BackupOrgID, MaxWaitPeriodForBackupCompletionInMinutes*time.Minute, 30*time.Second, ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying if the backup [%s] is in failed state", backupName))

		})

		//Verify the Failure status of the backup from metrics endpoint
		Step("Verify the failure status of the backup from metrics endpoint", func() {
			pxbNamespace, err := backup.GetPxBackupNamespace()
			dash.VerifyFatal(err, nil, "Getting px-backup namespace")

			allMetricsData, err := RunCurlCmd(pxbNamespace)
			log.FailOnError(err, "Fetching metrics data")

			expected := "4"
			status := GetMetricValue(allMetricsData, PxBackupMetricsName, backupName)
			log.Infof("pxbackup_backup_status recived:", status)
			dash.VerifyFatal(status, expected, "Verify the failure status of the pxbackup_backup_status from metrics endpoint")
		})
	})
	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		log.InfoD("Deleting the deployed apps after the testcase")
		// Cleaning up applications created
		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		err := DestroyAppsWithData(scheduledAppContexts, opts, controlChannel, errorGroup)
		log.FailOnError(err, "Data validations failed")

		// Cleaning up px-backup cluster
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)
	})
})

// This testcase validates static entries of the stork-controller-config configmap before and after pod restart
var _ = Describe("{VerifyStaticEntriesOfStorkControllerCm}", Label(TestCaseLabelsMap[StorkControllerConfigCM]...), func() {

	var (
		scheduledAppContexts []*scheduler.Context
		duplicateMap         map[string]string
	)
	JustBeforeEach(func() {
		duplicateMap = make(map[string]string)

		StartPxBackupTorpedoTest("VerifyStaticEntriesOfStorkControllerCm", "Validate static entry parameteres like admin-ns, service-account and stork-deploy-ns are not changed after stork pod restart", nil, 300557, Prikumar, Q2FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
	})

	// Validate static entry parameters like admin-ns, service-account and stork-deploy-ns are not changed after stork pod restart
	It("Test to verify static entries of the stork-controller-config configmap before and after pod restart", func() {

		// Validate static entry parameters of stork-controller-config configmap before pod restart
		Step("Verify the admin-ns, service-account, stork-deploy-ns value before pod restart", func() {
			log.InfoD("Verify the admin-ns, service-account, stork-deploy-ns value before pod restart")

			storkControllerConfigMapObject, err := core.Instance().GetConfigMap(StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			log.InfoD("stork map [%v] default-ns [%v]", StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			if err != nil {
				log.Errorf("Error getting stork controller configmap: %v", err)
			}

			for key, value := range storkControllerConfigMapObject.Data {
				duplicateMap[key] = value
				log.Infof("Value of [%s] in stork controller configmap is [%v]", key, duplicateMap[key])
			}
		})

		// Restart stork pods to verify the values
		Step("Get pods from new admin namespace", func() {
			storkDeploymentNamespace, err := k8sutils.GetStorkPodNamespace()
			if err != nil {
				log.InfoD("error geting strk")
			}
			// Delete stork pods with label
			err = DeletePodWithWithoutLabelInNamespace(storkDeploymentNamespace, StorkLabel, false)
			dash.VerifyFatal(err, nil, "Restart stork pods")
			err = ValidatePodByLabel(StorkLabel, storkDeploymentNamespace, 5*time.Minute, 30*time.Second)
			log.FailOnError(err, "Checking if stork pod is in running state")
		})

		// Validate static entry parameters of stork-controller-config configmap after pod restart
		Step("Verify the admin-ns, service-account, stork-deploy-ns value after stork pod restart", func() {
			log.InfoD("Verify the admin-ns, service-account, stork-deploy-ns value after stork pod restart")

			storkControllerConfigMapObject, err := core.Instance().GetConfigMap(StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			if err != nil {
				log.Errorf("Error getting stork controller configmap: %v", err)
			}

			for key, _ := range storkControllerConfigMapObject.Data {
				log.InfoD("Stork controller configmap value [%s] is equal after stork pod restart %s %s", key, storkControllerConfigMapObject.Data[key], duplicateMap[key])
				dash.VerifyFatal(storkControllerConfigMapObject.Data[key], duplicateMap[key], "Stork controller configmap values remains same after pod restart")

			}
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		log.InfoD("Deleting the deployed apps after the testcase")
		CleanupCloudSettingsAndClusters(nil, "", "", ctx)

	})
})

// This testcase validates large-resource-size-limit parameter is added and removed from stork-controller-config configmap after pod restart
var _ = Describe("{VerifyLargeResourceSizeLimitParamIsRemovedFromStorkCM}", Label(TestCaseLabelsMap[StorkControllerConfigCM]...), func() {

	var (
		scheduledAppContexts []*scheduler.Context
		largeResourceSize    string
	)
	JustBeforeEach(func() {
		largeResourceSize = "10000"

		StartPxBackupTorpedoTest("VerifyLargeResourceSizeLimitParamIsRemovedFromStorkCM", "Validate large-resource-size-limit parameter is added and removed from stork-controller-config configmap after stork pod restart", nil, 300555, Prikumar, Q2FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
	})

	// Validates large-resource-size-limit parameter is added and removed from stork-controller-config configmap after pod restart
	It("Test to verify large-resource-size-limit parameter is added and removed from stork-controller-config configmap after pod restart", func() {

		// Adding new parameter to stork-controller-config configmap
		Step("Adding large-resource-size-limit parameter to strok-controller-config CM before pod restart", func() {
			log.InfoD("Adding large-resource-size-limit parameter to strok-controller-config CM before pod restart")

			storkControllerConfigMapObject, err := core.Instance().GetConfigMap(StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			log.InfoD("stork map [%v] default-ns [%v]", StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			if err != nil {
				log.Errorf("Error getting stork controller configmap: %v", err)
			}

			storkControllerConfigMapObject.Data["large-resource-size-limit"] = largeResourceSize
			log.Infof("Value of large-resource-size-limit in stork controller configmap is %s", storkControllerConfigMapObject.Data["large-resource-size-limit"])

			storkControllerConfigMapObject, err = core.Instance().UpdateConfigMap(storkControllerConfigMapObject)
			if err != nil {
				log.InfoD("Object is not updated")
			}
			for key, _ := range storkControllerConfigMapObject.Data {
				log.Infof("Value of [%s] in stork controller configmap is [%v]", key, storkControllerConfigMapObject.Data[key])
			}
			dash.VerifyFatal(storkControllerConfigMapObject.Data["large-resource-size-limit"], largeResourceSize, "Large resource size limit CM value is added to the stork-controller-config")
		})

		// Remove newly added parameter from stork-controller-config configmap
		Step("Remove newly added large-resource-size-limit parameter from stork-controller-config CM", func() {
			storkControllerConfigMapObject, err := core.Instance().GetConfigMap(StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			if err != nil {
				log.Errorf("Error getting stork controller configmap: %v", err)
			}

			// Delete newly added parameter from config map
			delete(storkControllerConfigMapObject.Data, "large-resource-size-limit")
			storkControllerConfigMapObject, err = core.Instance().UpdateConfigMap(storkControllerConfigMapObject)
			if err != nil {
				log.InfoD("Config map object is not updated")
			}
			for key, _ := range storkControllerConfigMapObject.Data {
				log.Infof("Value of [%s] in stork controller configmap after deletion [%v]", key, storkControllerConfigMapObject.Data[key])
			}
			dash.VerifyFatal(storkControllerConfigMapObject.Data["large-resource-size-limit"], "", "Verify large resource size limit CM value is removed")
		})

		// Restart stork pods to verify the values
		Step("Get pods from new admin namespace", func() {
			storkDeploymentNamespace, err := k8sutils.GetStorkPodNamespace()
			if err != nil {
				log.InfoD("error geting strk")
			}
			// Delete stork pods with label
			err = DeletePodWithWithoutLabelInNamespace(storkDeploymentNamespace, StorkLabel, false)
			dash.VerifyFatal(err, nil, "Restart stork pods")
			err = ValidatePodByLabel(StorkLabel, storkDeploymentNamespace, 5*time.Minute, 30*time.Second)
			log.FailOnError(err, "Checking if stork pod is in running state")
		})

		// Validate large-resource-size-limit parameter is removed from stork-controller-config CM after pod restart
		Step("Verify large-resource-size-limit parameter is removed from stork-controller-config CM", func() {
			log.InfoD("Verify large-resource-size-limit parameter is removed from stork-controller-config CM after stork pod restart")

			storkControllerConfigMapObject, err := core.Instance().GetConfigMap(StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			if err != nil {
				log.Errorf("Error getting stork controller configmap: %v", err)
			}

			for key, _ := range storkControllerConfigMapObject.Data {
				log.Infof("value of [%s] in stork controller configmap after pod restart [%v]", key, storkControllerConfigMapObject.Data[key])
			}
			dash.VerifyFatal(storkControllerConfigMapObject.Data["large-resource-size-limit"], "", "Verify large resource size limit CM value is removed after pod restart")
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		log.InfoD("Deleting the deployed apps after the testcase")
		CleanupCloudSettingsAndClusters(nil, "", "", ctx)

	})
})

// This testcase verifies whether the backup is a large resource backup by adding small value to large-resource-size-limit configmap
var _ = Describe("{VerifyBackupIsLargeResourceBackup}", Label(TestCaseLabelsMap[StorkControllerConfigCM]...), func() {

	var (
		scheduledAppContexts []*scheduler.Context
		backupName           string
		bkpNamespaces        []string
		namespace            string
		clusterUid           string
		clusterStatus        api.ClusterInfo_StatusInfo_Status
		cloudCredName        string
		cloudCredUID         string
		backupLocationUID    string
		providers            []string
		backupLocationMap    map[string]string
		backupLocation       string
		largeResourceSize    string
		totalBackupSize      uint64
	)
	JustBeforeEach(func() {
		bkpNamespaces = make([]string, 0)
		backupLocationMap = make(map[string]string)
		providers = GetBackupProviders()
		largeResourceSize = "100"

		StartPxBackupTorpedoTest("VerifyBackupIsLargeResourceBackup", "Verify whether the backup is a large resource backup by adding small value to large-resource-size-limit configmap parameter", nil, 300556, Prikumar, Q2FY25)
		log.InfoD("Deploy applications")

		scheduledAppContexts = make([]*scheduler.Context, 0)
		for i := 0; i < Inst().GlobalScaleFactor; i++ {
			taskName := fmt.Sprintf("%s-%d", TaskNamePrefix, i)
			appContexts := ScheduleApplications(taskName)
			for _, ctx := range appContexts {
				ctx.ReadinessTimeout = AppReadinessTimeout
				namespace = GetAppNamespace(ctx, taskName)
				bkpNamespaces = append(bkpNamespaces, namespace)
				scheduledAppContexts = append(scheduledAppContexts, ctx)
			}
		}
	})

	// Verify whether the backup is a large resource backup by adding small value to large-resource-size-limit configmap parameter
	It("Test to verify whether the backup is a large resource backup", func() {

		Step("Validate applications", func() {
			log.Infof("Validate applications")
			ValidateApplications(scheduledAppContexts)
		})

		// Creating cloud credentials and backup location
		Step("Creating cloud credentials and backup location", func() {
			log.InfoD("Creating cloud credentials and backup location")
			providers = GetBackupProviders()
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
				cloudCredUID = uuid.New()
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				log.InfoD("Created Cloud Credentials with name - %s", cloudCredName)
				backupLocation = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = backupLocation
				err = CreateBackupLocation(provider, backupLocation, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %v", backupLocation))
				log.InfoD("Created Backup Location with name - %s", backupLocation)

			}
		})

		// Create cluster for backup
		Step("Register cluster for backup", func() {
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			err = CreateApplicationClusters(BackupOrgID, "", "", ctx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, ctx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = Inst().Backup.GetClusterUID(ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
		})

		// Check stork version
		Step("Check stork version", func() {
			CurrentStorkImage, err := GetStorkImageVersion()
			log.FailOnError(err, "Getting the current stork version")
			log.InfoD("Current stork image version is - %s", CurrentStorkImage)
		})

		// Adding new parameter to stork-controller-config configmap
		Step("Adding large-resource-size-limit parameter to strok-controller-config CM before pod restart", func() {
			log.InfoD("Adding large-resource-size-limit parameter to strok-controller-config CM before pod restart")

			storkControllerConfigMapObject, err := core.Instance().GetConfigMap(StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			log.InfoD("stork map [%v] default-ns [%v]", StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			if err != nil {
				log.Errorf("Error getting stork controller configmap: %v", err)
			}

			storkControllerConfigMapObject.Data["large-resource-size-limit"] = largeResourceSize
			log.Infof("Value of large-resource-size-limit in stork controller configmap is %s", storkControllerConfigMapObject.Data["large-resource-size-limit"])

			storkControllerConfigMapObject, err = core.Instance().UpdateConfigMap(storkControllerConfigMapObject)
			if err != nil {
				log.InfoD("Object is not updated")
			}
			for key, _ := range storkControllerConfigMapObject.Data {
				log.Infof("Value of [%s] in stork controller configmap is [%v]", key, storkControllerConfigMapObject.Data[key])
			}
		})

		Step("Taking backup of applications", func() {
			log.InfoD("Taking Backup of application")
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			backupName = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			appContextsToBackup := FilterAppContextsByNamespace(scheduledAppContexts, []string{namespace})
			err = CreateBackupWithValidation(ctx, backupName, SourceClusterName, backupLocation, backupLocationUID, appContextsToBackup, nil, BackupOrgID, clusterUid, "", "", "", "")
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of backup [%s]", backupName))
		})

		// Fetch actual volumes backup size from cluster
		Step("Get total Actual backup size volumes from cluster", func() {
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			bkpEnumerateReq := &api.BackupEnumerateRequest{OrgId: BackupOrgID}
			enumerateRsp, err := Inst().Backup.EnumerateBackup(ctx, bkpEnumerateReq)
			dash.VerifyFatal(err, nil, "Backup enumeration for the ctx")

			for i, bk := range enumerateRsp.GetBackups() {
				for _, volume := range bk.GetVolumes() {
					totalBackupSize = totalBackupSize + volume.ActualSize
					log.InfoD("Verify backup size [%v] [%d]", i, totalBackupSize)
				}
			}
			log.InfoD("total backup size from cluster: [%v]", totalBackupSize)
		})

		// Verify whether the backup is a large resource backup
		Step("Checking whether the backup is a large resource backup", func() {
			log.InfoD("Checking whether the backup [%s] is a large resource backup", backupName)
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")

			isLargeResourceBackup, err := IsLargeResourceBackup(ctx, backupName, BackupOrgID)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Checking the backup [%s] is a large resource backup", backupName))
			dash.VerifyFatal(isLargeResourceBackup, true, fmt.Sprintf("Verifying the backup [%s] is a large resource backup", backupName))
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		defer func() {
			storkControllerConfigMapObject, err := core.Instance().GetConfigMap(StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			if err != nil {
				log.Errorf("Error getting stork controller configmap: %v", err)
			}
			// Delete large-resource-size-limit parameter from strok-controller-configmap
			delete(storkControllerConfigMapObject.Data, "large-resource-size-limit")
			storkControllerConfigMapObject, err = core.Instance().UpdateConfigMap(storkControllerConfigMapObject)
			log.FailOnError(err, fmt.Sprintf("Failed to update %s configmap", storkControllerConfigMapObject))
		}()
		log.InfoD("Deleting the deployed apps after the testcase")
		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)
	})
})

// This testcase validates large-resource-size-limit configmap value is not changed after pod restart
var _ = Describe("{VerifyLargeResourceSizeLimitValueIsNotChangedAfterPodRestart}", Label(TestCaseLabelsMap[StorkControllerConfigCM]...), func() {

	var (
		scheduledAppContexts []*scheduler.Context
		largeResourceSize    string
	)
	JustBeforeEach(func() {
		largeResourceSize = "10000"

		StartPxBackupTorpedoTest("VerifyLargeResourceSizeLimitValueIsNotChangedAfterPodRestart", "Validate large-resource-size-limit configmap value is not changed after stork pod restart", nil, 300554, Prikumar, Q2FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
	})

	// Validates large-resource-size-limit configmap value remains same after stork pod restart
	It("Test to verify large-resource-size-limit configmap value remains same after stork pod restart", func() {
		// Check stork version
		Step("Check stork version", func() {
			CurrentStorkImage, err := GetStorkImageVersion()
			log.FailOnError(err, "Getting the current stork version")
			log.InfoD("Current stork image version is - %s", CurrentStorkImage)
		})

		// Adding new parameter to stork-controller-config configmap
		Step("Adding large-resource-size-limit parameter to strok-controller-config CM before pod restart", func() {
			log.InfoD("Adding large-resource-size-limit parameter to strok-controller-config CM before pod restart")

			storkControllerConfigMapObject, err := core.Instance().GetConfigMap(StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			log.InfoD("stork map [%v] default-ns [%v]", StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			if err != nil {
				log.Errorf("Error getting stork controller configmap: %v", err)
			}

			storkControllerConfigMapObject.Data["large-resource-size-limit"] = largeResourceSize
			log.Infof("Value of large-resource-size-limit in stork controller configmap is %s", storkControllerConfigMapObject.Data["large-resource-size-limit"])

			storkControllerConfigMapObject, err = core.Instance().UpdateConfigMap(storkControllerConfigMapObject)
			if err != nil {
				log.InfoD("Object is not updated")
			}
			for key, _ := range storkControllerConfigMapObject.Data {
				log.Infof("Value of [%s] in stork controller configmap is [%v]", key, storkControllerConfigMapObject.Data[key])
			}
		})

		// Restart stork pods to verify the values
		Step("Get pods from new admin namespace", func() {
			storkDeploymentNamespace, err := k8sutils.GetStorkPodNamespace()
			if err != nil {
				log.InfoD("error geting strk")
			}
			// Delete stork pods with label
			err = DeletePodWithWithoutLabelInNamespace(storkDeploymentNamespace, StorkLabel, false)
			dash.VerifyFatal(err, nil, "Restart stork pods")
			err = ValidatePodByLabel(StorkLabel, storkDeploymentNamespace, 5*time.Minute, 30*time.Second)
			log.FailOnError(err, "Checking if stork pod is in running state")
		})

		// Validate large-resource-size-limit configmap value remains same after pod restart
		Step("Verify large-resource-size-limit configmap value remains same after pod restart", func() {
			log.InfoD("Verify large-resource-size-limit configmap value remains same after pod restart")

			storkControllerConfigMapObject, err := core.Instance().GetConfigMap(StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			if err != nil {
				log.Errorf("Error getting stork controller configmap: %v", err)
			}

			for key, _ := range storkControllerConfigMapObject.Data {
				log.Infof("value of [%s] in stork controller configmap after pod restart [%v]", key, storkControllerConfigMapObject.Data[key])
			}
			dash.VerifyFatal(storkControllerConfigMapObject.Data["large-resource-size-limit"], largeResourceSize,
				fmt.Sprintf("Large resource size limit CM value [%s] remains same after pod restart", storkControllerConfigMapObject.Data["large-resource-size-limit"]))
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		defer func() {
			storkControllerConfigMapObject, err := core.Instance().GetConfigMap(StorkControllerConfigMap, DefaultStorkDeploymentNamespace)
			if err != nil {
				log.Errorf("Error getting stork controller configmap: %v", err)
			}
			// Delete large-resource-size-limit parameter from strok-controller-configmap
			delete(storkControllerConfigMapObject.Data, "large-resource-size-limit")
			storkControllerConfigMapObject, err = core.Instance().UpdateConfigMap(storkControllerConfigMapObject)
			log.FailOnError(err, fmt.Sprintf("Failed to update %s configmap", storkControllerConfigMapObject))
		}()
		log.InfoD("Deleting the deployed apps after the testcase")
		CleanupCloudSettingsAndClusters(nil, "", "", ctx)

	})
})

// Generic backup deletion, when the S3 bucket is missing
var _ = Describe("{ValidateGenericBackupDeletionWithMissingS3Bucket}", Label(TestCaseLabelsMap[KDMPBackup]...), func() {
	var (
		scheduledAppContexts []*scheduler.Context
		bkpNamespaces        []string
		clusterUid           string
		clusterStatus        api.ClusterInfo_StatusInfo_Status
		backupName           string
		backupLocationUID    string
		cloudCredName        string
		cloudCredUID         string
		bkpLocationName      string
		backupNames          []string
		providers            []string
		ctx                  context.Context
	)
	backupLocationMap := make(map[string]string)
	bkpNamespaces = make([]string, 0)
	backupNames = make([]string, 0)
	labelSelectors := make(map[string]string)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyTestGenericBackupDeletionWithMissingS3Bucket", "Verify Generic backup deletion, when the S3 bucket is missing.", nil, 300192, Pingle, Q3FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
	})

	// Generic backup deletion, when the S3 bucket is missing
	It("Verify Generic backup deletion, when the S3 bucket is missing", func() {
		numOfBackup := 1
		// 1. validate application
		Step("Validate applications", func() {
			log.InfoD("Validating applications")
			ValidateApplications(scheduledAppContexts)
		})

		// 2. common initializations
		Step("common init", func() {
			var err error
			ctx, err = backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")

			providers = GetBackupProviders()
		})

		// 3. Create cloud credentials and backup location
		Step("Creating cloud credentials and backup location", func() {
			log.InfoD("Creating cloud credentials and backup location")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cloudcred", provider, time.Now().Unix())
				bkpLocationName = fmt.Sprintf("%s-%s-%v-bl", provider, getGlobalBucketName(provider), time.Now().Unix())
				cloudCredUID = uuid.New()
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				err = CreateBackupLocation(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		// 4. Create application cluster for backup
		Step("Register cluster for backup", func() {
			err := CreateApplicationClusters(BackupOrgID, "", "", ctx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, ctx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = Inst().Backup.GetClusterUID(ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
			log.InfoD("Uid of [%s] cluster is %s", SourceClusterName, clusterUid)
		})

		// 5. Take the backup of bkNamespaces.
		Step("Taking backup of applications", func() {
			for i := 0; i < numOfBackup; i++ {
				backupName = fmt.Sprintf("%s-%s-%v", BackupNamePrefix, bkpNamespaces[0], time.Now().Unix())
				namespaceLabel := fmt.Sprintf("%s-label-schedule-%s", BackupNamePrefix, RandomString(4))
				params := map[string]string{"backupName": backupName, "backupOrgID": BackupOrgID, "bkpLocationName": bkpLocationName, "backupLocationUID": backupLocationUID, "clusterName": SourceClusterName, "clusterUid": clusterUid}
				bkpCreateRequest, err := PrepareGenericBackupRequest(params)
				dash.VerifyFatal(err, nil, fmt.Sprintf("decorating data of KDMP backup [%s]", backupName))
				bkpCreateRequest.NsLabelSelectors = namespaceLabel
				bkpCreateRequest.LabelSelectors = labelSelectors
				log.InfoD("Backup without check [%s] started at [%s]", backupName, time.Now().Format("2006-01-02 15:04:05"))
				_, err = Inst().Backup.CreateBackup(ctx, bkpCreateRequest)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of KDMP backup [%s]", backupName))
				backupNames = append(backupNames, backupName)
			}
		})

		// 6. Delete s3 bucket
		Step("Delete s3 bucket and then delete backup", func() {
			DeleteS3Bucket(getGlobalBucketName(providers[0]))
			backupUID, err := Inst().Backup.GetBackupUID(ctx, backupName, BackupOrgID)
			dash.VerifySafely(err, nil, fmt.Sprintf("Getting backuip UID for backup %s", backupName))
			_, err = DeleteBackup(backupName, backupUID, BackupOrgID, ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying backup deletion - %s", backupName))
			err = Inst().Backup.WaitForBackupDeletion(ctx, backupName, BackupOrgID, BackupDeleteTimeout, BackupDeleteRetryTime)
			log.FailOnError(err, "failed while waiting for backup %s to be deleted", backupName)
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		defer func() {
			log.Infof("Unsetting BACKUP_TYPE env variable")
			err := os.Unsetenv("BACKUP_TYPE")
			log.FailOnError(err, "Unsetting BACKUP_TYPE env variable")
		}()

		log.InfoD("Deleting the deployed apps after the testcase")
		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		DestroyApps(scheduledAppContexts, opts)

		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)

	})
})

// Validate that the backup sync syncs all the backups (both generic and non-genric) present in bucket
var _ = Describe("{ValidateGenericAndNonGenericBackupSync}", Label(TestCaseLabelsMap[KDMPBackup]...), func() {
	var (
		scheduledAppContexts []*scheduler.Context
		bkpNamespaces        []string
		clusterUid           string
		clusterStatus        api.ClusterInfo_StatusInfo_Status
		backupName           string
		backupLocationUID    string
		cloudCredName        string
		cloudCredUID         string
		bkpLocationName      string
		backupNames          []string
		providers            []string
		ctx                  context.Context
	)
	backupLocationMap := make(map[string]string)
	bkpNamespaces = make([]string, 0)
	backupNames = make([]string, 0)
	labelSelectors := make(map[string]string)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyValidateGenericAndNonGenericBackupSync", "Validate that the backup sync syncs all the backups (both generic and non-genric) present in bucket.", nil, 300159, Pingle, Q3FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
	})

	// Validate that the backup sync syncs all the backups (both generic and non-genric) present in bucket
	It("Verify Validate that the backup sync syncs all the backups", func() {
		numOfKDMPBackup := 2
		// 1. validate application
		Step("Validate applications", func() {
			log.InfoD("Validating applications")
			ValidateApplications(scheduledAppContexts)
		})

		// 2. common initializations
		Step("common init", func() {
			var err error
			ctx, err = backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")

			providers = GetBackupProviders()
		})

		// 3. Create cloud credentials and backup location
		Step("Creating cloud credentials and backup location", func() {
			log.InfoD("Creating cloud credentials and backup location")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cloudcred", provider, time.Now().Unix())
				bkpLocationName = fmt.Sprintf("%s-%s-%v-bl", provider, getGlobalBucketName(provider), time.Now().Unix())
				cloudCredUID = uuid.New()
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				err = CreateBackupLocation(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		// 4. Create application cluster for backup
		Step("Register cluster for backup", func() {
			err := CreateApplicationClusters(BackupOrgID, "", "", ctx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, ctx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = Inst().Backup.GetClusterUID(ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
			log.InfoD("Uid of [%s] cluster is %s", SourceClusterName, clusterUid)
		})

		// 5. Take 1 non generic backup
		Step("Taking backup of applications", func() {
			log.InfoD("Taking Backup of application")
			backupName = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			appContextsToBackup := FilterAppContextsByNamespace(scheduledAppContexts, bkpNamespaces)
			_, err := CreateBackupWithoutCheck(ctx, backupName, SourceClusterName, bkpLocationName, backupLocationUID, appContextsToBackup, nil, BackupOrgID, clusterUid, "", "", "", "")
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of normal backup [%s]", backupName))
			backupNames = append(backupNames, backupName)
		})

		// 6. Take 2 KDMP backup.
		Step("Taking backup of applications", func() {
			for i := 0; i < numOfKDMPBackup; i++ {
				backupName = fmt.Sprintf("%s-%s-%v", BackupNamePrefix, bkpNamespaces[0], time.Now().Unix())
				namespaceLabel := fmt.Sprintf("%s-label-schedule-%s", BackupNamePrefix, RandomString(4))
				params := map[string]string{"backupName": backupName, "backupOrgID": BackupOrgID, "bkpLocationName": bkpLocationName, "backupLocationUID": backupLocationUID, "clusterName": SourceClusterName, "clusterUid": clusterUid}
				bkpCreateRequest, err := PrepareGenericBackupRequest(params)
				dash.VerifyFatal(err, nil, fmt.Sprintf("decorating data of KDMP backup [%s]", backupName))
				bkpCreateRequest.NsLabelSelectors = namespaceLabel
				bkpCreateRequest.LabelSelectors = labelSelectors
				log.InfoD("Backup without check [%s] started at [%s]", backupName, time.Now().Format("2006-01-02 15:04:05"))
				_, err = Inst().Backup.CreateBackup(ctx, bkpCreateRequest)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of KDMP backup [%s]", backupName))
				backupNames = append(backupNames, backupName)
			}
		})

		// 7. Remove the backup location where backups were taken
		Step("Remove the backup location where backups were taken", func() {
			log.InfoD("Remove backup location where backups were taken")
			// remove backup location call
			err := DeleteBackupLocation(bkpLocationName, backupLocationUID, BackupOrgID, false)
			dash.VerifySafely(err, nil, fmt.Sprintf("Deleting backup location %s", bkpLocationName))

			// Wait until backup location is removed
			backupLocationDeleteStatusCheck := func() (interface{}, bool, error) {
				ctx, err := backup.GetAdminCtxFromSecret()
				log.FailOnError(err, "Fetching px-central-admin ctx")
				status, err := IsBackupLocationPresent(bkpLocationName, ctx, BackupOrgID)
				if err != nil {
					return "", true, fmt.Errorf("backup location %s still present with error %v", bkpLocationName, err)
				}
				if status == true {
					return "", true, fmt.Errorf("backup location %s is not deleted yet", bkpLocationName)
				}
				return "", false, nil
			}
			_, err = DoRetryWithTimeoutWithGinkgoRecover(backupLocationDeleteStatusCheck, 3*time.Minute, 30*time.Second)
			dash.VerifySafely(err, nil, fmt.Sprintf("Deleting backup location %s", bkpLocationName))
		})

		// 7. Enumerate backup after location is deleted
		Step("Enumerate backup:", func() {
			bkpEnumerateReq := &api.BackupEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					ClusterUidFilter: clusterUid,
				},
			}
			backupObj, err := Inst().Backup.EnumerateBackup(ctx, bkpEnumerateReq)
			dash.VerifyFatal(err, nil, "Verifying enumerate backup")
			log.Infof("backup obj len:%v", len(backupObj.GetBackups()))
			dash.VerifyFatal(len(backupObj.GetBackups()), 0, "Verifying enumerate backup length")
		})

		// 8. Add the backup location again which had backups
		Step("Add the backup location again which had backups", func() {
			log.InfoD("Add the backup location with backups back")
			for _, provider := range providers {
				bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateBackupLocation(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		// Sync-up backup and check the both backups are synced up.
		Step("Sync-up backup.", func() {
			// Wait for backups to get synced
			checkBackupSync := func() (interface{}, bool, error) {
				fetchedBackupNames, err := GetAllBackupsAdmin()
				log.InfoD(fmt.Sprintf("The list of backups fetched %s", fetchedBackupNames))
				if err != nil {
					return "", true, fmt.Errorf("unable to fetch backups. Error: %s", err.Error())
				}
				if len(fetchedBackupNames) == len(backupNames) {
					return "", false, nil
				}
				return "", true, fmt.Errorf("expected: %d and actual: %d", len(backupNames), len(fetchedBackupNames))
			}
			_, err := DoRetryWithTimeoutWithGinkgoRecover(checkBackupSync, 100*time.Minute, 30*time.Second)
			log.FailOnError(err, "Wait for BackupSync to complete")
			fetchedBackupNames, err := GetAllBackupsAdmin()
			log.FailOnError(err, "Getting a list of all backups")

			// Iterating through all backup and check if they are present in the fetched backup list or not
			listOfFetchedBackups := strings.Join(fetchedBackupNames, "")
			for _, backup := range backupNames {
				re := regexp.MustCompile(fmt.Sprintf("%s-*", backup))
				dash.VerifyFatal(re.MatchString(listOfFetchedBackups), true, fmt.Sprintf("Checking if backup [%s] was synced or not", backup))
			}

			var bkp *api.BackupObject
			backupDriver := Inst().Backup
			bkpEnumerateReq := &api.BackupEnumerateRequest{
				OrgId: BackupOrgID}
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			curBackups, err := backupDriver.EnumerateBackup(ctx, bkpEnumerateReq)
			for _, bkp = range curBackups.GetBackups() {
				backupInspectRequest := &api.BackupInspectRequest{
					Name:  bkp.Name,
					Uid:   bkp.Uid,
					OrgId: BackupOrgID,
				}
				resp, err := backupDriver.InspectBackup(ctx, backupInspectRequest)
				log.FailOnError(err, "Inspect each backup from list")
				actual := resp.GetBackup().GetStatus().Status
				expected := api.BackupInfo_StatusInfo_Success
				dash.VerifyFatal(actual, expected, fmt.Sprintf("Check each backup for success status %s", bkp.Name))
			}
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		defer func() {
			log.Infof("Unsetting BACKUP_TYPE env variable")
			err := os.Unsetenv("BACKUP_TYPE")
			log.FailOnError(err, "Unsetting BACKUP_TYPE env variable")
		}()

		log.InfoD("Deleting the deployed apps after the testcase")
		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		DestroyApps(scheduledAppContexts, opts)

		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)

	})
})

// Verify for every new backup there is a corresponding DataExport CR and VolumeBackup CR for every ApplicationBackup CR.
var _ = Describe("{ValidateDataExportCRAndVolumeBackupCR}", Label(TestCaseLabelsMap[KDMPBackup]...), func() {
	var (
		scheduledAppContexts []*scheduler.Context
		bkpNamespaces        []string
		clusterUid           string
		clusterStatus        api.ClusterInfo_StatusInfo_Status
		backupName           string
		backupLocationUID    string
		cloudCredName        string
		cloudCredUID         string
		bkpLocationName      string
		backupNames          []string
		providers            []string
		ctx                  context.Context
		backupDriver         backup.Driver
	)
	backupLocationMap := make(map[string]string)
	bkpNamespaces = make([]string, 0)
	backupNames = make([]string, 0)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyValidateDataExportCRAndVolumeBackupCR", "Verify for every new backup there is a corresponding DataExport CR and VolumeBackup CR for every ApplicationBackup CR.", nil, 300164, Pingle, Q3FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
		log.Infof("bkpNamespace:%v", bkpNamespaces)
		log.InfoD(fmt.Sprintf("App list %v", Inst().AppList))
	})

	// Verify for every new backup there is a corresponding DataExport CR and VolumeBackup CR for every ApplicationBackup CR.
	It("Verify for every new backup there is a corresponding DataExport CR and VolumeBackup CR for every ApplicationBackup CR.", func() {
		numOfBackup := 1
		var backupCrName string
		// 1. validate application
		Step("Validate applications", func() {
			log.InfoD("Validating applications")
			ValidateApplications(scheduledAppContexts)
		})

		// 2. common initializations
		Step("common init", func() {
			var err error
			ctx, err = backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")

			providers = GetBackupProviders()
			backupDriver = Inst().Backup
		})

		// 3. Create cloud credentials and backup location
		Step("Creating cloud credentials and backup location", func() {
			log.InfoD("Creating cloud credentials and backup location")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cloudcred", provider, time.Now().Unix())
				bkpLocationName = fmt.Sprintf("%s-%s-%v-bl", provider, getGlobalBucketName(provider), time.Now().Unix())
				cloudCredUID = uuid.New()
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				err = CreateBackupLocation(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		// 4. Create application cluster for backup
		Step("Register cluster for backup", func() {
			err := CreateApplicationClusters(BackupOrgID, "", "", ctx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = backupDriver.GetClusterStatus(BackupOrgID, SourceClusterName, ctx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = backupDriver.GetClusterUID(ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
			log.InfoD("Uid of [%s] cluster is %s", SourceClusterName, clusterUid)
		})

		// 5. Take the backup of bkNamespaces.
		Step("Taking backup of applications", func() {
			for i := 0; i < numOfBackup; i++ {
				backupName = fmt.Sprintf("%s-%s-%v", BackupNamePrefix, bkpNamespaces[0], time.Now().Unix())
				params := map[string]string{"backupName": backupName, "backupOrgID": BackupOrgID, "bkpLocationName": bkpLocationName, "backupLocationUID": backupLocationUID, "clusterName": SourceClusterName, "clusterUid": clusterUid}
				bkpCreateRequest, err := PrepareGenericBackupRequest(params)
				dash.VerifyFatal(err, nil, fmt.Sprintf("decorating data of KDMP backup [%s]", backupName))
				bkpCreateRequest.Namespaces = bkpNamespaces
				log.InfoD("Backup without check [%s] started at [%s]", backupName, time.Now().Format("2006-01-02 15:04:05"))
				_, err = backupDriver.CreateBackup(ctx, bkpCreateRequest)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of KDMP backup [%s]", backupName))
				backupNames = append(backupNames, backupName)
			}
		})

		// 6. Get the backup cr from backup object
		Step("Get the backup cr from backup object", func() {
			bkpEnumerateReq := &api.BackupEnumerateRequest{OrgId: BackupOrgID}
			enumerateRsp, err := backupDriver.EnumerateBackup(ctx, bkpEnumerateReq)
			dash.VerifyFatal(err, nil, "Backup enumeration for the ctx")
			log.Infof("crid is:%d", enumerateRsp.GetBackups()[0].CrUid[0:7])

			backupCrName = enumerateRsp.GetBackups()[0].CrUid[0:7]
		})

		// 7. Validate data export CR for backup in ns-mysql
		Step("Validate dataexportCR for backup in ns-mysql", func() {
			log.Infof("all namespaces:", bkpNamespaces)
			err := ValidateDataExportCR(bkpNamespaces, backupCrName)
			dash.VerifyFatal(err, nil, "dataexport CR validation.")
		})

		// 8. Validate Volumebackup CR for backup in ns-mysql
		Step("Validate Volumebackup for backup in ns-mysql", func() {
			err := ValidateVolumebackup(bkpNamespaces, backupCrName)
			dash.VerifyFatal(err, nil, "dataVolume CR validation.")
		})

	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		defer func() {
			log.Infof("Unsetting BACKUP_TYPE env variable")
			err := os.Unsetenv("BACKUP_TYPE")
			log.FailOnError(err, "Unsetting BACKUP_TYPE env variable")
		}()

		log.InfoD("Deleting the deployed apps after the testcase")
		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		DestroyApps(scheduledAppContexts, opts)

		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)

	})
})

// Trying to restore from a generic backup which is already getting deleted. Restore option should not be available to the user.
var _ = Describe("{ValidateRestoreAfterDeleteKDMPBackup}", Label(TestCaseLabelsMap[KDMPBackup]...), func() {

	var (
		scheduledAppContexts []*scheduler.Context
		bkpNamespaces        []string
		clusterUid           string
		clusterStatus        api.ClusterInfo_StatusInfo_Status
		backupName           string
		backupLocationUID    string
		cloudCredName        string
		cloudCredUID         string
		bkpLocationName      string
		backupNames          []string
		providers            []string
		ctx                  context.Context
		backupLocationMap    map[string]string
	)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyValidateRestoreAfterDeleteKDMPBackup", "Trying to restore from a generic backup which is already getting deleted. Restore option should not be available to the user.", nil, 300201, Pingle, Q3FY25)

		backupLocationMap = make(map[string]string)
		bkpNamespaces = make([]string, 0)
		backupNames = make([]string, 0)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
	})

	// Trying to restore from a generic backup which is already getting deleted.
	It("Trying to restore from a generic backup which is already getting deleted.", func() {
		numOfBackup := 1
		backupDriver := Inst().Backup
		// 1. validate application
		Step("Validate applications", func() {
			log.InfoD("Validating applications")
			ValidateApplications(scheduledAppContexts)
		})

		// 2. common initializations
		Step("common init", func() {
			var err error
			ctx, err = backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")

			providers = GetBackupProviders()
		})

		// 3. Create cloud credentials and backup location
		Step("Creating cloud credentials and backup location", func() {
			log.InfoD("Creating cloud credentials and backup location")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cloudcred", provider, time.Now().Unix())
				bkpLocationName = fmt.Sprintf("%s-%s-%v-bl", provider, getGlobalBucketName(provider), time.Now().Unix())
				cloudCredUID = uuid.New()
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				err = CreateBackupLocation(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		// 4. Create application cluster for backup
		Step("Register cluster for backup", func() {
			err := CreateApplicationClusters(BackupOrgID, "", "", ctx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, ctx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = Inst().Backup.GetClusterUID(ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
			log.InfoD("Uid of [%s] cluster is %s", SourceClusterName, clusterUid)
		})

		// 5. Take the backup of bkNamespaces.
		Step("Taking backup of applications", func() {
			for i := 0; i < numOfBackup; i++ {
				backupName = fmt.Sprintf("%s-%s-%v", BackupNamePrefix, bkpNamespaces[0], time.Now().Unix())
				params := map[string]string{"backupName": backupName, "backupOrgID": BackupOrgID, "bkpLocationName": bkpLocationName, "backupLocationUID": backupLocationUID, "clusterName": SourceClusterName, "clusterUid": clusterUid}
				bkpCreateRequest, err := PrepareGenericBackupRequest(params)
				dash.VerifyFatal(err, nil, fmt.Sprintf("decorating data of KDMP backup [%s]", backupName))
				bkpCreateRequest.Namespaces = bkpNamespaces
				log.InfoD("Backup without check [%s] started at [%s]", backupName, time.Now().Format("2006-01-02 15:04:05"))
				_, err = backupDriver.CreateBackup(ctx, bkpCreateRequest)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of KDMP backup [%s]", backupName))
				err = Inst().Backup.WaitForBackupCompletion(ctx, backupName, BackupOrgID, BackupRestoreCompletionTimeoutMin*time.Minute, RetrySeconds*time.Second)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Waiting for [%s] completion", backupName))
				backupNames = append(backupNames, backupName)
			}
		})

		// 6. Delete the backup
		Step("Delete the backup", func() {
			log.Infof("About to delete backup - %s", backupName)
			backupUID, err := backupDriver.GetBackupUID(ctx, backupName, BackupOrgID)
			log.FailOnError(err, "Failed while trying to get backup UID for - %s", backupName)
			_, err = DeleteBackup(backupName, backupUID, BackupOrgID, ctx)
			log.FailOnError(err, "Failed to issue delete backup for - %s", backupName)
		})

		Step("Restore the backup", func() {
			userDestClusterUid, err := Inst().Backup.GetClusterUID(ctx, BackupOrgID, DestinationClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", DestinationClusterName))
			restoreName := fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			appContextsToBackup := FilterAppContextsByNamespace(scheduledAppContexts, bkpNamespaces)
			err = CreateRestoreWithValidation(ctx, restoreName, backupNames[0], make(map[string]string), make(map[string]string), DestinationClusterName, userDestClusterUid, BackupOrgID, appContextsToBackup)
			dash.VerifyNotNilFatal(err, fmt.Sprintf("Validation of Restore [%s] ", restoreName))
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		defer func() {
			log.Infof("Unsetting BACKUP_TYPE env variable")
			err := os.Unsetenv("BACKUP_TYPE")
			log.FailOnError(err, "Unsetting BACKUP_TYPE env variable")
		}()

		log.InfoD("Deleting the deployed apps after the testcase")
		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		DestroyApps(scheduledAppContexts, opts)

		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)

	})
})

// Verify the Cloud File missing Job should never be older than 10 mins old. and no accumulation of PVC & PV of the older job should be there.
var _ = Describe("{ValidateCloudFileMissingJobAgeAndPVC}", Label(TestCaseLabelsMap[KDMPBackup]...), func() {

	var (
		scheduledAppContexts  []*scheduler.Context
		s3CloudCredName       string
		s3CloudCredUID        string
		nfsBackupLocationName string
		nfsBackupLocationUID  string
		backupLocationMap     map[string]string
		bkpNamespaces         []string
		providers             []string
		backupNames           []string
		clusterUid            string
		err                   error
		ctx                   context.Context
	)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyValidateCloudFileMissingJobAgeAndPVC", "Verify the Cloud File missing Job should never be older than 10 mins old. and no accumulation of PVC & PV of the older job should be there.", nil, 300406, Pingle, Q3FY24)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)
		backupNames = make([]string, 0)
		backupLocationMap = make(map[string]string)
		log.InfoD("Scheduling Applications")
		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, appCtx := range appContexts {
			appCtx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(appCtx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, appCtx)
		}
		providers = GetBackupProviders()
	})

	// Verify the Cloud File missing Job should never be older than 10 mins old. and no accumulation of PVC & PV of the older job should be there.
	It("Verify the Cloud File missing Job should never be older than 10 mins old. and no accumulation of PVC & PV of the older job should be there", func() {
		numOfBackup := 1

		Step("Validate applications", func() {
			log.InfoD("Validating applications")
			ValidateApplications(scheduledAppContexts)
		})

		Step("common init", func() {
			ctx, err = backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
		})

		Step("Creating cloud setting and nfs backup locations", func() {
			log.InfoD("Creating cloud setting and nfs backup locations")
			for _, provider := range providers {
				log.InfoD("Creating NFS backup location")
				nfsBackupLocationName = fmt.Sprintf("%s-%s-%v", "nfs", getGlobalBucketName(drivers.ProviderNfs), RandomString(6))
				nfsBackupLocationUID = uuid.New()
				backupLocationMap[nfsBackupLocationUID] = nfsBackupLocationName
				err = CreateNFSBackupLocation(nfsBackupLocationName, nfsBackupLocationUID, BackupOrgID, " ", getGlobalBucketName(provider), true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of NFS backup location [%s]", nfsBackupLocationName))

				log.InfoD("Creating cloud credentials")
				s3CloudCredName = fmt.Sprintf("%s-%s-%v", "cred", "s3", RandomString(4))
				s3CloudCredUID = uuid.New()
				err = CreateCloudCredential("aws", s3CloudCredName, s3CloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, "Verifying creation of cloud credential ")
			}
		})

		// 4. Create application cluster for backup
		Step("Register cluster for backup", func() {
			err := CreateApplicationClusters(BackupOrgID, "", "", ctx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err := Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, ctx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = Inst().Backup.GetClusterUID(ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
			log.InfoD("Uid of [%s] cluster is %s", SourceClusterName, clusterUid)
		})

		Step("Taking backups of application NFS backup location", func() {
			log.InfoD("Taking alternate backups of application from source cluster to both S3 and NFS backup locations")
			appContextsToBackup := FilterAppContextsByNamespace(scheduledAppContexts, bkpNamespaces)
			for i := 0; i < numOfBackup; i++ {
				for locationUID, locationName := range backupLocationMap {
					log.InfoD("Creating backup using the backup location of [%s]", locationName)
					backupName := fmt.Sprintf("%s-%v", BackupNamePrefix, RandomString(10))
					backupNames = append(backupNames, backupName)

					err = CreateBackupWithValidation(ctx, backupName, SourceClusterName, locationName, locationUID, appContextsToBackup, nil, BackupOrgID, clusterUid, "", "", "", "")
					dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of backup [%s]", backupName))
					log.InfoD("Verifying the type of backup")
				}
			}
			log.Infof("List of backups - %v", backupNames)
		})

		Step("validate job and pvc is present", func() {
			err := CheckPxJobLifeForNFSCreation()
			dash.VerifyFatal(err, nil, "Verifying job creation ")
			err = CheckPvcLifeForNFSCreation()
			dash.VerifyFatal(err, nil, "Verifying pvc creation ")
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		// Clean up the cluster
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		CleanupCloudSettingsAndClusters(nil, "", "", ctx)

	})
})

// Once a object is selected for deletion, check if a job pod is created on the PX-Backup cluster
var _ = Describe("{ValidatPxBackupDeletionJobPodRunning}", Label(TestCaseLabelsMap[PxBackupLabel]...), func() {

	var (
		scheduledAppContexts []*scheduler.Context
		bkpNamespaces        []string
		clusterUid           string
		clusterStatus        api.ClusterInfo_StatusInfo_Status
		backupName           string
		backupLocationUID    string
		cloudCredName        string
		cloudCredUID         string
		bkpLocationName      string
		backupNames          []string
		providers            []string
		ctx                  context.Context
		backupLocationMap    map[string]string
		backupDriver         backup.Driver
		crUid                string
	)

	JustBeforeEach(func() {
		StartPxBackupTorpedoTest("VerifyValidatPxBackupDeletionJobPodRunning", "Once a object is selected for deletion, check if a job pod is created on the PX-Backup cluster", nil, 300189, Pingle, Q3FY25)

		backupLocationMap = make(map[string]string)
		bkpNamespaces = make([]string, 0)
		backupNames = make([]string, 0)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}
	})

	//Once a object is selected for deletion, check if a job pod is created on the PX-Backup cluster
	It("Once a object is selected for deletion, check if a job pod is created on the PX-Backup cluster.", func() {
		numOfBackup := 1
		// 1. validate application
		Step("Validate applications", func() {
			log.InfoD("Validating applications")
			ValidateApplications(scheduledAppContexts)
		})

		// 2. common initializations
		Step("common init", func() {
			backupDriver = Inst().Backup
			var err error
			ctx, err = backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")

			providers = GetBackupProviders()
		})

		// 3. Create cloud credentials and backup location
		Step("Creating cloud credentials and backup location", func() {
			log.InfoD("Creating cloud credentials and backup location")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cloudcred", provider, time.Now().Unix())
				bkpLocationName = fmt.Sprintf("%s-%s-%v-bl", provider, getGlobalBucketName(provider), time.Now().Unix())
				cloudCredUID = uuid.New()
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
				err = CreateBackupLocation(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		// 4. Create application cluster for backup
		Step("Register cluster for backup", func() {
			err := CreateApplicationClusters(BackupOrgID, "", "", ctx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, ctx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = Inst().Backup.GetClusterUID(ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
			log.InfoD("Uid of [%s] cluster is %s", SourceClusterName, clusterUid)
		})

		// 5. Take the kdmp backup of bkNamespaces.
		Step("Taking backup of applications", func() {
			for i := 0; i < numOfBackup; i++ {
				backupName = fmt.Sprintf("%s-%s-%v", BackupNamePrefix, bkpNamespaces[0], time.Now().Unix())
				params := map[string]string{"backupName": backupName, "backupOrgID": BackupOrgID, "bkpLocationName": bkpLocationName, "backupLocationUID": backupLocationUID, "clusterName": SourceClusterName, "clusterUid": clusterUid}
				bkpCreateRequest, err := PrepareGenericBackupRequest(params)
				dash.VerifyFatal(err, nil, fmt.Sprintf("decorating data of KDMP backup [%s]", backupName))
				bkpCreateRequest.Namespaces = bkpNamespaces
				log.InfoD("Backup without check [%s] started at [%s]", backupName, time.Now().Format("2006-01-02 15:04:05"))
				_, err = backupDriver.CreateBackup(ctx, bkpCreateRequest)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creation and Validation of KDMP backup [%s]", backupName))
				err = Inst().Backup.WaitForBackupCompletion(ctx, backupName, BackupOrgID, BackupRestoreCompletionTimeoutMin*time.Minute, RetrySeconds*time.Second)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Waiting for [%s] completion", backupName))
				backupNames = append(backupNames, backupName)
			}
		})

		// 6. Get the backup cr uid from backup object
		Step("Get the backup cr uid from backup object", func() {
			bkpEnumerateReq := &api.BackupEnumerateRequest{OrgId: BackupOrgID}
			enumerateRsp, err := backupDriver.EnumerateBackup(ctx, bkpEnumerateReq)
			dash.VerifyFatal(err, nil, "Backup enumeration for the ctx")
			log.Infof("crid is:%d", enumerateRsp.GetBackups()[0].CrUid[0:7])

			crUid = enumerateRsp.GetBackups()[0].CrUid[0:7]
		})

		// 6. Delete the backup
		Step("Delete the backup", func() {
			log.Infof("About to delete backup - %s", backupName)
			backupUID, err := backupDriver.GetBackupUID(ctx, backupName, BackupOrgID)
			log.FailOnError(err, "Failed while trying to get backup UID for - %s", backupName)
			_, err = DeleteBackup(backupName, backupUID, BackupOrgID, ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying backup deletion : %v", backupName))
		})

		// 7. Check if job pod is getting created
		Step("Verify the px-backup delete job pod is created", func() {
			jobPodName := PxBackupDeleteJobPrifix + crUid
			namespace, err := backup.GetPxBackupNamespace()
			dash.VerifyFatal(err, nil, "Verifing the px-backup namespace")
			expectedState := corev1.PodSucceeded

			err = ValidatePodInNamespace(jobPodName, namespace, expectedState)
			dash.VerifyFatal(err, nil, "Verifing the px-backup delete job pod is created and completed.")
		})

	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		defer func() {
			log.Infof("Unsetting BACKUP_TYPE env variable")
			err := os.Unsetenv("BACKUP_TYPE")
			log.FailOnError(err, "Unsetting BACKUP_TYPE env variable")
		}()

		log.InfoD("Deleting the deployed apps after the testcase")
		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		DestroyApps(scheduledAppContexts, opts)

		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)

	})
})
