package tests

import (
	"context"
	"fmt"
	"time"

	. "github.com/onsi/ginkgo/v2"
	"github.com/pborman/uuid"
	api "github.com/portworx/px-backup-api/pkg/apis/v1"
	"github.com/pure-px/torpedo/drivers/backup"
	"github.com/pure-px/torpedo/drivers/scheduler"
	"github.com/pure-px/torpedo/pkg/log"
	. "github.com/pure-px/torpedo/tests"
)

var _ = Describe("{BackupScheduleEnumerate}", Ordered, Label(TestCaseLabelsMap[BackupScheduleEnumerate]...), func() {
	var (
		scheduledAppContexts                  []*scheduler.Context
		providers                             []string = GetBackupProviders()
		bkpNamespaces                         []string
		backupScheduleList                    []string
		schedulePolicyName, schedulePolicyUid string
		cloudCredName, cloudCredUID           string
		backupLocationMap                     map[string]string
		adminContext                          context.Context
		sourceClusterUID                      string
		backupLocationUID                     string
		bkpLocationName                       string
		numberOfSchedules                     uint64
	)
	BeforeAll(func() {
		backupLocationMap = make(map[string]string)

		// Schedule an Application
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)

		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}

		// Validate the application
		ValidateApplications(scheduledAppContexts)

		// Get Admin User Context
		var err error
		adminContext, err = backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin user ctx")

		// Create Schedule Policy
		log.InfoD("Creating backup monthly schedule policy")
		schedulePolicyName = fmt.Sprintf("%s-%s", "monthly", RandomString(5))
		schedulePolicyUid = uuid.New()
		monthlySchedulePolicyInfo := Inst().Backup.CreateMonthlySchedulePolicy(1, 29, "9:20AM", 2)
		monthlyPolicyStatus := Inst().Backup.BackupSchedulePolicy(schedulePolicyName, schedulePolicyUid, BackupOrgID, monthlySchedulePolicyInfo)
		dash.VerifyFatal(monthlyPolicyStatus, nil, "Creating monthly schedule policy")

		cloudCredName, cloudCredUID = "", uuid.New()
		for _, provider := range providers {
			// Create Cloud Credential
			cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
			err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))

			// Create BackupLocation
			bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
			backupLocationUID = uuid.New()
			backupLocationMap[backupLocationUID] = bkpLocationName
			err = CreateBackupLocationWithContext(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", adminContext, true)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
		}

		// Create a cluster object with User1
		err = AddSourceCluster(adminContext)
		dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of source [%s] cluster with admin ctx", SourceClusterName))
		sourceClusterUID, err = Inst().Backup.GetClusterUID(adminContext, BackupOrgID, SourceClusterName)
		dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))

		// Create monthly backup schedule objects
		backupScheduleList = make([]string, 0)
		numberOfSchedules = 5
		for i := 0; i < int(numberOfSchedules); i++ {
			scheduleName := fmt.Sprintf("schedule-bkp-%v", RandomString(5))
			_, err := CreateScheduleBackupWithoutCheck(scheduleName, SourceClusterName, sourceClusterUID, bkpLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", schedulePolicyName, schedulePolicyUid, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of scheduled backup with schedule name [%s]", scheduleName))
			backupScheduleList = append(backupScheduleList, scheduleName)
		}
	})

	// This testcase is to verify Max Objects should return only maximum number of objects during the backupSchedule enumerate.
	It("VerifyMaxObjects", func() {
		StartPxBackupTorpedoTest("VerifyMaxObjects", "Verify maximum number of schedule objects where return during the schedule enumerate", nil, 302831, "sgajawada", Q3FY25)
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		Step("Enumerate BackupSchedule to test MaxObjects", func() {
			var maxObjects uint64 = 3
			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					MaxObjects: maxObjects,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), int(maxObjects), fmt.Sprintf("verify max objects %v in backup schedule enumerate response", maxObjects))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), numberOfSchedules, fmt.Sprintf("verify total count %v in backup schedule enumerate response", numberOfSchedules))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), false, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", false))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetBackupSchedules()[0].Name, backupScheduleList[4], fmt.Sprintf("verify initial object: %v in the response", backupScheduleList[4]))
		})
	})

	// This testcase is to verify Object Index should return only from starting index of list during the backupSchedule enumerate.
	It("VerifyStartingIndex", func() {
		StartPxBackupTorpedoTest("VerifyStartingIndex", "Verify all the objects before starting index where skipped during the schedule enumerate", nil, 302832, "sgajawada", Q3FY25)
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		Step("Enumerate BackupSchedule to test ObjectIndex", func() {
			var startingIndex uint64 = 1
			var remainingObjects int = 4

			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					ObjectIndex: startingIndex,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), remainingObjects, fmt.Sprintf("verify remaining objects %v in backup schedule enumerate response", remainingObjects))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), numberOfSchedules, fmt.Sprintf("verify total count %v in backup schedule enumerate response", numberOfSchedules))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), false, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", false))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetBackupSchedules()[0].Name, backupScheduleList[3], fmt.Sprintf("verify initial object: %v in the response", backupScheduleList[3]))
		})
	})

	// This testcase is to verify Object Index and Max Objects should return maximum objects from starting index of list during the backupSchedule enumerate.
	It("VerifyMaxObjectsWithStartingIndex", func() {
		StartPxBackupTorpedoTest("VerifyMaxObjectsWithStartingIndex", "Verify all the objects before starting index where skipped and only maximum objects where return during the schedule enumerate", nil, 302833, "sgajawada", Q3FY25)
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		Step("Enumerate BackupSchedule to test MaxObjects and ObjectIndex", func() {
			var maxObjects uint64 = 3
			var startingIndex uint64 = 2

			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					MaxObjects:  maxObjects,
					ObjectIndex: startingIndex,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), int(maxObjects), fmt.Sprintf("verify max objects %v in backup schedule enumerate response", maxObjects))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), numberOfSchedules, fmt.Sprintf("verify total count %v in backup schedule enumerate response", numberOfSchedules))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), true, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", true))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetBackupSchedules()[0].Name, backupScheduleList[2], fmt.Sprintf("verify initial object: %v in the response", backupScheduleList[2]))
		})
	})

	// This testcase is to verify name filter should return matched objects during the backupSchedule enumerate.
	It("VerifyNameFilter", func() {
		StartPxBackupTorpedoTest("VerifyNameFilter", "Verify matched objects where return during the schedule enumerate", nil, 302834, "sgajawada", Q3FY25)
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		Step("Enumerate BackupSchedule to test NameFilter", func() {
			searchString := backupScheduleList[1][:len(backupScheduleList[1])-1]
			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					NameFilter: searchString,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), 1, fmt.Sprintf("verify name matching objects %v in backup schedule enumerate response", 1))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), uint64(1), fmt.Sprintf("verify total count %v in backup schedule enumerate response", 1))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), true, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", true))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetBackupSchedules()[0].Name, backupScheduleList[1], fmt.Sprintf("verify initial object: %v in the response", backupScheduleList[2]))
		})
	})

	// This testcase is to verify name filter with object index and max objects should return maximum matched objects from starting index of list during the backupSchedule enumerate.
	It("VerifyNameFilterWithObjectIndexAndMaxObjects", func() {
		StartPxBackupTorpedoTest("VerifyNameFilterWithObjectIndexAndMaxObjects", "Verify all the matched objects before starting index where skipped and only maximum objects where return during the schedule enumerate", nil, 302835, "sgajawada", Q3FY25)
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		var newBackupScheduleList []string

		Step("Create 5 BackupSchedule Objects", func() {
			// Create monthly backup schedule objects
			newBackupScheduleList = make([]string, 0)
			for i := 0; i < 5; i++ {
				scheduleName := fmt.Sprintf("new-schedule-bkp-%v", RandomString(5))
				_, err := CreateScheduleBackupWithoutCheck(scheduleName, SourceClusterName, sourceClusterUID, bkpLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", schedulePolicyName, schedulePolicyUid, adminContext)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of scheduled backup with schedule name [%s]", scheduleName))
				newBackupScheduleList = append(newBackupScheduleList, scheduleName)
			}
		})

		Step("Enumerate BackupSchedule to test NameFilter with MaxObjects and ObjectIndex", func() {
			var maxObjects uint64 = 3
			var startingIndex uint64 = 1
			searchString := "new"

			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					MaxObjects:  maxObjects,
					ObjectIndex: startingIndex,
					NameFilter:  searchString,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), int(maxObjects), fmt.Sprintf("verify max objects %v in backup schedule enumerate response", maxObjects))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), uint64(5), fmt.Sprintf("verify total count %v in backup schedule enumerate response", 5))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), false, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", false))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetBackupSchedules()[0].Name, newBackupScheduleList[3], fmt.Sprintf("verify initial object: %v in the response", backupScheduleList[2]))
		})

		Step("Enumerate BackupSchedule Object Again", func() {
			var maxObjects uint64 = 3
			var startingIndex uint64 = 4
			searchString := "new"

			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					MaxObjects:  maxObjects,
					ObjectIndex: startingIndex,
					NameFilter:  searchString,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), 1, fmt.Sprintf("verify max objects %v in backup schedule enumerate response", 1))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), uint64(5), fmt.Sprintf("verify total count %v in backup schedule enumerate response", 5))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), true, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", true))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetBackupSchedules()[0].Name, newBackupScheduleList[0], fmt.Sprintf("verify initial object: %v in the response", backupScheduleList[2]))
		})

		Step("Cleanup", func() {
			searchString := "new"
			backupScheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
				OrgId: BackupOrgID,
				EnumerateOptions: &api.EnumerateOptions{
					NameFilter: searchString,
				},
			}
			backupScheduleEnumerateResponse, err := Inst().Backup.EnumerateBackupSchedule(adminContext, backupScheduleEnumerateRequest)
			log.FailOnError(err, "failed to enumerate backups")

			dash.VerifyFatal(len(backupScheduleEnumerateResponse.GetBackupSchedules()), 5, fmt.Sprintf("verify max objects %v in backup schedule enumerate response", 5))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetTotalCount(), uint64(5), fmt.Sprintf("verify total count %v in backup schedule enumerate response", 5))
			dash.VerifyFatal(backupScheduleEnumerateResponse.GetComplete(), true, fmt.Sprintf("verify is backup schedule enumerate response completed: %v", true))

			for _, schedule := range backupScheduleEnumerateResponse.BackupSchedules {
				err = DeleteScheduleWithUIDAndWait(schedule.Name, schedule.Uid, SourceClusterName, sourceClusterUID, BackupOrgID, adminContext)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of backup schedule [%s]", schedule))
			}
		})

	})

	AfterAll(func() {
		// Delete the backup schedules
		scheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
			OrgId: BackupOrgID,
		}
		scheduleList, err := Inst().Backup.EnumerateBackupSchedule(adminContext, scheduleEnumerateRequest)
		log.FailOnError(err, "failed to enumerate backup schedules")
		for _, schedule := range scheduleList.BackupSchedules {
			err = DeleteScheduleWithUIDAndWait(schedule.Name, schedule.Uid, SourceClusterName, sourceClusterUID, BackupOrgID, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of backup schedule [%s]", schedule))
		}

		// Delete the schedule policy
		log.InfoD("Deleting schedule policy [%s]", schedulePolicyName)
		schedulePolicyDeleteRequest := &api.SchedulePolicyDeleteRequest{
			Name:  schedulePolicyName,
			Uid:   schedulePolicyUid,
			OrgId: BackupOrgID,
		}
		_, err = Inst().Backup.DeleteSchedulePolicy(adminContext, schedulePolicyDeleteRequest)
		log.FailOnError(err, "failed to delete schedule policy [%s]", schedulePolicyName)

		// Delete the backups
		backupEnumerateRequest := &api.BackupEnumerateRequest{
			OrgId: BackupOrgID,
		}
		backupList, err := Inst().Backup.EnumerateBackup(adminContext, backupEnumerateRequest)
		log.FailOnError(err, "failed to enumerate backups")
		for _, backup := range backupList.Backups {
			err = DeleteBackupAndWaitForCompletion(backup.Name, backup.Uid, BackupOrgID, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backup))
		}

		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		log.InfoD("Deleting deployed applications")
		DestroyApps(scheduledAppContexts, opts)
		err = DeleteNamespaces(bkpNamespaces)
		log.FailOnError(err, "failed to delete namespaces")
		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, adminContext)
	})
})
