package tests

import (
	"context"
	"fmt"
	"strings"
	"time"

	. "github.com/onsi/ginkgo/v2"
	"github.com/pborman/uuid"
	api "github.com/portworx/px-backup-api/pkg/apis/v1"
	"github.com/portworx/torpedo/drivers/backup"
	"github.com/portworx/torpedo/drivers/scheduler"
	"github.com/portworx/torpedo/pkg/log"
	. "github.com/portworx/torpedo/tests"
)

var _ = Describe("{SuperAdmin}", Label(TestCaseLabelsMap[SuperAdmin]...), func() {
	var (
		scheduledAppContexts                                                 []*scheduler.Context
		providers                                                            []string = GetBackupProviders()
		bkpNamespaces                                                        []string
		testUser1Name, testUser1FirstName, testUser1LastName, testUser1Email string
		cloudCredName, cloudCredUID                                          string
		backupLocationMap                                                    map[string]string
		testUser1Ctx, adminContext                                           context.Context
		sourceClusterUID                                                     string
	)
	JustBeforeEach(func() {
		backupLocationMap = make(map[string]string)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)
		cloudCredName, cloudCredUID = "", ""
		testUser1Name = "testuser1"
		testUser1FirstName = "testUser1FirstName"
		testUser1LastName = "testUser1LastName"
		testUser1Email = "testuser1email@cnbu.com"
		cloudCredUID = uuid.New()
		sourceClusterUID = ""

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}

		// Validate the application
		ValidateApplications(scheduledAppContexts)

		// Get Admin User Context
		var err error
		adminContext, err = backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin user ctx")

		// Create testuser1
		err = backup.AddUser(testUser1Name, testUser1FirstName, testUser1LastName, testUser1Email, CommonPassword)
		log.FailOnError(err, "Failed to create user - %s", testUser1Name)

		err = backup.AddRoleToUser(testUser1Name, backup.SuperAdmin, fmt.Sprintf("Adding %v role to %s", backup.SuperAdmin, testUser1Name))
		log.FailOnError(err, "Failed to add role %s to the user %s", backup.SuperAdmin, testUser1Name)

		testUser1Ctx, err = backup.GetNonAdminCtx(testUser1Name, CommonPassword)
		log.FailOnError(err, "Fetching non admin ctx")

		// Create Cloud Credential for testuser1
		for _, provider := range providers {
			cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
			err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
		}

		// Create a cluster object with User1
		err = AddSourceCluster(testUser1Ctx)
		dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of source [%s] cluster with %s ctx", SourceClusterName, testUser1Name))
		sourceClusterUID, err = Inst().Backup.GetClusterUID(testUser1Ctx, BackupOrgID, SourceClusterName)
		dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))

	})

	It("AsSuperAdminVerifyCRUDOperationsOnBackupLocation", func() {
		// TODO: Add the testrail ID
		StartPxBackupTorpedoTest("AsSuperAdminVerifyCRUDOperationsOnBackupLocation", "As Super Admin Verify CRUD of BackupLocation", nil, 301218, Sgajawada, Q2FY25)

		var (
			backupName        = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			restoreName       = fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			namespaceMapping  = make(map[string]string)
			backupLocationUID string
			bkpLocationName   string
		)

		Step("Create BackupLocation with Admin User", func() {
			// Create BackupLocation
			for _, provider := range providers {
				bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateBackupLocationWithContext(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", adminContext, true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		Step("Create a backup and restore it on the same cluster with user1", func() {
			// Take Backup
			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err := CreateBackup(backupName, SourceClusterName, bkpLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, sourceClusterUID, "", "", "", "", testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))

			// Create Restore
			for _, namespace := range bkpNamespaces {
				restoredNameSpace := fmt.Sprintf("%s-%s", RandomString(10), "restored")
				namespaceMapping[namespace] = restoredNameSpace
			}
			log.InfoD("Namespace mapping is %v:", namespaceMapping)
			err = CreateRestore(restoreName, backupName, namespaceMapping, SourceClusterName, BackupOrgID, testUser1Ctx, make(map[string]string))
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of restore [%s]", restoreName))
		})

		Step("Check Inspect and Update operations on BackupLocation with user1", func() {
			// Inspect the backuplocation with user1
			backupLocationInspectRequest := api.BackupLocationInspectRequest{
				Name:  bkpLocationName,
				Uid:   backupLocationUID,
				OrgId: BackupOrgID,
			}
			backupLocationObject, err := Inst().Backup.InspectBackupLocation(testUser1Ctx, &backupLocationInspectRequest)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Failed to inspect backup location [%s]", bkpLocationName))

			// Update the backuplocation with user1
			backupLocationUpdateRequest := api.BackupLocationUpdateRequest{
				BackupLocation: backupLocationObject.BackupLocation.GetBackupLocationInfo(),
				CreateMetadata: &api.CreateMetadata{
					Name:      backupLocationObject.BackupLocation.GetName(),
					Uid:       backupLocationObject.BackupLocation.GetUid(),
					OrgId:     backupLocationObject.BackupLocation.GetOrgId(),
					Labels:    map[string]string{"key1": "value1"}, // new updated values
					Ownership: backupLocationObject.BackupLocation.GetOwnership(),
					Owner:     backupLocationObject.BackupLocation.GetOwner(),
				},
			}
			_, err = Inst().Backup.UpdateBackupLocation(testUser1Ctx, &backupLocationUpdateRequest)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Failed to update backup location [%s]", bkpLocationName))
		})

		Step("Cleanup", func() {
			backupDriver := Inst().Backup
			backupUID, err := backupDriver.GetBackupUID(testUser1Ctx, backupName, BackupOrgID)
			log.FailOnError(err, "Failed while trying to get backup UID for - [%s]", backupName)

			log.InfoD("Deleting backup")
			err = DeleteBackupAndWaitForCompletion(backupName, backupUID, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backupName))

			log.InfoD(fmt.Sprintf("Delete restore with name [%s]", restoreName))
			err = DeleteRestore(restoreName, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting restore [%s]", restoreName))

			// Delete the backuplocation with user1
			backupLocationDeleteRequest := api.BackupLocationDeleteRequest{
				Name:  bkpLocationName,
				Uid:   backupLocationUID,
				OrgId: BackupOrgID,
			}
			_, err = Inst().Backup.DeleteBackupLocation(testUser1Ctx, &backupLocationDeleteRequest)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Failed to delete backup location [%s]", bkpLocationName))

			// Remove the backup location UID from the map as the BL is deleted
			delete(backupLocationMap, backupLocationUID)
		})
	})

	It("AsSuperAdminVerifyCRUDOperationsOnSchedulePolicy", func() {
		// TODO: Add the testrail ID
		StartPxBackupTorpedoTest("AsSuperAdminVerifyCRUDOperationsOnSchedulePolicy", "As Super Admin Verify CRUD Schedule Policy", nil, 301217, Sgajawada, Q2FY25)

		var (
			scheduleName               string
			periodicSchedulePolicyName string
			periodicSchedulePolicyUid  string
			backupLocationUID          string
			bkpLocationName            string
		)

		Step("Create Schedule Policy with Admin User", func() {
			// Create Schedule Policy
			periodicSchedulePolicyName = fmt.Sprintf("%s-%s", "periodic", RandomString(5))
			periodicSchedulePolicyUid = uuid.New()
			periodicSchedulePolicyInterval := int64(15)
			err := CreateBackupScheduleIntervalPolicy(5, periodicSchedulePolicyInterval, 5, periodicSchedulePolicyName, periodicSchedulePolicyUid, BackupOrgID, adminContext, false, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of periodic schedule policy of interval [%v] minutes named [%s] ", periodicSchedulePolicyInterval, periodicSchedulePolicyName))
		})

		Step("Create a backup schedule with User1", func() {
			// Create BackupLocation
			for _, provider := range providers {
				bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateBackupLocationWithContext(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", testUser1Ctx, true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}

			// Take Backup Schedule
			log.InfoD("Taking schedule backup of multiple namespaces")
			scheduleName = fmt.Sprintf("schedule-bkp-%v", RandomString(5))
			_, err := CreateScheduleBackupWithoutCheck(scheduleName, SourceClusterName, bkpLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", periodicSchedulePolicyName, periodicSchedulePolicyUid, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of scheduled backup with schedule name [%s]", scheduleName))
		})

		Step("Check Inspect and Update operations on schedulePolicy with user1", func() {
			// Inspect the Schedule Policy with user1
			log.InfoD("Inspect schedule policy [%s]", periodicSchedulePolicyName)
			schedulePolicyInspectRequest := &api.SchedulePolicyInspectRequest{
				Name:  periodicSchedulePolicyName,
				Uid:   periodicSchedulePolicyUid,
				OrgId: BackupOrgID,
			}
			schedulePolicyObject, err := Inst().Backup.InspectSchedulePolicy(testUser1Ctx, schedulePolicyInspectRequest)
			log.FailOnError(err, "Failed to inspect schedule policy %s", periodicSchedulePolicyName)

			// Update the Schedule Policy with user1
			log.InfoD("Update schedule policy [%s]", periodicSchedulePolicyName)
			schedulePolicyUpdateRequest := &api.SchedulePolicyUpdateRequest{
				SchedulePolicy: schedulePolicyObject.GetSchedulePolicy().SchedulePolicyInfo,
				CreateMetadata: &api.CreateMetadata{
					Name:      schedulePolicyObject.GetSchedulePolicy().GetName(),
					Uid:       schedulePolicyObject.GetSchedulePolicy().GetUid(),
					OrgId:     schedulePolicyObject.GetSchedulePolicy().GetOrgId(),
					Labels:    map[string]string{"key1": "value1"}, // new updated values
					Ownership: schedulePolicyObject.GetSchedulePolicy().GetOwnership(),
					Owner:     schedulePolicyObject.GetSchedulePolicy().GetOwner(),
				},
			}
			_, err = Inst().Backup.UpdateSchedulePolicy(testUser1Ctx, schedulePolicyUpdateRequest)
			log.FailOnError(err, "Failed to update schedule policy %s", periodicSchedulePolicyName)
		})

		Step("Delete the backup schedule and schedulePolicy", func() {
			log.InfoD("Deleting backup schedule [%s]", scheduleName)
			scheduleUID, err := GetScheduleUID(scheduleName, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] backupschedule uid", scheduleName))

			allScheduleBackupNames, err := Inst().Backup.GetAllScheduleBackupNames(testUser1Ctx, scheduleName, BackupOrgID)
			log.FailOnError(err, "failed to get all schedule backup names with schedule name %s of the user %s", scheduleName, testUser1Name)

			err = DeleteScheduleWithUIDAndWait(scheduleName, scheduleUID, SourceClusterName, sourceClusterUID, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of backup schedule [%s]", scheduleName))

			log.InfoD("allScheduleBackupNames: %v", allScheduleBackupNames)
			for i := len(allScheduleBackupNames) - 1; i >= 0; i-- {
				backupName := allScheduleBackupNames[i]
				backupUid, err := Inst().Backup.GetBackupUID(testUser1Ctx, backupName, BackupOrgID)
				if err != nil && !strings.Contains(err.Error(), "not found") {
					log.FailOnError(err, "failed to fetch backup %s uid of the user %s", backupName, testUser1Name)
				}
				if backupUid != "" {
					err = DeleteBackupAndWaitForCompletion(backupName, backupUid, BackupOrgID, testUser1Ctx)
					log.FailOnError(err, "failed to delete schedule backup %s of the user %s", backupName, testUser1Name)
				}
			}

			// Delete the Schedule Policy with user1
			log.InfoD("Deleting schedule policy [%s]", periodicSchedulePolicyName)
			schedulePolicyDeleteRequest := &api.SchedulePolicyDeleteRequest{
				Name:  periodicSchedulePolicyName,
				Uid:   periodicSchedulePolicyUid,
				OrgId: BackupOrgID,
			}
			_, err = Inst().Backup.DeleteSchedulePolicy(testUser1Ctx, schedulePolicyDeleteRequest)
			log.FailOnError(err, "failed to delete schedule policy %s", periodicSchedulePolicyName)
		})

	})

	It("AsSuperAdminVerifyCRUDOperationsOnRules", func() {
		// TODO: Add the testrail ID
		StartPxBackupTorpedoTest("AsSuperAdminVerifyCRUDOperationsOnRules", "As Super Admin Verify CRUD of Rules", nil, 301219, Sgajawada, Q2FY25)

		var (
			backupName                = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			backupLocationUID         string
			bkpLocationName           string
			preRuleName, postRuleName string
			preRuleUid, postRuleUid   string
		)

		Step("Create PreExecRule and PostExecRule with Admin User", func() {
			log.InfoD("Creation of pre and post exec rules for applications ")
			var err error
			preRuleName, postRuleName, err = CreateRuleForBackupWithMultipleApplications(BackupOrgID, Inst().AppList, adminContext)
			dash.VerifyFatal(err, nil, "Verifying creation of pre and post exec rules for applications from px-admin")
			if preRuleName != "" {
				preRuleUid, err = Inst().Backup.GetRuleUid(BackupOrgID, adminContext, preRuleName)
				log.FailOnError(err, "Fetching pre backup rule [%s] uid", preRuleName)
				log.Infof("Pre backup rule [%s] uid: [%s]", preRuleName, preRuleUid)
			}
			if postRuleName != "" {
				postRuleUid, err = Inst().Backup.GetRuleUid(BackupOrgID, adminContext, postRuleName)
				log.FailOnError(err, "Fetching post backup rule [%s] uid", postRuleName)
				log.Infof("Post backup rule [%s] uid: [%s]", postRuleName, postRuleUid)
			}
		})

		Step("Create a backup and restore it on the same cluster with user1", func() {
			// Create BackupLocation
			for _, provider := range providers {
				bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateBackupLocationWithContext(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", testUser1Ctx, true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}

			// Take Backup
			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err := CreateBackup(backupName, SourceClusterName, bkpLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, sourceClusterUID, preRuleName, preRuleUid, postRuleName, postRuleUid, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))
		})

		Step("Check Inspect and Update operations on rules with user1", func() {
			labels := map[string]string{"key1": "value1"}
			if preRuleName != "" {
				err := InspectAndUpdateRuleWithLabels(testUser1Ctx, preRuleName, preRuleUid, labels)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Failed while InspectAndUpdateRuleWithLabel [%s]", preRuleName))
			}
			if postRuleName != "" {
				err := InspectAndUpdateRuleWithLabels(testUser1Ctx, postRuleName, postRuleUid, labels)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Failed while InspectAndUpdateRuleWithLabel [%s]", postRuleName))
			}
		})

		Step("Cleanup", func() {
			backupDriver := Inst().Backup
			backupUID, err := backupDriver.GetBackupUID(testUser1Ctx, backupName, BackupOrgID)
			log.FailOnError(err, "Failed while trying to get backup UID for - [%s]", backupName)

			log.InfoD("Deleting backup")
			err = DeleteBackupAndWaitForCompletion(backupName, backupUID, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backupName))

			// Delete the Rules with user1
			log.Infof("Deleting pre & post exec rules")
			if preRuleName != "" {
				err = DeleteRule(preRuleName, BackupOrgID, testUser1Ctx)
				dash.VerifySafely(err, nil, fmt.Sprintf("Verifying deletion of rule [%s]", preRuleName))
			}
			if postRuleName != "" {
				err = DeleteRule(postRuleName, BackupOrgID, testUser1Ctx)
				dash.VerifySafely(err, nil, fmt.Sprintf("Verifying deletion of rule [%s]", postRuleName))
			}
		})
	})

	It("AsSuperAdminVerifyCRUDOperationsOnRoles ", func() {
		// TODO: Add the testrail ID
		StartPxBackupTorpedoTest("AsSuperAdminVerifyCRUDOperationsOnRoles", "As Super Admin verify CRUD operation of Roles ", nil, 301220, Sgajawada, Q2FY25)

		Step("Add Keycloack roles to testuser1", func() {
			err := backup.AddRoleToUser(testUser1Name, backup.DefaultRoles, fmt.Sprintf("Adding %v role to %s", backup.DefaultRoles, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.DefaultRoles, testUser1Name)

			err = backup.AddRoleToUser(testUser1Name, backup.Admin, fmt.Sprintf("Adding %v role to %s", backup.Admin, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.Admin, testUser1Name)

			err = backup.AddRoleToUser(testUser1Name, backup.SystemAdmin, fmt.Sprintf("Adding %v role to %s", backup.SystemAdmin, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.SystemAdmin, testUser1Name)
		})

		var (
			testUser2Name, testUser2FirstName, testUser2LastName, testUser2Email string
			testUser2Ctx                                                         context.Context
			backupLocationUID                                                    string
			bkpLocationName                                                      string
			customRoleName                                                       = backup.PxBackupRole(fmt.Sprintf("custom-role-%s", RandomString(4)))
		)

		Step("Create Custom app.User Role with Admin User", func() {
			services := []RoleServices{BackupSchedulePolicy, Rules, Cloudcredential, BackupLocation, Role}
			apis := []RoleApis{Inspect, Enumerate, Validate}
			err := CreateRole(customRoleName, services, apis, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of role [%s] by the %v user", customRoleName, "admin"))
		})

		Step("Update the Custom Role with infra.admin using user1", func() {
			services := []RoleServices{BackupSchedulePolicy, Rules, Cloudcredential, BackupLocation, Role}
			apis := []RoleApis{All}
			err := UpdateRole(customRoleName, services, apis, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying update of role [%s] by the %v user", customRoleName, testUser1Name))
		})

		Step("Login as User1 and Create User2 with custom role", func() {
			// Create testuser2
			testUser2Name = "testuser2"
			testUser2FirstName = "testUser2FirstName"
			testUser2LastName = "testUser2LastName"
			testUser2Email = "testuser2email@cnbu.com"

			err := backup.AddUser(testUser2Name, testUser2FirstName, testUser2LastName, testUser2Email, CommonPassword)
			log.FailOnError(err, "Failed to create user - %s", testUser2Name)

			err = backup.AddRoleToUserWithCredentials(testUser2Name, customRoleName, fmt.Sprintf("Adding %v role to %s", customRoleName, testUser2Name), testUser1Name, CommonPassword)
			log.FailOnError(err, "Failed to add role %s to the user %s", customRoleName, testUser2Name)

			testUser2Ctx, err = backup.GetNonAdminCtx(testUser2Name, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")
		})

		Step("Create a backup with user2", func() {
			// Share the Cloud Credential with user2
			err := AddCloudCredentialOwnership(cloudCredName, cloudCredUID, []string{testUser2Name}, nil, Read, Invalid, testUser1Ctx, BackupOrgID)
			log.FailOnError(err, "Sharing CloudCredential Object %s with user2", cloudCredName)

			// Create BackupLocation
			for _, provider := range providers {
				bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateBackupLocationWithContext(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", testUser2Ctx, true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		Step("Cleanup", func() {
			err := backup.DeleteUser(testUser2Name)
			log.FailOnError(err, "Failed to delete user - %s", testUser2Name)

			log.Infof("Verify deletion of role [%s] created by user [%s] ", customRoleName, "admin")
			err = DeleteRole(customRoleName, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of role [%s] created by user  %s", customRoleName, testUser1Name))

			err = backup.DeleteRoleFromUser(testUser1Name, backup.DefaultRoles, fmt.Sprintf("delete %v role from %s", backup.DefaultRoles, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.DefaultRoles, testUser1Name)

			err = backup.DeleteRoleFromUser(testUser1Name, backup.Admin, fmt.Sprintf("delete %v role from %s", backup.Admin, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.Admin, testUser1Name)

			err = backup.DeleteRoleFromUser(testUser1Name, backup.SystemAdmin, fmt.Sprintf("delete %v role from %s", backup.SystemAdmin, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.SystemAdmin, testUser1Name)
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		err := DeleteClusterWithUID(SourceClusterName, sourceClusterUID, BackupOrgID, testUser1Ctx, false)
		dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting Cluster [%s]", SourceClusterName))

		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		log.InfoD("Deleting deployed applications")
		DestroyApps(scheduledAppContexts, opts)

		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, adminContext)

		err = backup.DeleteUser(testUser1Name)
		log.FailOnError(err, "Failed to delete user - %s", testUser1Name)
	})
})
