package tests

import (
	"context"
	"fmt"
	"strings"
	"time"

	. "github.com/onsi/ginkgo/v2"
	"github.com/pborman/uuid"
	api "github.com/portworx/px-backup-api/pkg/apis/v1"
	"github.com/portworx/torpedo/drivers"
	"github.com/portworx/torpedo/drivers/backup"
	"github.com/portworx/torpedo/drivers/scheduler"
	"github.com/portworx/torpedo/pkg/log"
	. "github.com/portworx/torpedo/tests"
)

var _ = Describe("{SuperAdmin}", Label(TestCaseLabelsMap[SuperAdmin]...), func() {
	var (
		scheduledAppContexts                                                 []*scheduler.Context
		providers                                                            []string = GetBackupProviders()
		bkpNamespaces                                                        []string
		testUser1Name, testUser1FirstName, testUser1LastName, testUser1Email string
		cloudCredName, cloudCredUID                                          string
		backupLocationMap                                                    map[string]string
		testUser1Ctx, adminContext                                           context.Context
		sourceClusterUID                                                     string
	)
	JustBeforeEach(func() {
		backupLocationMap = make(map[string]string)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)
		cloudCredName, cloudCredUID = "", ""
		testUser1Name = "testuser1"
		testUser1FirstName = "testUser1FirstName"
		testUser1LastName = "testUser1LastName"
		testUser1Email = "testuser1email@cnbu.com"
		cloudCredUID = uuid.New()
		sourceClusterUID = ""

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}

		// Validate the application
		ValidateApplications(scheduledAppContexts)

		// Get Admin User Context
		var err error
		adminContext, err = backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin user ctx")

		// Create testuser1
		err = backup.AddUser(testUser1Name, testUser1FirstName, testUser1LastName, testUser1Email, CommonPassword)
		log.FailOnError(err, "Failed to create user - %s", testUser1Name)

		err = backup.AddRoleToUser(testUser1Name, backup.SuperAdmin, fmt.Sprintf("Adding %v role to %s", backup.SuperAdmin, testUser1Name))
		log.FailOnError(err, "Failed to add role %s to the user %s", backup.SuperAdmin, testUser1Name)

		testUser1Ctx, err = backup.GetNonAdminCtx(testUser1Name, CommonPassword)
		log.FailOnError(err, "Fetching non admin ctx")

		// Create Cloud Credential for testuser1
		for _, provider := range providers {
			cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
			err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
		}

		// Create a cluster object with User1
		err = AddSourceCluster(testUser1Ctx)
		dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of source [%s] cluster with %s ctx", SourceClusterName, testUser1Name))
		sourceClusterUID, err = Inst().Backup.GetClusterUID(testUser1Ctx, BackupOrgID, SourceClusterName)
		dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))

	})

	It("AsSuperAdminVerifyCRUDOperationsOnBackupLocation", func() {
		StartPxBackupTorpedoTest("AsSuperAdminVerifyCRUDOperationsOnBackupLocation", "As Super Admin Verify CRUD of BackupLocation", nil, 301218, Sgajawada, Q2FY25)

		var (
			backupName        = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			restoreName       = fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			namespaceMapping  = make(map[string]string)
			backupLocationUID string
			bkpLocationName   string
		)

		Step("Create BackupLocation with Admin User", func() {
			// Create BackupLocation
			for _, provider := range providers {
				bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateBackupLocationWithContext(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", adminContext, true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		Step("Create a backup and restore it on the same cluster with user1", func() {
			// Take Backup
			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err := CreateBackup(backupName, SourceClusterName, bkpLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, sourceClusterUID, "", "", "", "", testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))

			// Create Restore
			for _, namespace := range bkpNamespaces {
				restoredNameSpace := fmt.Sprintf("%s-%s", RandomString(10), "restored")
				namespaceMapping[namespace] = restoredNameSpace
			}
			log.InfoD("Namespace mapping is %v:", namespaceMapping)
			err = CreateRestore(restoreName, backupName, namespaceMapping, SourceClusterName, sourceClusterUID, BackupOrgID, testUser1Ctx, make(map[string]string))
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of restore [%s]", restoreName))
		})

		Step("Check Inspect and Update operations on BackupLocation with user1", func() {
			// Inspect the backuplocation with user1
			backupLocationInspectRequest := api.BackupLocationInspectRequest{
				Name:  bkpLocationName,
				Uid:   backupLocationUID,
				OrgId: BackupOrgID,
			}
			backupLocationObject, err := Inst().Backup.InspectBackupLocation(testUser1Ctx, &backupLocationInspectRequest)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Failed to inspect backup location [%s]", bkpLocationName))

			// Update the backuplocation with user1
			backupLocationUpdateRequest := api.BackupLocationUpdateRequest{
				BackupLocation: backupLocationObject.BackupLocation.GetBackupLocationInfo(),
				CreateMetadata: &api.CreateMetadata{
					Name:      backupLocationObject.BackupLocation.GetName(),
					Uid:       backupLocationObject.BackupLocation.GetUid(),
					OrgId:     backupLocationObject.BackupLocation.GetOrgId(),
					Labels:    map[string]string{"key1": "value1"}, // new updated values
					Ownership: backupLocationObject.BackupLocation.GetOwnership(),
					Owner:     backupLocationObject.BackupLocation.GetOwner(),
				},
			}
			_, err = Inst().Backup.UpdateBackupLocation(testUser1Ctx, &backupLocationUpdateRequest)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Failed to update backup location [%s]", bkpLocationName))
		})

		Step("Cleanup", func() {
			backupDriver := Inst().Backup
			backupUID, err := backupDriver.GetBackupUID(testUser1Ctx, backupName, BackupOrgID)
			log.FailOnError(err, "Failed while trying to get backup UID for - [%s]", backupName)

			log.InfoD("Deleting backup")
			err = DeleteBackupAndWaitForCompletion(backupName, backupUID, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backupName))

			log.InfoD(fmt.Sprintf("Delete restore with name [%s]", restoreName))
			err = DeleteRestore(restoreName, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting restore [%s]", restoreName))

			// Delete the backuplocation with user1
			backupLocationDeleteRequest := api.BackupLocationDeleteRequest{
				Name:  bkpLocationName,
				Uid:   backupLocationUID,
				OrgId: BackupOrgID,
			}
			_, err = Inst().Backup.DeleteBackupLocation(testUser1Ctx, &backupLocationDeleteRequest)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Failed to delete backup location [%s]", bkpLocationName))

			// Remove the backup location UID from the map as the BL is deleted
			delete(backupLocationMap, backupLocationUID)
		})
	})

	It("AsSuperAdminVerifyCRUDOperationsOnSchedulePolicy", func() {
		StartPxBackupTorpedoTest("AsSuperAdminVerifyCRUDOperationsOnSchedulePolicy", "As Super Admin Verify CRUD Schedule Policy", nil, 301217, Sgajawada, Q2FY25)

		var (
			scheduleName               string
			periodicSchedulePolicyName string
			periodicSchedulePolicyUid  string
			backupLocationUID          string
			bkpLocationName            string
		)

		Step("Create Schedule Policy with Admin User", func() {
			// Create Schedule Policy
			periodicSchedulePolicyName = fmt.Sprintf("%s-%s", "periodic", RandomString(5))
			periodicSchedulePolicyUid = uuid.New()
			periodicSchedulePolicyInterval := int64(15)
			err := CreateBackupScheduleIntervalPolicy(5, periodicSchedulePolicyInterval, 5, periodicSchedulePolicyName, periodicSchedulePolicyUid, BackupOrgID, adminContext, false, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of periodic schedule policy of interval [%v] minutes named [%s] ", periodicSchedulePolicyInterval, periodicSchedulePolicyName))
		})

		Step("Create a backup schedule with User1", func() {
			// Create BackupLocation
			for _, provider := range providers {
				bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateBackupLocationWithContext(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", testUser1Ctx, true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}

			// Take Backup Schedule
			log.InfoD("Taking schedule backup of multiple namespaces")
			scheduleName = fmt.Sprintf("schedule-bkp-%v", RandomString(5))
			_, err := CreateScheduleBackupWithoutCheck(scheduleName, SourceClusterName, sourceClusterUID, bkpLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", periodicSchedulePolicyName, periodicSchedulePolicyUid, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of scheduled backup with schedule name [%s]", scheduleName))
		})

		Step("Check Inspect and Update operations on schedulePolicy with user1", func() {
			// Inspect the Schedule Policy with user1
			log.InfoD("Inspect schedule policy [%s]", periodicSchedulePolicyName)
			schedulePolicyInspectRequest := &api.SchedulePolicyInspectRequest{
				Name:  periodicSchedulePolicyName,
				Uid:   periodicSchedulePolicyUid,
				OrgId: BackupOrgID,
			}
			schedulePolicyObject, err := Inst().Backup.InspectSchedulePolicy(testUser1Ctx, schedulePolicyInspectRequest)
			log.FailOnError(err, "Failed to inspect schedule policy %s", periodicSchedulePolicyName)

			// Update the Schedule Policy with user1
			log.InfoD("Update schedule policy [%s]", periodicSchedulePolicyName)
			schedulePolicyUpdateRequest := &api.SchedulePolicyUpdateRequest{
				SchedulePolicy: schedulePolicyObject.GetSchedulePolicy().SchedulePolicyInfo,
				CreateMetadata: &api.CreateMetadata{
					Name:      schedulePolicyObject.GetSchedulePolicy().GetName(),
					Uid:       schedulePolicyObject.GetSchedulePolicy().GetUid(),
					OrgId:     schedulePolicyObject.GetSchedulePolicy().GetOrgId(),
					Labels:    map[string]string{"key1": "value1"}, // new updated values
					Ownership: schedulePolicyObject.GetSchedulePolicy().GetOwnership(),
					Owner:     schedulePolicyObject.GetSchedulePolicy().GetOwner(),
				},
			}
			_, err = Inst().Backup.UpdateSchedulePolicy(testUser1Ctx, schedulePolicyUpdateRequest)
			log.FailOnError(err, "Failed to update schedule policy %s", periodicSchedulePolicyName)
		})

		Step("Delete the backup schedule and schedulePolicy", func() {
			log.InfoD("Deleting backup schedule [%s]", scheduleName)
			scheduleUID, err := GetScheduleUID(scheduleName, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] backupschedule uid", scheduleName))

			allScheduleBackupNames, err := Inst().Backup.GetAllScheduleBackupNames(testUser1Ctx, scheduleName, BackupOrgID)
			log.FailOnError(err, "failed to get all schedule backup names with schedule name %s of the user %s", scheduleName, testUser1Name)

			err = DeleteScheduleWithUIDAndWait(scheduleName, scheduleUID, SourceClusterName, sourceClusterUID, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of backup schedule [%s]", scheduleName))

			log.InfoD("allScheduleBackupNames: %v", allScheduleBackupNames)
			for i := len(allScheduleBackupNames) - 1; i >= 0; i-- {
				backupName := allScheduleBackupNames[i]
				backupUid, err := Inst().Backup.GetBackupUID(testUser1Ctx, backupName, BackupOrgID)
				if err != nil && !strings.Contains(err.Error(), "not found") {
					log.FailOnError(err, "failed to fetch backup %s uid of the user %s", backupName, testUser1Name)
				}
				if backupUid != "" {
					err = DeleteBackupAndWaitForCompletion(backupName, backupUid, BackupOrgID, testUser1Ctx)
					log.FailOnError(err, "failed to delete schedule backup %s of the user %s", backupName, testUser1Name)
				}
			}

			// Delete the Schedule Policy with user1
			log.InfoD("Deleting schedule policy [%s]", periodicSchedulePolicyName)
			schedulePolicyDeleteRequest := &api.SchedulePolicyDeleteRequest{
				Name:  periodicSchedulePolicyName,
				Uid:   periodicSchedulePolicyUid,
				OrgId: BackupOrgID,
			}
			_, err = Inst().Backup.DeleteSchedulePolicy(testUser1Ctx, schedulePolicyDeleteRequest)
			log.FailOnError(err, "failed to delete schedule policy %s", periodicSchedulePolicyName)
		})

	})

	It("AsSuperAdminVerifyCRUDOperationsOnRules", func() {
		StartPxBackupTorpedoTest("AsSuperAdminVerifyCRUDOperationsOnRules", "As Super Admin Verify CRUD of Rules", nil, 301219, Sgajawada, Q2FY25)

		var (
			backupName                = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			backupLocationUID         string
			bkpLocationName           string
			preRuleName, postRuleName string
			preRuleUid, postRuleUid   string
		)

		Step("Create PreExecRule and PostExecRule with Admin User", func() {
			log.InfoD("Creation of pre and post exec rules for applications ")
			var err error
			preRuleName, postRuleName, err = CreateRuleForBackupWithMultipleApplications(BackupOrgID, Inst().AppList, adminContext)
			dash.VerifyFatal(err, nil, "Verifying creation of pre and post exec rules for applications from px-admin")
			if preRuleName != "" {
				preRuleUid, err = Inst().Backup.GetRuleUid(BackupOrgID, adminContext, preRuleName)
				log.FailOnError(err, "Fetching pre backup rule [%s] uid", preRuleName)
				log.Infof("Pre backup rule [%s] uid: [%s]", preRuleName, preRuleUid)
			}
			if postRuleName != "" {
				postRuleUid, err = Inst().Backup.GetRuleUid(BackupOrgID, adminContext, postRuleName)
				log.FailOnError(err, "Fetching post backup rule [%s] uid", postRuleName)
				log.Infof("Post backup rule [%s] uid: [%s]", postRuleName, postRuleUid)
			}
		})

		Step("Create a backup and restore it on the same cluster with user1", func() {
			// Create BackupLocation
			for _, provider := range providers {
				bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateBackupLocationWithContext(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", testUser1Ctx, true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}

			// Take Backup
			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err := CreateBackup(backupName, SourceClusterName, bkpLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, sourceClusterUID, preRuleName, preRuleUid, postRuleName, postRuleUid, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))
		})

		Step("Check Inspect and Update operations on rules with user1", func() {
			labels := map[string]string{"key1": "value1"}
			if preRuleName != "" {
				err := InspectAndUpdateRuleWithLabels(testUser1Ctx, preRuleName, preRuleUid, labels)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Failed while InspectAndUpdateRuleWithLabel [%s]", preRuleName))
			}
			if postRuleName != "" {
				err := InspectAndUpdateRuleWithLabels(testUser1Ctx, postRuleName, postRuleUid, labels)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Failed while InspectAndUpdateRuleWithLabel [%s]", postRuleName))
			}
		})

		Step("Cleanup", func() {
			backupDriver := Inst().Backup
			backupUID, err := backupDriver.GetBackupUID(testUser1Ctx, backupName, BackupOrgID)
			log.FailOnError(err, "Failed while trying to get backup UID for - [%s]", backupName)

			log.InfoD("Deleting backup")
			err = DeleteBackupAndWaitForCompletion(backupName, backupUID, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backupName))

			// Delete the Rules with user1
			log.Infof("Deleting pre & post exec rules")
			if preRuleName != "" {
				err = DeleteRule(preRuleName, BackupOrgID, testUser1Ctx)
				dash.VerifySafely(err, nil, fmt.Sprintf("Verifying deletion of rule [%s]", preRuleName))
			}
			if postRuleName != "" {
				err = DeleteRule(postRuleName, BackupOrgID, testUser1Ctx)
				dash.VerifySafely(err, nil, fmt.Sprintf("Verifying deletion of rule [%s]", postRuleName))
			}
		})
	})

	It("AsSuperAdminVerifyCRUDOperationsOnRoles ", func() {
		StartPxBackupTorpedoTest("AsSuperAdminVerifyCRUDOperationsOnRoles", "As Super Admin verify CRUD operation of Roles ", nil, 301220, Sgajawada, Q2FY25)

		Step("Add Keycloack roles to testuser1", func() {
			err := backup.AddRoleToUser(testUser1Name, backup.DefaultRoles, fmt.Sprintf("Adding %v role to %s", backup.DefaultRoles, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.DefaultRoles, testUser1Name)

			err = backup.AddRoleToUser(testUser1Name, backup.Admin, fmt.Sprintf("Adding %v role to %s", backup.Admin, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.Admin, testUser1Name)

			err = backup.AddRoleToUser(testUser1Name, backup.SystemAdmin, fmt.Sprintf("Adding %v role to %s", backup.SystemAdmin, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.SystemAdmin, testUser1Name)
		})

		var (
			testUser2Name, testUser2FirstName, testUser2LastName, testUser2Email string
			testUser2Ctx                                                         context.Context
			backupLocationUID                                                    string
			bkpLocationName                                                      string
			customRoleName                                                       = backup.PxBackupRole(fmt.Sprintf("custom-role-%s", RandomString(4)))
		)

		Step("Create Custom app.User Role with Admin User", func() {
			services := []RoleServices{BackupSchedulePolicy, Rules, Cloudcredential, BackupLocation, Role}
			apis := []RoleApis{Inspect, Enumerate, Validate}
			err := CreateRole(customRoleName, services, apis, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of role [%s] by the %v user", customRoleName, "admin"))
		})

		Step("Update the Custom Role with infra.admin using user1", func() {
			services := []RoleServices{BackupSchedulePolicy, Rules, Cloudcredential, BackupLocation, Role}
			apis := []RoleApis{All}
			err := UpdateRole(customRoleName, services, apis, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying update of role [%s] by the %v user", customRoleName, testUser1Name))
		})

		Step("Login as User1 and Create User2 with custom role", func() {
			// Create testuser2
			testUser2Name = "testuser2"
			testUser2FirstName = "testUser2FirstName"
			testUser2LastName = "testUser2LastName"
			testUser2Email = "testuser2email@cnbu.com"

			err := backup.AddUser(testUser2Name, testUser2FirstName, testUser2LastName, testUser2Email, CommonPassword)
			log.FailOnError(err, "Failed to create user - %s", testUser2Name)

			err = backup.AddRoleToUserWithCredentials(testUser2Name, customRoleName, fmt.Sprintf("Adding %v role to %s", customRoleName, testUser2Name), testUser1Name, CommonPassword)
			log.FailOnError(err, "Failed to add role %s to the user %s", customRoleName, testUser2Name)

			testUser2Ctx, err = backup.GetNonAdminCtx(testUser2Name, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")
		})

		Step("Create a backup with user2", func() {
			// Share the Cloud Credential with user2 and create the BackupLocation
			for _, provider := range providers {
				if provider != drivers.ProviderNfs {
					err := AddCloudCredentialOwnership(cloudCredName, cloudCredUID, []string{testUser2Name}, nil, Read, Invalid, testUser1Ctx, BackupOrgID)
					log.FailOnError(err, "Sharing CloudCredential Object %s with user2", cloudCredName)
				}
				bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = bkpLocationName
				err := CreateBackupLocationWithContext(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", testUser2Ctx, true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
			}
		})

		Step("Cleanup", func() {
			err := backup.DeleteUser(testUser2Name)
			log.FailOnError(err, "Failed to delete user - %s", testUser2Name)

			log.Infof("Verify deletion of role [%s] created by user [%s] ", customRoleName, "admin")
			err = DeleteRole(customRoleName, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of role [%s] created by user  %s", customRoleName, testUser1Name))

			err = backup.DeleteRoleFromUser(testUser1Name, backup.DefaultRoles, fmt.Sprintf("delete %v role from %s", backup.DefaultRoles, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.DefaultRoles, testUser1Name)

			err = backup.DeleteRoleFromUser(testUser1Name, backup.Admin, fmt.Sprintf("delete %v role from %s", backup.Admin, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.Admin, testUser1Name)

			err = backup.DeleteRoleFromUser(testUser1Name, backup.SystemAdmin, fmt.Sprintf("delete %v role from %s", backup.SystemAdmin, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.SystemAdmin, testUser1Name)
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		err := DeleteClusterWithUID(SourceClusterName, sourceClusterUID, BackupOrgID, testUser1Ctx, false)
		dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting Cluster [%s]", SourceClusterName))

		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		log.InfoD("Deleting deployed applications")
		DestroyApps(scheduledAppContexts, opts)

		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, adminContext)

		err = backup.DeleteUser(testUser1Name)
		log.FailOnError(err, "Failed to delete user - %s", testUser1Name)
	})
})

var _ = Describe("{SuperAdminAccessVerificationWithBackupRestoreOperations}", Label(TestCaseLabelsMap[SuperAdmin]...), func() {
	var (
		scheduledAppContexts       []*scheduler.Context
		bkpNamespaces              []string
		backupList                 []string
		restoreList                []string
		backupScheduleList         []string
		cloudCredName              string
		cloudCredUID               string
		backupLocationUID          string
		backupLocationName         string
		backupLocationMap          map[string]string
		clusterUid                 string
		superAdmin                 string
		periodicSchedulePolicyName string
		periodicSchedulePolicyUid  string
		testUser1Name              = "testuser1"
		testUser1FirstName         = "testUser1FirstName"
		testUser1LastName          = "testUser1LastName"
		testUser1Email             = "testuser1email@cnbu.com"
	)

	BeforeEach(func() {
		backupLocationMap = make(map[string]string)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)
		cloudCredName, cloudCredUID, backupLocationUID, backupLocationName, periodicSchedulePolicyName, periodicSchedulePolicyUid = "", "", "", "", "", ""
		backupList = make([]string, 0)
		restoreList = make([]string, 0)
		backupScheduleList = make([]string, 0)

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}

		ValidateApplications(scheduledAppContexts)

		// Create Superadmin user
		superAdmin = CreateUsers(1)[0]
		err := backup.AddRoleToUser(superAdmin, backup.SuperAdmin, fmt.Sprintf("Adding %v role to %s", backup.SuperAdmin, superAdmin))
		log.FailOnError(err, "Failed to add role %s to the user %s", backup.SuperAdmin, superAdmin)

		// Create Backup Location and Cloud Setting
		adminContext, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin user ctx")
		log.InfoD("Creating backup location and cloud setting with admin user")
		backupLocationProviders := GetBackupProviders()
		for _, provider := range backupLocationProviders {
			cloudCredName = fmt.Sprintf("%s-cred-%v", provider, RandomString(10))
			cloudCredUID = uuid.New()
			err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, adminContext)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s]  as provider %s", cloudCredName, BackupOrgID, provider))

			backupLocationName = fmt.Sprintf("%s-backup-location-%v", provider, RandomString(10))
			backupLocationUID = uuid.New()
			backupLocationMap[backupLocationUID] = backupLocationName
			err = CreateBackupLocationWithContext(provider, backupLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", adminContext, true)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", backupLocationName))
		}
	})

	// This test case is to verify the read access of backups, restores, schedules, and cluster by SuperAdmin
	It("Verify the read access by SuperAdmin", func() {
		StartPxBackupTorpedoTest("VerifyReadAccessBySuperAdmin", "Verify Read Access By Super Admin", nil, 301207, Dbinnal, Q2FY25)

		Step("Crete cluster from admin along with backup and restore creation", func() {
			adminCtx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")

			err = AddSourceCluster(adminCtx)
			dash.VerifyFatal(err, nil, "Adding source cluster")

			clusterUid, err = Inst().Backup.GetClusterUID(adminCtx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))

			// Create a backup
			backupName := fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err = CreateBackup(backupName, SourceClusterName, backupLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, clusterUid, "", "", "", "", adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))
			backupList = append(backupList, backupName)

			restoreName := fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			namespaceMapping := make(map[string]string)
			for _, namespace := range bkpNamespaces {
				restoredNameSpace := fmt.Sprintf("%s-%s", namespace, "restored")
				namespaceMapping[namespace] = restoredNameSpace
			}

			// Create Restore
			err = CreateRestore(restoreName, backupName, namespaceMapping, SourceClusterName, clusterUid, BackupOrgID, adminCtx, make(map[string]string))
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of restore [%s]", restoreName))
			restoreList = append(restoreList, restoreName)
		})

		Step("Create a backup schedule with admin", func() {
			adminCtx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")

			// Create schedule Policy
			periodicSchedulePolicyName = fmt.Sprintf("%s-%s", "periodic", RandomString(5))
			periodicSchedulePolicyUid = uuid.New()
			periodicSchedulePolicyInterval := int64(15)
			err = CreateBackupScheduleIntervalPolicy(5, periodicSchedulePolicyInterval, 5, periodicSchedulePolicyName, periodicSchedulePolicyUid, BackupOrgID, adminCtx, false, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of periodic schedule policy of interval [%v] minutes named [%s] ", periodicSchedulePolicyInterval, periodicSchedulePolicyName))

			// Create a backup schedule
			scheduleName := fmt.Sprintf("schedule-bkp-%v", RandomString(5))
			err = CreateScheduleBackup(scheduleName, SourceClusterName, clusterUid, backupLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", periodicSchedulePolicyName, periodicSchedulePolicyUid, adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of scheduled backup with schedule name [%s]", scheduleName))
			backupScheduleList = append(backupScheduleList, scheduleName)
		})

		Step("Verify backups/schedules/restores are accessible with superadmin", func() {
			testUser1Ctx, err := backup.GetNonAdminCtx(superAdmin, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")

			clusterInspectReq := &api.ClusterInspectRequest{
				Name:           SourceClusterName,
				OrgId:          BackupOrgID,
				IncludeSecrets: false,
				Uid:            clusterUid,
			}
			_, err = Inst().Backup.InspectCluster(testUser1Ctx, clusterInspectReq)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying cluster [%s] is accessible to user [%s]", SourceClusterName, superAdmin))

			// Verify backups are accessible to testUser1
			for _, backup := range backupList {
				backupInspectReq := &api.BackupInspectRequest{
					Name:  backup,
					OrgId: BackupOrgID,
				}
				_, err = Inst().Backup.InspectBackup(testUser1Ctx, backupInspectReq)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying backup [%s] is accessible to user [%s]", backup, superAdmin))
			}

			// Verify restores are accessible to testUser1
			for _, restore := range restoreList {
				restoreInspectRequest := &api.RestoreInspectRequest{
					Name:  restore,
					OrgId: BackupOrgID,
				}
				_, err = Inst().Backup.InspectRestore(testUser1Ctx, restoreInspectRequest)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying restore [%s] is accessible to user [%s]", restore, superAdmin))
			}

			_, err = Inst().Backup.InspectSchedulePolicy(testUser1Ctx, &api.SchedulePolicyInspectRequest{
				OrgId: BackupOrgID,
				Name:  periodicSchedulePolicyName,
				Uid:   periodicSchedulePolicyUid,
			})
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying schedule policy [%s] is accessible to user [%s]", periodicSchedulePolicyName, superAdmin))

			// Verify Schedules are accessible to testUser1
			for _, schedule := range backupScheduleList {
				scheduleInspectRequest := &api.BackupScheduleInspectRequest{
					Name:  schedule,
					OrgId: BackupOrgID,
				}
				_, err = Inst().Backup.InspectBackupSchedule(testUser1Ctx, scheduleInspectRequest)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying schedule [%s] is accessible to user [%s]", schedule, superAdmin))
			}
		})
	})

	// This testcase is to verify share cluster with share allBackups option from superadmin
	It("As super Admin execute share allBackup option with share cluster", func() {
		StartPxBackupTorpedoTest("AsSuperAdminExecuteShareAllBackupOptionWithClusterShare", "As super admin execute share allBackups option with share cluster", nil, 301294, Dbinnal, Q2FY25)

		var (
			testUser2            string
			superAdminBackupName string
		)

		Step("Add a testUser2", func() {
			testUser2 = CreateUsers(1)[0]
		})

		Step("Creta cluster from admin and create a backup", func() {
			adminCtx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")

			err = AddSourceCluster(adminCtx)
			dash.VerifyFatal(err, nil, "Adding source cluster")

			clusterUid, err = Inst().Backup.GetClusterUID(adminCtx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))

			// Create a backup
			backupName := fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err = CreateBackup(backupName, SourceClusterName, backupLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, clusterUid, "", "", "", "", adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))
			backupList = append(backupList, backupName)
		})

		Step("Share cluster with share allbackups option to testUser2 from superadmin", func() {
			tetsUser1Ctx, err := backup.GetNonAdminCtx(superAdmin, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")

			// Create backup
			superAdminBackupName = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err = CreateBackup(superAdminBackupName, SourceClusterName, backupLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, clusterUid, "", "", "", "", tetsUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", superAdminBackupName))
			backupList = append(backupList, superAdminBackupName)

			id, _ := backup.FetchIDOfUser(testUser2)
			log.InfoD("Sharing cluster with share allbackups option with user [%s]", testUser2)
			log.InfoD("UserId of the user [%s] is [%s]", testUser2, id)
			// Share the source cluster to testuser2 with share all backups option
			_, err = ShareCluster(tetsUser1Ctx, SourceClusterName, clusterUid, []string{testUser2}, nil, true)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying share of source [%s] cluster with %s user", SourceClusterName, []string{testUser2}))
			time.Sleep(10 * time.Second)
		})

		Step("Verify backups are accessible to testUser2 and take restore", func() {
			testUser2Ctx, err := backup.GetNonAdminCtx(testUser2, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")

			// Verify cluster is accessible to testUser2
			clusterInspectReq := &api.ClusterInspectRequest{
				Name:  SourceClusterName,
				OrgId: BackupOrgID,
				Uid:   clusterUid,
			}
			_, err = Inst().Backup.InspectCluster(testUser2Ctx, clusterInspectReq)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying cluster [%s] is accessible to user [%s]", SourceClusterName, testUser2))

			// Verify only backups owned by superadmin are accessible to shared user
			backups, err := GetAllBackupsForUser(testUser2, CommonPassword)
			dash.VerifyFatal(err, nil, "Failed to get all backups for user")
			log.Infof("GetallBackups error: %v", err)
			dash.VerifyFatal(len(backups), 1, "Verifying backups are accessible to shared user")

			backupInspectReq := &api.BackupInspectRequest{
				Name:  superAdminBackupName,
				OrgId: BackupOrgID,
			}
			_, err = Inst().Backup.InspectBackup(testUser2Ctx, backupInspectReq)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying backup [%s] is accessible to user [%s]", superAdminBackupName, testUser2))

			// Create Restore
			restoreName := fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			namespaceMapping := make(map[string]string)
			for _, namespace := range bkpNamespaces {
				restoredNameSpace := fmt.Sprintf("%s-%s", namespace, "restored")
				namespaceMapping[namespace] = restoredNameSpace
			}

			// Create Restore of the backup owned by admin is failed as user is not having access to the backup
			err = CreateRestore(restoreName, backupList[0], namespaceMapping, SourceClusterName, clusterUid, BackupOrgID, testUser2Ctx, make(map[string]string))
			dash.VerifyNotNilFatal(err, fmt.Sprintf("Creation of restore [%s] expected to fail", restoreName))

			// Create Restore of the backup owned by superadmin is successful as user is having access to the backup
			restoreName = fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			// Create Restore
			err = CreateRestore(restoreName, backupList[1], namespaceMapping, SourceClusterName, clusterUid, BackupOrgID, testUser2Ctx, make(map[string]string))
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of restore [%s]", restoreName))
		})

		Step("Unshare cluster with testUser2", func() {
			tetsUser1Ctx, err := backup.GetNonAdminCtx(superAdmin, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")

			// Unshare the source cluster to testuser2
			_, err = UnShareCluster(tetsUser1Ctx, SourceClusterName, clusterUid, []string{testUser2}, nil)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying unshare of source [%s] cluster with %s user", SourceClusterName, []string{testUser2}))
		})
	})

	// This testcase is to verify SuperAdmin role revoke removes the access to admin user objects from the superadmin
	It("Verify SuperAdmin revoke", func() {
		StartPxBackupTorpedoTest("VerifySuperAdminRevoke", "Verify super admin revoke", nil, 301209, Dbinnal, Q2FY25)

		Step("Create a cluster and create backups/backupschedule with admin user", func() {
			adminCtx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")

			err = AddSourceCluster(adminCtx)
			dash.VerifyFatal(err, nil, "Adding source cluster")

			clusterUid, err = Inst().Backup.GetClusterUID(adminCtx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))

			// Create a backup
			backupName := fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err = CreateBackup(backupName, SourceClusterName, backupLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, clusterUid, "", "", "", "", adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))
			backupList = append(backupList, backupName)

			// Create schedule Policy
			periodicSchedulePolicyName = fmt.Sprintf("%s-%s", "periodic", RandomString(5))
			periodicSchedulePolicyUid = uuid.New()
			periodicSchedulePolicyInterval := int64(15)
			err = CreateBackupScheduleIntervalPolicy(5, periodicSchedulePolicyInterval, 5, periodicSchedulePolicyName, periodicSchedulePolicyUid, BackupOrgID, adminCtx, false, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of periodic schedule policy of interval [%v] minutes named [%s] ", periodicSchedulePolicyInterval, periodicSchedulePolicyName))

			// Create a backup schedule
			scheduleName := fmt.Sprintf("schedule-bkp-%v", RandomString(5))
			err = CreateScheduleBackup(scheduleName, SourceClusterName, clusterUid, backupLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", periodicSchedulePolicyName, periodicSchedulePolicyUid, adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of scheduled backup with schedule name [%s]", scheduleName))
			backupScheduleList = append(backupScheduleList, scheduleName)

			// Create restore from backup
			restoreName := fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			namespaceMapping := make(map[string]string)
			for _, namespace := range bkpNamespaces {
				namespaceMapping[namespace] = namespace
			}

			err = CreateRestore(restoreName, backupName, namespaceMapping, SourceClusterName, clusterUid, BackupOrgID, adminCtx, make(map[string]string))
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of restore [%s]", restoreName))
		})

		Step("As a superAdmin verify testUser1 can access the cluster and create backup/backupschedule", func() {
			testUser1Ctx, err := backup.GetNonAdminCtx(superAdmin, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")

			// Create a backup
			backupName := fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err = CreateBackup(backupName, SourceClusterName, backupLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, clusterUid, "", "", "", "", testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))
			backupList = append(backupList, backupName)

			// Create a backup schedule
			scheduleName := fmt.Sprintf("schedule-bkp-%v", RandomString(5))
			err = CreateScheduleBackup(scheduleName, SourceClusterName, clusterUid, backupLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", periodicSchedulePolicyName, periodicSchedulePolicyUid, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of scheduled backup with schedule name [%s]", scheduleName))
			backupScheduleList = append(backupScheduleList, scheduleName)

			// Create restore from backup
			restoreName := fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			namespaceMapping := make(map[string]string)
			for _, namespace := range bkpNamespaces {
				restoreNamespace := fmt.Sprintf("%s-%s", namespace, "restored")
				namespaceMapping[namespace] = restoreNamespace
			}

			err = CreateRestore(restoreName, backupList[0], namespaceMapping, SourceClusterName, clusterUid, BackupOrgID, testUser1Ctx, make(map[string]string))
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of restore [%s]", restoreName))
		})

		Step("Revoke superAdmin role from testUser1 and verify access", func() {
			err := backup.DeleteRoleFromUser(superAdmin, backup.SuperAdmin, fmt.Sprintf("Revoking %v role from %s", backup.SuperAdmin, superAdmin))
			log.FailOnError(err, "Failed to delete role %v from user %s", backup.SuperAdmin, superAdmin)

			testUser1Ctx, err := backup.GetNonAdminCtx(superAdmin, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")

			// Verify cluster is no longer accessible to testUser1
			clusterInspectRequest := &api.ClusterInspectRequest{
				Name:  SourceClusterName,
				OrgId: BackupOrgID,
				Uid:   clusterUid,
			}
			_, err = Inst().Backup.InspectCluster(testUser1Ctx, clusterInspectRequest)
			dash.VerifyNotNilFatal(err, fmt.Sprintf("Verifying cluster [%s] is not accessible to user [%s]", SourceClusterName, superAdmin))

			// Verify backups are not accessible to testUser1
			backups, err := GetAllBackupsForUser(superAdmin, CommonPassword)
			dash.VerifyFatal(err, nil, "Failed to get all backups for user")
			dash.VerifyFatal(len(backups), 2, "Verifying only owned backups are accessible to shared user")

			// Verify backup1 created from admin is not accessible to testUser1
			backupInspectReq := &api.BackupInspectRequest{
				Name:  backupList[0],
				OrgId: BackupOrgID,
			}
			_, err = Inst().Backup.InspectBackup(testUser1Ctx, backupInspectReq)
			dash.VerifyNotNilFatal(err, fmt.Sprintf("Verifying backup [%s] is not accessible to user [%s]", backupList[0], superAdmin))

			// verify schedule1 created from admin is not accessible to testUser1
			scheduleInspectRequest := &api.BackupScheduleInspectRequest{
				Name:  backupScheduleList[0],
				OrgId: BackupOrgID,
			}
			_, err = Inst().Backup.InspectBackupSchedule(testUser1Ctx, scheduleInspectRequest)
			dash.VerifyNotNilFatal(err, fmt.Sprintf("Verifying schedule [%s] is not accessible to user [%s]", backupScheduleList[0], superAdmin))
		})
	})

	// This testcase is to verify after the revoking the superadmin role, superadmin has access to the object created by him only
	It("Verify ownership after super admin revoke", func() {
		StartPxBackupTorpedoTest("VerifyOwnershipAfterSuperAdminRevoke", "Verify ownership after the super admin revoke", nil, 301210, Dbinnal, Q2FY25)

		var (
			clusterName  string
			clsuter1UID  string
			scheduleName string
		)

		Step("Create a source cluster and take backup/baackupschedules on it", func() {
			adminCtx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")

			err = AddSourceCluster(adminCtx)
			dash.VerifyFatal(err, nil, "Adding source cluster")

			clusterUid, err = Inst().Backup.GetClusterUID(adminCtx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
		})

		Step("As a superadmin testUser1 will create a cluster2 and take backup/backupschedules", func() {
			testUser1Ctx, err := backup.GetNonAdminCtx(superAdmin, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")

			// Verify cluster1(Source cluster) is accessible to testUser1
			clusterInspectRequest := &api.ClusterInspectRequest{
				Name:  SourceClusterName,
				OrgId: BackupOrgID,
				Uid:   clusterUid,
			}
			_, err = Inst().Backup.InspectCluster(testUser1Ctx, clusterInspectRequest)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying cluster [%s] is accessible to user [%s]", SourceClusterName, superAdmin))

			clusterName = fmt.Sprintf("cluster-%s", RandomString(5))
			sourceKubeConfigPath, err := GetSourceClusterConfigPath()
			log.FailOnError(err, "Fetching source cluster kubeconfig path")
			err = CreateCluster(clusterName, sourceKubeConfigPath, BackupOrgID, "", "", testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Adding %s cluster", clusterName))

			clsuter1UID, err = Inst().Backup.GetClusterUID(testUser1Ctx, BackupOrgID, clusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", clusterName))

			// Create a backup
			backupName := fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err = CreateBackup(backupName, clusterName, backupLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, clsuter1UID, "", "", "", "", testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))
			backupList = append(backupList, backupName)

			// Create schedule policy
			periodicSchedulePolicyName = fmt.Sprintf("%s-%s", "periodic", RandomString(5))
			periodicSchedulePolicyUid = uuid.New()
			periodicSchedulePolicyInterval := int64(15)
			err = CreateBackupScheduleIntervalPolicy(5, periodicSchedulePolicyInterval, 5, periodicSchedulePolicyName, periodicSchedulePolicyUid, BackupOrgID, testUser1Ctx, false, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of periodic schedule policy of interval [%v] minutes named [%s] ", periodicSchedulePolicyInterval, periodicSchedulePolicyName))

			// Create a backup schedule
			scheduleName = fmt.Sprintf("schedule-bkp-%v", RandomString(5))
			err = CreateScheduleBackup(scheduleName, clusterName, clsuter1UID, backupLocationName, backupLocationUID, bkpNamespaces, make(map[string]string), BackupOrgID, "", "", "", "", periodicSchedulePolicyName, periodicSchedulePolicyUid, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of scheduled backup with schedule name [%s]", scheduleName))
			// backupScheduleList = append(backupScheduleList, scheduleName)

			// Create restore from backup
			restoreName := fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			namespaceMapping := make(map[string]string)
			for _, namespace := range bkpNamespaces {
				restoreNamespace := fmt.Sprintf("%s-%s", namespace, "restored")
				namespaceMapping[namespace] = restoreNamespace
			}

			err = CreateRestore(restoreName, backupName, namespaceMapping, clusterName, clsuter1UID, BackupOrgID, testUser1Ctx, make(map[string]string))
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of restore [%s]", restoreName))
			restoreList = append(restoreList, restoreName)
		})

		Step("Revoke superAdmin role from testUser1 and verify access", func() {
			err := backup.DeleteRoleFromUser(superAdmin, backup.SuperAdmin, fmt.Sprintf("Revoking %v role from %s", backup.SuperAdmin, superAdmin))
			log.FailOnError(err, "Failed to delete role %v from user %s", backup.SuperAdmin, superAdmin)

			testUser1Ctx, err := backup.GetNonAdminCtx(superAdmin, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")

			// Verify cluster1 is no longer accessible to testUser1
			clusterInspectRequest := &api.ClusterInspectRequest{
				Name:  SourceClusterName,
				OrgId: BackupOrgID,
				Uid:   clusterUid,
			}
			_, err = Inst().Backup.InspectCluster(testUser1Ctx, clusterInspectRequest)
			dash.VerifyNotNilFatal(err, fmt.Sprintf("Verifying cluster [%s] is not accessible to user [%s]", SourceClusterName, superAdmin))

			// Verify cluster2 is accessible to testUser1
			clusterInspectRequest = &api.ClusterInspectRequest{
				Name:  clusterName,
				OrgId: BackupOrgID,
				Uid:   clsuter1UID,
			}
			_, err = Inst().Backup.InspectCluster(testUser1Ctx, clusterInspectRequest)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying cluster [%s] is accessible to user [%s]", clusterName, superAdmin))

			// Verify backups are not accessible to testUser1
			backups, err := GetAllBackupsForUser(superAdmin, CommonPassword)
			dash.VerifyFatal(err, nil, "Failed to get all backups for user")
			dash.VerifyFatal(len(backups), 2, "Verifying owned backups are accessible to shared user")

			// Verify restores are accessible to testUser1
			restores, err := GetAllRestoresForUser(superAdmin, CommonPassword)
			dash.VerifyFatal(err, nil, "Failed to get all restores for user")
			dash.VerifyFatal(len(restores), 1, "Verifying owned restores are accessible to shared user")

			restoreInspectRequest := &api.RestoreInspectRequest{
				Name:  restoreList[0],
				OrgId: BackupOrgID,
			}
			// Verify testUser1 is able access the restore
			_, err = Inst().Backup.InspectRestore(testUser1Ctx, restoreInspectRequest)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying testUser1 is able to access the restore [%s]", restoreList[0]))

			// Verify restores are accessible to testUser1
			shedules, err := GetAllBackupSchedulesForUser(superAdmin, CommonPassword)
			dash.VerifyFatal(err, nil, "Failed to get all restores for user")
			dash.VerifyFatal(len(shedules), 1, "Verifying owned schedules are accessible to shared user")
		})

		Step("Delete cluster created by testUser1", func() {
			testUser1Ctx, err := backup.GetNonAdminCtx(superAdmin, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")

			// Delete the schedules
			scheduleUID, err := GetScheduleUID(scheduleName, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] backupschedule uid", scheduleName))
			err = DeleteScheduleWithUIDAndWait(scheduleName, scheduleUID, clusterName, clsuter1UID, BackupOrgID, testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of backup schedule [%s]", scheduleName))

			err = DeleteCluster(clusterName, BackupOrgID, testUser1Ctx, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting cluster [%s]", clusterName))
		})
	})

	// This testcase is to verify superadmin access to the objects created by admin user
	It("VerifySuperAdminAccessToObjectsCreatedByAdminUser", func() {
		StartPxBackupTorpedoTest("Verify Super Admin Operations ", "Verify Backup/BackupSchedule and Restore operations by Super Admin", nil, 301208, "vsundarraj", Q2FY25)

		var (
			backupName       = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			restoreName      = fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			namespaceMapping = make(map[string]string)
			scheduleName     string
		)

		Step("Create Cluster with Admin Context and create backup/backupSchedule/restore objects on it", func() {
			adminCtx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")

			log.InfoD("Creating Cluster with Admin context")
			err = AddSourceCluster(adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of source [%s] cluster with admin ctx", SourceClusterName))

			clusterUid, err = Inst().Backup.GetClusterUID(adminCtx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))

			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err = CreateBackup(backupName, SourceClusterName, backupLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, clusterUid, "", "", "", "", adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))

			log.InfoD("Creating SchedulePolicy with Admin Context")
			periodicSchedulePolicyName = fmt.Sprintf("%s-%s", "periodic", RandomString(5))
			periodicSchedulePolicyUid = uuid.New()
			periodicSchedulePolicyInterval := int64(15)
			err = CreateBackupScheduleIntervalPolicy(5, periodicSchedulePolicyInterval, 5, periodicSchedulePolicyName, periodicSchedulePolicyUid, BackupOrgID, adminCtx, false, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of periodic schedule policy of interval [%v] minutes named [%s] ", periodicSchedulePolicyInterval, periodicSchedulePolicyName))
			periodicSchedulePolicyUid, err = Inst().Backup.GetSchedulePolicyUid(BackupOrgID, adminCtx, periodicSchedulePolicyName)
			log.FailOnError(err, "Fetching uid of schedule policy [%s]", periodicSchedulePolicyName)

			log.InfoD("Creating BackupSchedule with Admin Context")
			scheduleName = fmt.Sprintf("%s-schedule-%v", BackupNamePrefix, RandomString(6))
			labelSelectors := make(map[string]string)
			err = CreateScheduleBackup(scheduleName, SourceClusterName, clusterUid, backupLocationName, backupLocationUID, bkpNamespaces, labelSelectors, BackupOrgID, "", "", "", "", periodicSchedulePolicyName, periodicSchedulePolicyUid, adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of schedule backup with schedule name [%s]", scheduleName))
		})

		Step("Verify object Access by SuperAdmin on Admin created Cluster", func() {
			ctx, err := backup.GetNonAdminCtx(superAdmin, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")

			_, err = Inst().Backup.InspectCluster(ctx, &api.ClusterInspectRequest{
				OrgId:          BackupOrgID,
				Name:           SourceClusterName,
				IncludeSecrets: false,
				Uid:            clusterUid,
			})
			dash.VerifyFatal(err, nil, "Cluster Inspect by Super Admin user")

			_, err = Inst().Backup.InspectBackup(ctx, &api.BackupInspectRequest{
				OrgId: BackupOrgID,
				Name:  backupName,
			})
			dash.VerifyFatal(err, nil, "Backup Inspect by Super Admin user")

			backupLocationProvider := GetBackupProviders()
			for _, provider := range backupLocationProvider {
				if provider != drivers.ProviderNfs {
					_, err = Inst().Backup.InspectCloudCredential(ctx, &api.CloudCredentialInspectRequest{
						OrgId: BackupOrgID,
						Name:  cloudCredName,
						Uid:   cloudCredUID,
					})
					dash.VerifyFatal(err, nil, "CloudCredential Inspect by Super Admin user")
				}
			}

			_, err = Inst().Backup.InspectBackupLocation(ctx, &api.BackupLocationInspectRequest{
				OrgId: BackupOrgID,
				Name:  backupLocationName,
				Uid:   backupLocationUID,
			})
			dash.VerifyFatal(err, nil, "BackupLocation Inspect by Super Admin user")

			_, err = Inst().Backup.InspectSchedulePolicy(ctx, &api.SchedulePolicyInspectRequest{
				OrgId: BackupOrgID,
				Name:  periodicSchedulePolicyName,
				Uid:   periodicSchedulePolicyUid,
			})
			dash.VerifyFatal(err, nil, "SchedulePolicy Inspect by Super Admin user")

			_, err = Inst().Backup.InspectBackupSchedule(ctx, &api.BackupScheduleInspectRequest{
				OrgId: BackupOrgID,
				Name:  scheduleName,
			})
			dash.VerifyFatal(err, nil, "BackupSchedule Inspect by Super Admin user")
		})

		Step("Verify create Backup BackupSchedule and Restore by SuperAdmin(testUser1) on Admin created Cluster", func() {
			ctx, err := backup.GetNonAdminCtx(superAdmin, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")

			userBackupName := fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]  with super admin context", bkpNamespaces))
			err = CreateBackup(userBackupName, SourceClusterName, backupLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, clusterUid, "", "", "", "", ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", userBackupName))

			log.InfoD("Creating BackupSchedule with superAdmin context")
			scheduleName := fmt.Sprintf("%s-schedule-%v", BackupNamePrefix, RandomString(6))
			err = CreateScheduleBackup(scheduleName, SourceClusterName, clusterUid, backupLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, "", "", "", "", periodicSchedulePolicyName, periodicSchedulePolicyUid, ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of schedule backup with schedule name [%s]", scheduleName))

			for _, namespace := range bkpNamespaces {
				namespaceMapping[namespace] = namespace
			}
			err = CreateRestore(restoreName, userBackupName, namespaceMapping, SourceClusterName, clusterUid, BackupOrgID, ctx, make(map[string]string))
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of restore [%s]", restoreName))
		})
	})

	// This test verifies sharing of backup with restore access to other users from other users having super admin role ( non owner/ non default admin )
	It("VerifyClusterBackupShareWithBackupCreationAndRestoreBySharedUser", func() {
		StartPxBackupTorpedoTest("VerifyClusterBackupShareWithBackupCreationAndRestoreBySharedUser", "Verify Cluster Backup Share with Backup Creation and Restore by Shared User", nil, 301216, Pamathur, Q2FY25)
		var (
			backupName         = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			restoreName        = fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			restoreName2       = fmt.Sprintf("%s-%v-2", RestoreNamePrefix, time.Now().Unix())
			namespaceMapping   = make(map[string]string)
			scheduleName       string
			testUser2Name      = "testuser2"
			testUser2FirstName = "testUser2FirstName"
			testUser2LastName  = "testUser2LastName"
			testUser2Email     = "testuser2email@cnbu.com"
		)
		Step("Create Cluster with Admin Context and create backup/backupSchedule/restore objects on it", func() {

			adminCtx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")

			err = AddSourceCluster(adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Adding source cluster [%s] using admin ctx", SourceClusterName))

			clusterUid, err = Inst().Backup.GetClusterUID(adminCtx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid using admin ctx", SourceClusterName))

			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err = CreateBackup(backupName, SourceClusterName, backupLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, clusterUid, "", "", "", "", adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s] using admin ctx", backupName))

			log.InfoD("Creating SchedulePolicy with Admin Context")
			periodicSchedulePolicyName = fmt.Sprintf("%s-%s", "periodic", RandomString(5))
			periodicSchedulePolicyUid = uuid.New()
			periodicSchedulePolicyInterval := int64(15)
			err = CreateBackupScheduleIntervalPolicy(5, periodicSchedulePolicyInterval, 5, periodicSchedulePolicyName, periodicSchedulePolicyUid, BackupOrgID, adminCtx, false, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of periodic schedule policy of interval [%v] minutes named [%s] using admin ctx", periodicSchedulePolicyInterval, periodicSchedulePolicyName))
			periodicSchedulePolicyUid, err = Inst().Backup.GetSchedulePolicyUid(BackupOrgID, adminCtx, periodicSchedulePolicyName)
			log.FailOnError(err, "Fetching uid of schedule policy [%s] using admin ctx", periodicSchedulePolicyName)

			log.InfoD("Creating BackupSchedule with Admin Context")
			scheduleName = fmt.Sprintf("%s-schedule-%v", BackupNamePrefix, RandomString(6))
			labelSelectors := make(map[string]string)
			err = CreateScheduleBackup(scheduleName, SourceClusterName, clusterUid, backupLocationName, backupLocationUID, bkpNamespaces, labelSelectors, BackupOrgID, "", "", "", "", periodicSchedulePolicyName, periodicSchedulePolicyUid, adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of schedule backup with schedule name [%s] using admix ctx", scheduleName))

			for _, namespace := range bkpNamespaces {
				namespaceMapping[namespace] = namespace
			}
			err = CreateRestore(restoreName, backupName, namespaceMapping, SourceClusterName, clusterUid, BackupOrgID, adminCtx, make(map[string]string))
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of restore [%s] using admin ctx", restoreName))
		})
		Step("Share Backup as restore access using user with super admin role", func() {
			superAdminCtx, err := backup.GetNonAdminCtx(superAdmin, CommonPassword)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching super.admin user [%s] ctx", superAdmin))

			// Create testuser1
			err = backup.AddUser(testUser1Name, testUser1FirstName, testUser1LastName, testUser1Email, CommonPassword)
			log.FailOnError(err, "Failed to create user - %s", testUser1Name)

			err = backup.AddRoleToUser(testUser1Name, backup.ApplicationOwner, fmt.Sprintf("Adding %v role to %s", backup.SuperAdmin, testUser1Name))
			log.FailOnError(err, "Failed to add role %s to the user %s", backup.SuperAdmin, testUser1Name)

			err = ShareBackup(backupName, nil, []string{testUser1Name}, RestoreAccess, superAdminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Sharing backup [%s] to user [%s] with restore access with [%s] ctx", backupName, testUser1Name, superAdmin))
		})
		Step("Verify Backup Shared to User 2 and create restore to verify restore access", func() {
			testUser1Ctx, err := backup.GetNonAdminCtx(testUser1Name, CommonPassword)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching testUser1 [%s] ctx", testUser1Name))

			// Verify backup is accessible to testUser1
			_, err = Inst().Backup.InspectBackup(testUser1Ctx, &api.BackupInspectRequest{
				OrgId: BackupOrgID,
				Name:  backupName,
			})
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying backup [%s] is accessible to user [%s]", backupName, testUser1Name))

			// user1 needs atleast one cluster where he can restore
			err = AddSourceCluster(testUser1Ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Adding source cluster [%s] using [%s] ctx", SourceClusterName, testUser1Name))

			testUser1ClusterUid, err := Inst().Backup.GetClusterUID(testUser1Ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid using testuser1 ctx", SourceClusterName))

			// Create restore from backup
			restoreName := fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			namespaceMapping := make(map[string]string)
			for _, namespace := range bkpNamespaces {
				restoreNamespace := fmt.Sprintf("%s-%s", namespace, "restored")
				namespaceMapping[namespace] = restoreNamespace
			}

			err = CreateRestore(restoreName2, backupName, namespaceMapping, SourceClusterName, testUser1ClusterUid, BackupOrgID, testUser1Ctx, make(map[string]string))
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of restore [%s]", restoreName))
		})
		Step("Verify Backup access and share to user 3", func() {
			superAdminCtx, err := backup.GetNonAdminCtx(superAdmin, CommonPassword)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching super.admin user [%s] ctx", superAdmin))

			// Verify backup is accessible to testUser1
			_, err = Inst().Backup.InspectBackup(superAdminCtx, &api.BackupInspectRequest{
				OrgId: BackupOrgID,
				Name:  backupName,
			})
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying backup [%s] is accessible to user [%s]", backupName, superAdmin))

			// Create testuser2
			err = backup.AddUser(testUser2Name, testUser2FirstName, testUser2LastName, testUser2Email, CommonPassword)
			log.FailOnError(err, "Failed to create user - %s", testUser2Name)

			err = ShareBackup(backupName, nil, []string{testUser2Name}, RestoreAccess, superAdminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Sharing backup [%s] to user [%s] with restore access with [%s] ctx", backupName, testUser2Name, superAdmin))
		})
		Step("Cleanup", func() {
			adminCtx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching admin user ctx")

			log.InfoD("Deleting backup")
			backupUID, err := Inst().Backup.GetBackupUID(adminCtx, backupName, BackupOrgID)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] backup uid using admin ctx", backupName))

			// Delete the backup
			_, err = DeleteBackup(backupName, backupUID, BackupOrgID, adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s] using admin ctx", backupName))

			err = SuspendAndDeleteSchedule(scheduleName, periodicSchedulePolicyName, SourceClusterName, clusterUid, BackupOrgID, adminCtx, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of schedule [%s] using admin ctx", scheduleName))

			// Delete the restore
			err = DeleteRestore(restoreName, BackupOrgID, adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting restore [%s] using admin ctx", restoreName))

			// Delete the restore
			err = DeleteRestore(restoreName2, BackupOrgID, adminCtx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting restore [%s] using admin ctx", restoreName2))

			// Delete the users
			for _, user := range []string{testUser1Name, testUser2Name} {
				err = backup.DeleteUser(user)
				log.FailOnError(err, "Failed to delete user - %s", user)
			}
		})

	})

	AfterEach(func() {
		// Cleanup
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		ctx, err := backup.GetPxCentralAdminCtx()
		log.FailOnError(err, "Fetching admin user ctx")

		// Delete the backup schedules
		scheduleEnumerateRequest := &api.BackupScheduleEnumerateRequest{
			OrgId: BackupOrgID,
		}
		scheduleList, err := Inst().Backup.EnumerateBackupSchedule(ctx, scheduleEnumerateRequest)
		log.FailOnError(err, "failed to enumerate backup schedules")
		for _, schedule := range scheduleList.BackupSchedules {
			err = DeleteScheduleWithUIDAndWait(schedule.Name, schedule.Uid, SourceClusterName, clusterUid, BackupOrgID, ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying deletion of backup schedule [%s]", schedule))
		}

		backupEnumerateRequest := &api.BackupEnumerateRequest{
			OrgId: BackupOrgID,
		}
		backupList, err := Inst().Backup.EnumerateBackup(ctx, backupEnumerateRequest)
		log.FailOnError(err, "failed to enumerate backups")
		// Delete the backups
		for _, backup := range backupList.Backups {
			err = DeleteBackupAndWaitForCompletion(backup.Name, backup.Uid, BackupOrgID, ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backup))
		}

		// Delete the schedule policy
		if len(periodicSchedulePolicyName) > 0 {
			log.InfoD("Deleting schedule policy [%s]", periodicSchedulePolicyName)
			schedulePolicyDeleteRequest := &api.SchedulePolicyDeleteRequest{
				Name:  periodicSchedulePolicyName,
				Uid:   periodicSchedulePolicyUid,
				OrgId: BackupOrgID,
			}
			_, err := Inst().Backup.DeleteSchedulePolicy(ctx, schedulePolicyDeleteRequest)
			log.FailOnError(err, "failed to delete schedule policy [%s]", periodicSchedulePolicyName)
		}

		restoreEnumerateRequest := &api.RestoreEnumerateRequest{
			OrgId: BackupOrgID,
		}
		restoreList, err := Inst().Backup.EnumerateRestore(ctx, restoreEnumerateRequest)
		log.FailOnError(err, "failed to enumerate restores")
		// Delete the restores
		for _, restore := range restoreList.Restores {
			err = DeleteRestore(restore.Name, BackupOrgID, ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting restore [%s]", restore.Name))
		}

		log.InfoD("Deleting deployed applications")
		DestroyApps(scheduledAppContexts, opts)

		err = DeleteNamespaces(bkpNamespaces)
		log.FailOnError(err, "failed to delete namespaces")

		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)

		// Delete the users
		for _, user := range []string{superAdmin} {
			err = backup.DeleteUser(user)
			log.FailOnError(err, "Failed to delete user - %s", user)
		}
	})
})

var _ = Describe("{SuperAdminBackupShare}", Label(TestCaseLabelsMap[SuperAdminBackupShare]...), func() {
	type user struct {
		name string
		ctx  context.Context
	}

	var (
		scheduledAppContexts []*scheduler.Context
		bkpNamespaces        []string
		providers            []string = GetBackupProviders()
		cloudCredName        string
		cloudCredUID         string
		backupLocationUID    string
		bkpLocationName      string
		backupLocationMap    map[string]string
		pxbUsers             map[int]user
	)

	JustBeforeEach(func() {
		backupLocationMap = make(map[string]string)
		scheduledAppContexts = make([]*scheduler.Context, 0)
		bkpNamespaces = make([]string, 0)
		cloudCredName, cloudCredUID, backupLocationUID, bkpLocationName = "", "", "", ""

		// Schedule an Application
		appContexts := ScheduleApplications(TaskNamePrefix)
		for _, ctx := range appContexts {
			ctx.ReadinessTimeout = AppReadinessTimeout
			namespace := GetAppNamespace(ctx, TaskNamePrefix)
			bkpNamespaces = append(bkpNamespaces, namespace)
			scheduledAppContexts = append(scheduledAppContexts, ctx)
		}

		// Validate the application
		ValidateApplications(scheduledAppContexts)

		// Create two test users
		var err error
		numberOfUsers := 2
		log.InfoD("Creating %d users", numberOfUsers)
		testusers := CreateUsers(numberOfUsers)
		pxbUsers = make(map[int]user)

		adminCtx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching admin user ctx")

		pxbUsers[0] = user{name: "ADMIN USER", ctx: adminCtx}
		//pxbUsers = map[int]user{1: {name: "testuser1"}, 2: {name: "testuser2"}}
		for index, testuser := range testusers {
			ctxNonAdmin, err := backup.GetNonAdminCtx(testuser, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")
			pxbUsers[index+1] = user{testuser, ctxNonAdmin}
		}

		// Create backup location and cloud setting with admin user
		log.InfoD("Creating backup location and cloud setting with admin user")
		for _, provider := range providers {
			cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
			bkpLocationName = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
			cloudCredUID = uuid.New()
			backupLocationUID = uuid.New()
			backupLocationMap[backupLocationUID] = bkpLocationName
			err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, pxbUsers[0].ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
			err = CreateBackupLocationWithContext(provider, bkpLocationName, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", pxbUsers[0].ctx, true)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", bkpLocationName))
		}

	})

	It("VerifySuperAdminAccessBackupShareOfAdminBackups", func() {
		StartPxBackupTorpedoTest("Verify Super Admin Operations ", "Verify SuperAdmin can share AdminBackups to other user", nil, 301039, "vsundarraj", Q2FY25)

		var (
			backupName            = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			restoreName           = fmt.Sprintf("%s-%v", RestoreNamePrefix, time.Now().Unix())
			namespaceMapping      = make(map[string]string)
			sourceClusterUID      string
			destinationClusterUID string
		)

		Step("Create cluster object with admin user", func() {
			// Create a cluster object with User1
			err := AddSourceCluster(pxbUsers[0].ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of source [%s] cluster with %s ctx", SourceClusterName, pxbUsers[0].name))
			sourceClusterUID, err = Inst().Backup.GetClusterUID(pxbUsers[0].ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
		})

		Step("Create a backup with admin user", func() {
			// Take Backup
			log.InfoD(fmt.Sprintf("Taking backup of multiple namespaces [%v]", bkpNamespaces))
			err := CreateBackup(backupName, SourceClusterName, bkpLocationName, backupLocationUID, bkpNamespaces, nil, BackupOrgID, sourceClusterUID, "", "", "", "", pxbUsers[0].ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))
		})

		Step("Assign user1 with super admin role", func() {
			err := backup.AddRoleToUser(pxbUsers[1].name, backup.SuperAdmin, fmt.Sprintf("Adding %v role to %s", backup.SuperAdmin, pxbUsers[1].name))
			log.FailOnError(err, "failed to add role %s to the user %s", backup.SuperAdmin, pxbUsers[1].name)

			ctxNonAdmin, err := backup.GetNonAdminCtx(pxbUsers[1].name, CommonPassword)
			log.FailOnError(err, "Fetching non admin ctx")
			pxbUsers[1] = user{name: pxbUsers[1].name, ctx: ctxNonAdmin}
		})

		Step("Share Backup1 from Cluster1 to User2 with restore access using User1 context", func() {
			err := ShareBackup(backupName, []string{}, []string{pxbUsers[2].name}, RestoreAccess, pxbUsers[1].ctx)
			log.FailOnError(err, fmt.Sprintf("backup share to user %v by super admin user %v failed", pxbUsers[2].name, pxbUsers[1].name))
		})

		Step("Verify user2 can access admin backup", func() {
			bkpInspectRequest := &api.BackupInspectRequest{
				OrgId: BackupOrgID,
				Name:  backupName,
			}
			_, err := Inst().Backup.InspectBackup(pxbUsers[2].ctx, bkpInspectRequest)
			log.FailOnError(err, "failed to inspect backup [%v] by user %s", backupName, pxbUsers[2].name)
		})

		Step("Create restore from Admin Backup on SourceCluster with User2", func() {
			// Create a destination cluster object with User2
			err := AddDestinationCluster(pxbUsers[2].ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cluster[%s] with %s ctx", DestinationClusterName, pxbUsers[2].name))

			destinationClusterUID, err = Inst().Backup.GetClusterUID(pxbUsers[2].ctx, BackupOrgID, DestinationClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", DestinationClusterName))

			// Create Restore
			for _, namespace := range bkpNamespaces {
				restoredNameSpace := fmt.Sprintf("%s-%s", RandomString(10), "restored")
				namespaceMapping[namespace] = restoredNameSpace
			}
			log.InfoD("Namespace mapping is %v:", namespaceMapping)
			err = CreateRestore(restoreName, backupName, namespaceMapping, DestinationClusterName, destinationClusterUID, BackupOrgID, pxbUsers[2].ctx, make(map[string]string))
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creating restore [%s]", restoreName))
		})

		Step("Cleanup", func() {
			backupDriver := Inst().Backup
			backupUID, err := backupDriver.GetBackupUID(pxbUsers[0].ctx, backupName, BackupOrgID)
			log.FailOnError(err, "Failed while trying to get backup UID for - [%s]", backupName)

			log.InfoD("Deleting backup")
			err = DeleteBackupAndWaitForCompletion(backupName, backupUID, BackupOrgID, pxbUsers[0].ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting backup [%s]", backupName))

			log.InfoD(fmt.Sprintf("Delete restore with name [%s]", restoreName))
			err = DeleteRestore(restoreName, BackupOrgID, pxbUsers[2].ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting restore [%s]", restoreName))

			err = DeleteCluster(SourceClusterName, BackupOrgID, pxbUsers[0].ctx, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting Cluster [%s]", SourceClusterName))

			err = DeleteCluster(DestinationClusterName, BackupOrgID, pxbUsers[2].ctx, false)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Deleting Cluster [%s]", DestinationClusterName))
		})

	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)

		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		log.InfoD("Deleting deployed applications")
		DestroyApps(scheduledAppContexts, opts)

		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, pxbUsers[0].ctx)
		for i := 1; i < len(pxbUsers); i++ {
			err := backup.DeleteUser(pxbUsers[i].name)
			log.FailOnError(err, "Failed to delete user - %s", pxbUsers[i].name)
		}
	})
})
