package tests

import (
	"fmt"
	"time"

	"github.com/libopenstorage/stork/pkg/k8sutils"
	. "github.com/onsi/ginkgo/v2"
	"github.com/pborman/uuid"
	api "github.com/portworx/px-backup-api/pkg/apis/v1"
	"github.com/portworx/sched-ops/k8s/core"
	"github.com/pure-px/torpedo/drivers/backup"
	"github.com/pure-px/torpedo/drivers/scheduler"
	"github.com/pure-px/torpedo/pkg/log"
	. "github.com/pure-px/torpedo/tests"
	"golang.org/x/sync/errgroup"
)

// This test deletes backup custom resource.
var _ = Describe("{DeleteCustomResourceBackup}", func() {
	var (
		backupName           string
		scheduledAppContexts []*scheduler.Context
		bkpNamespaces        []string
		namespace            string
		clusterUid           string
		clusterStatus        api.ClusterInfo_StatusInfo_Status
		cloudCredName        string
		cloudCredUID         string
		backupLocationUID    string
		providers            []string
		backupLocationMap    map[string]string
		labelSelectors       map[string]string
		backupLocation       string
		controlChannel       chan string
		errorGroup           *errgroup.Group
	)
	JustBeforeEach(func() {
		bkpNamespaces = make([]string, 0)
		backupLocationMap = make(map[string]string)
		labelSelectors = make(map[string]string)
		providers = GetBackupProviders()

		StartPxBackupTorpedoTest("DeleteCustomResourceBackup", "Delete custom resource backup", nil, 300500, Prikumar, Q3FY25)
		log.InfoD("Deploy applications")

		scheduledAppContexts = make([]*scheduler.Context, 0)
		for i := 0; i < Inst().GlobalScaleFactor; i++ {
			taskName := fmt.Sprintf("%s-%d", TaskNamePrefix, i)
			appContexts := ScheduleApplications(taskName)
			for _, ctx := range appContexts {
				ctx.ReadinessTimeout = AppReadinessTimeout
				namespace = GetAppNamespace(ctx, taskName)
				bkpNamespaces = append(bkpNamespaces, namespace)
				scheduledAppContexts = append(scheduledAppContexts, ctx)
			}
		}
	})
	//Test case to delete custom resource while backup in progress
	It("Test to validate and delete CRs before completion of backup", func() {
		Step("Validate applications", func() {
			ctx, _ := backup.GetAdminCtxFromSecret()
			controlChannel, errorGroup = ValidateApplicationsStartData(scheduledAppContexts, ctx)
		})

		Step("Creating cloud credentials", func() {
			log.InfoD("Creating cloud credentials")
			providers := GetBackupProviders()
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			for _, provider := range providers {
				cloudCredName = fmt.Sprintf("%s-%s-%v", "cred", provider, time.Now().Unix())
				cloudCredUID = uuid.New()
				err := CreateCloudCredential(provider, cloudCredName, cloudCredUID, BackupOrgID, ctx)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying creation of cloud credential named [%s] for org [%s] with [%s] as provider", cloudCredName, BackupOrgID, provider))
			}
		})

		Step("Register cluster for backup", func() {
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			err = CreateApplicationClusters(BackupOrgID, "", "", ctx)
			dash.VerifyFatal(err, nil, "Creating source and destination cluster")
			clusterStatus, err = Inst().Backup.GetClusterStatus(BackupOrgID, SourceClusterName, ctx)
			log.FailOnError(err, fmt.Sprintf("Fetching [%s] cluster status", SourceClusterName))
			dash.VerifyFatal(clusterStatus, api.ClusterInfo_StatusInfo_Online, fmt.Sprintf("Verifying if [%s] cluster is online", SourceClusterName))
			clusterUid, err = Inst().Backup.GetClusterUID(ctx, BackupOrgID, SourceClusterName)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Fetching [%s] cluster uid", SourceClusterName))
		})

		Step("Creating backup location", func() {
			log.InfoD("Creating backup location")
			providers = GetBackupProviders()
			for _, provider := range providers {
				backupLocation = fmt.Sprintf("autogenerated-backup-location-%v", time.Now().Unix())
				backupLocationUID = uuid.New()
				backupLocationMap[backupLocationUID] = backupLocation
				err := CreateBackupLocation(provider, backupLocation, backupLocationUID, cloudCredName, cloudCredUID, getGlobalBucketName(provider), BackupOrgID, "", true)
				dash.VerifyFatal(err, nil, fmt.Sprintf("Creating backup location %s", backupLocation))
			}
		})

		Step("Taking backup of applications", func() {
			log.InfoD("Taking Backup of application")
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			backupName = fmt.Sprintf("%s-%v", BackupNamePrefix, time.Now().Unix())
			appContextsToBackup := FilterAppContextsByNamespace(scheduledAppContexts, []string{namespace})
			_, err = CreateBackupWithoutCheck(ctx, backupName, SourceClusterName, backupLocation, backupLocationUID, appContextsToBackup, labelSelectors, BackupOrgID, clusterUid, "", "", "", "")
			dash.VerifyFatal(err, nil, fmt.Sprintf("Creation of backup [%s]", backupName))
		})

		Step("Delete the backups CR", func() {
			log.InfoD("Delete the backups CR")
			ctx, err := backup.GetAdminCtxFromSecret()
			log.FailOnError(err, "Fetching px-central-admin ctx")
			err = DeleteBackupCR(namespace, backupName, SourceClusterName, clusterUid, BackupOrgID, ctx)
			log.InfoD("started deleting the cr")
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying backup CR %s deletion", backupName))
			err = BackupFailedCheck(backupName, BackupOrgID, MaxWaitPeriodForBackupCompletionInMinutes*time.Minute, 30*time.Second, ctx)
			dash.VerifyFatal(err, nil, fmt.Sprintf("Verifying if the backup [%s] is in failed state", backupName))

		})

		//Verify the Failure status of the backup from metrics endpoint
		Step("Verify the failure status of the backup from metrics endpoint", func() {
			pxbNamespace, err := backup.GetPxBackupNamespace()
			dash.VerifyFatal(err, nil, "Getting px-backup namespace")

			allMetricsData, err := RunCurlCmd(pxbNamespace)
			log.FailOnError(err, "Fetching metrics data")

			expected := "4"
			status := GetMetricValue(allMetricsData, PxBackupMetricsName, backupName)
			log.Infof("pxbackup_backup_status recived:", status)
			dash.VerifyFatal(status, expected, "Verify the failure status of the pxbackup_backup_status from metrics endpoint")
		})
	})
	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		log.InfoD("Deleting the deployed apps after the testcase")
		// Cleaning up applications created
		opts := make(map[string]bool)
		opts[SkipClusterScopedObjects] = true
		err := DestroyAppsWithData(scheduledAppContexts, opts, controlChannel, errorGroup)
		log.FailOnError(err, "Data validations failed")

		// Cleaning up px-backup cluster
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		CleanupCloudSettingsAndClusters(backupLocationMap, cloudCredName, cloudCredUID, ctx)
	})
})

// This testcase validates static entries of the stork-controller-config configmap before and after pod restart
var _ = Describe("{VerifyStaticEntriesOfStorkControllerCm}", Label(TestCaseLabelsMap[StorkControllerConfigCM]...), func() {

	var (
		scheduledAppContexts            []*scheduler.Context
		storkControllerConfigMap        string
		defaultStorkDeploymentNamespace string
		duplicateMap                    map[string]string
	)
	JustBeforeEach(func() {
		defaultStorkDeploymentNamespace = "kube-system"
		StorkLabel = map[string]string{"name": "stork"}
		storkControllerConfigMap = "stork-controller-config"
		duplicateMap = make(map[string]string)

		StartPxBackupTorpedoTest("VerifyStaticEntriesOfStorkControllerCm", "Validate static entry parameteres like admin-ns, service-account and stork-deploy-ns are not changed after stork pod restart", nil, 300557, Prikumar, Q2FY25)
		scheduledAppContexts = make([]*scheduler.Context, 0)
	})

	// Validate static entry parameters like admin-ns, service-account and stork-deploy-ns are not changed after stork pod restart
	It("Test to verify static entries of the stork-controller-config configmap before and after pod restart", func() {

		// Validate static entry parameters of stork-controller-config configmap before pod restart
		Step("Verify the admin-ns, service-account, stork-deploy-ns value before pod restart", func() {
			log.InfoD("Verify the admin-ns, service-account, stork-deploy-ns value before pod restart")

			storkControllerConfigMapObject, err := core.Instance().GetConfigMap(storkControllerConfigMap, defaultStorkDeploymentNamespace)
			log.InfoD("stork map [%v] default-ns [%v]", storkControllerConfigMap, defaultStorkDeploymentNamespace)
			if err != nil {
				log.Errorf("Error getting stork controller configmap: %v", err)
			}

			for key, value := range storkControllerConfigMapObject.Data {
				duplicateMap[key] = value
				log.Infof("Value of [%s] in stork controller configmap is [%v]", key, duplicateMap[key])
			}
		})

		// Restart stork pods to verify the values
		Step("Get pods from new admin namespace", func() {
			storkDeploymentNamespace, err := k8sutils.GetStorkPodNamespace()
			if err != nil {
				log.InfoD("error geting strk")
			}
			// Delete stork pods with label
			err = DeletePodWithWithoutLabelInNamespace(storkDeploymentNamespace, StorkLabel, false)
			dash.VerifyFatal(err, nil, "Restart stork pods")
			err = ValidatePodByLabel(StorkLabel, storkDeploymentNamespace, 5*time.Minute, 30*time.Second)
			log.FailOnError(err, "Checking if stork pod is in running state")
		})

		// Validate static entry parameters of stork-controller-config configmap after pod restart
		Step("Verify the admin-ns, service-account, stork-deploy-ns value after stork pod restart", func() {
			log.InfoD("Verify the admin-ns, service-account, stork-deploy-ns value after stork pod restart")

			storkControllerConfigMapObject, err := core.Instance().GetConfigMap(storkControllerConfigMap, defaultStorkDeploymentNamespace)
			if err != nil {
				log.Errorf("Error getting stork controller configmap: %v", err)
			}

			for key, _ := range storkControllerConfigMapObject.Data {
				log.InfoD("Stork controller configmap value [%s] is equal after stork pod restart %s %s", key, storkControllerConfigMapObject.Data[key], duplicateMap[key])
				dash.VerifyFatal(storkControllerConfigMapObject.Data[key], duplicateMap[key], "Stork controller configmap values remains same after pod restart")

			}
		})
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(scheduledAppContexts)
		ctx, err := backup.GetAdminCtxFromSecret()
		log.FailOnError(err, "Fetching px-central-admin ctx")
		log.InfoD("Deleting the deployed apps after the testcase")
		CleanupCloudSettingsAndClusters(nil, "", "", ctx)

	})
})
