FROM centos:centos7

# Install necessary dependencies

RUN yum install epel-release -y
RUN yum install npm -y
RUN yum install nodejs npm -y
RUN npm install -g newman
RUN yum install jq -y
RUN yum install wget -y
RUN wget https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64 -O /usr/local/bin/yq
RUN chmod +x /usr/local/bin/yq

# Install required dependencies
RUN yum install -y curl

# Download and install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

RUN chmod 777 ./