  {{/* Portworx persistent volume claim */}}
    {{ if .ClaimsCount }}
    {{- range $val := Iterate .ClaimsCount }}
---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-data-volume-{{ $val }}
  spec:
    storageClassName: fedora-sc
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: app-config-{{ $val }}
  data:
    key1: value1
    key2: value2
    key3: value3
    key4: value4
    key5: value5
    key6: value6
    key7: value7
    key8: value8
    key9: value9
    key10: value10
    key11: value11
    key12: value12
    key13: value13
    key14: value14
    key15: value15
    key16: value16
    key17: value17
    key18: value18
    key19: value19
    key20: value20
---
  apiVersion: v1
  data:
    password: dummypassword
    username: dummyusername
  kind: Secret
  metadata:
    name: app-secret-{{ $val }}
    namespace: fed2
    uid: fd82f809-3f3c-4b99-995c-f646ef490d4f
  type: Opaque
    {{- end }}
    {{ else }}
---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-data-volume
  spec:
    storageClassName: fedora-sc
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: app-config
  data:
    key1: value1
    key2: value2
    key3: value3
    key4: value4
    key5: value5
    key6: value6
    key7: value7
    key8: value8
    key9: value9
    key10: value10
    key11: value11
    key12: value12
    key13: value13
    key14: value14
    key15: value15
    key16: value16
    key17: value17
    key18: value18
    key19: value19
    key20: value20
---
  apiVersion: v1
  data:
    password: dummypassword
    username: dummyusername
  kind: Secret
  metadata:
    name: app-secret
  type: Opaque
  {{- end }}
---
  apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    labels:
      kubevirt.io/os: linux
      app: vm-fed
    name: vm-fed
  spec:
    running: true
    template:
      metadata:
        labels:
          kubevirt.io/domain: vm-fed
          app: vm-fed
      spec:
        domain:
          devices:
            disks:
              - disk:
                  bus: virtio
                name: containerdisk
              - disk:
                  bus: virtio
                name: cloudinitdisk
              {{ if .ClaimsCount }}
              {{- range $val := Iterate .ClaimsCount }}
              - name: datavolume{{ $val }}
                disk:
                  bus: virtio
              - disk:
                name: app-config-disk-{{ $val }}
                serial: CVLY623300HK240D{{ $val }}
              - disk:
                name: app-secret-disk-{{ $val }}
                serial: D23YZ9W6WA5DJ487{{ $val }}
              {{- end }}
              {{ else }}
              - name: datavolume
                disk:
                  bus: virtio
              - disk:
                name: app-config-disk
                serial: CVLY623300HK240D
              - disk:
                name: app-secret-disk
                serial: D23YZ9W6WA5DJ487
              {{- end }}
          machine:
            type: ""
          resources:
            requests:
              memory: 2048M
        terminationGracePeriodSeconds: 0
        volumes:
          - name: containerdisk
            containerDisk:
              image: kubevirt/fedora-cloud-container-disk-demo:latest
          {{ if .ClaimsCount }}
          {{- range $val := Iterate .ClaimsCount }}
          - name: datavolume{{ $val }}
            dataVolume:
              name: pvc-data-volume-{{ $val }}
          - name: app-config-disk-{{ $val }}
            configMap:
              name: app-config-{{ $val }}
          - name: app-secret-disk-{{ $val }}
            secret:
              name: app-secret-{{ $val }}
          {{- end }}
          {{ else }}
          - name: datavolume
            dataVolume:
              name: pvc-data-volume
          - name: app-config-disk
            configMap:
              name: app-config
          - secret:
              secretName: app-secret
            name: app-secret-disk
          {{- end }}
          - cloudInitNoCloud:
              userData: |-
                #cloud-config
                password: fedora
                chpasswd: { expire: False }
                bootcmd:
                  # mount the ConfigMap
                  - "sudo mkdir /mnt/app-config"
                  - "sudo mount /dev/$(lsblk --nodeps -no name,serial | grep CVLY623300HK240D | cut -f1 -d' ') /mnt/app-config"
            name: cloudinitdisk
