{{- range $i := until .VolumeCount }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data-{{ $i }}
spec:
  storageClassName: postgres-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
{{- end }}