##### Portworx persistent volume claim
{{- $volumeCount := .Values.VolumeCount }}
{{- range $i, $ := until $volumeCount }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-{{ $i }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-sc
  resources:
    requests:
      storage: 1Gi
  {{- end }}

