apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-portworx-pvc
  labels:
    backupVolumeType: pxd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: px-csi-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-gke-pvc
  labels:
    backupVolumeType: csi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo