##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nginx-sc-cloud
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  snapshotschedule.stork.libopenstorage.org/test-schedule: |
    schedulePolicyName: auto-schedule-policy
    reclaimPolicy: Delete
    annotations:
      portworx/snapshot-type: cloud
allowVolumeExpansion: true