apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: datavol-fada-raw-immediate
parameters:
  backend: "pure_block"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-data-validation-template-pvc
  namespace: openshift-virtualization-os-images
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: http://kubevirt-disk-registry.pwx.dev.purestorage.com/more_images/fio-data-validation.qcow2
    pvc.source: "cloned"
spec:
  volumeMode: Block
  storageClassName: datavol-fada-raw-immediate
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
