##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-sv4-2-sc-svc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  aggregation_level: "2"
  io_profile: "db"
  sharedv4: "true"
allowVolumeExpansion: true
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-sv4-2-pvc-svc
spec:
  storageClassName: test-sv4-2-sc-svc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

