apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-shr-intree-rep3
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  shared: "true"
reclaimPolicy: Delete
allowVolumeExpansion: true
