apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mount-sc
parameters:
  backend: "pure_file"
provisioner: pxd.portworx.com 
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nosuid
