apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-portworx-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: pxd-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-portworx-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi
  storageClassName: pxd-sc
