kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  {{ if .Repl }}
  repl: "{{ .Repl }}"
  {{ else }}
  repl: "3"{{ end }}
  priority_io: "high"
  snap_schedule: "periodic=60,5"