apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      schedulerName: stork
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        livenessProbe:
          exec:
            command: ["sh", "-c", "mysqladmin -u root -p$MYSQL_ROOT_PASSWORD ping"]
          initialDelaySeconds: 70
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["sh", "-c", "mysql -u root -p$MYSQL_ROOT_PASSWORD -e \"select 1\""]
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: mysql-persistent-storage-1
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-1
        persistentVolumeClaim:
          claimName: mysql-data-1
      - name: mysql-persistent-storage-2
        persistentVolumeClaim:
          claimName: mysql-data-2
      - name: mysql-persistent-storage-3
        persistentVolumeClaim:
          claimName: mysql-data-3
      - name: mysql-persistent-storage-4
        persistentVolumeClaim:
          claimName: mysql-data-4
      - name: mysql-persistent-storage-5
        persistentVolumeClaim:
          claimName: mysql-data-5
      - name: mysql-persistent-storage-6
        persistentVolumeClaim:
          claimName: mysql-data-6
      - name: mysql-persistent-storage-7
        persistentVolumeClaim:
          claimName: mysql-data-7
      - name: mysql-persistent-storage-8
        persistentVolumeClaim:
          claimName: mysql-data-8
      - name: mysql-persistent-storage-9
        persistentVolumeClaim:
          claimName: mysql-data-9
      - name: mysql-persistent-storage-10
        persistentVolumeClaim:
          claimName: mysql-data-10
