apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-sc-cms-repl3-shared
provisioner: kubernetes.io/portworx-volume
parameters:
  fs: "ext4"
  block_size: "512b"
  repl: "3"
  aggregation_level: "1"
  io_profile: "cms"
  priority_io: "high"
  shared: "true"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-sc-db-repl3
provisioner: kubernetes.io/portworx-volume
parameters:
  fs: "ext4"
  block_size: "512b"
  repl: "3"
  aggregation_level: "1"
  io_profile: "db"
  priority_io: "high"
  shared: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-sc-cms-repl3-shared
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-1
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-sc-db-repl3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
