---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster
spec:
  clusterIP: None
  selector:
    app: es-cluster
  ports:
  - name: transport
    port: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-api
spec:
  selector:
    app: es-cluster
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  elasticsearch.yml: |
    cluster.name: my-elastic-cluster-repl1
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: elasticsearch-cluster
    discovery.zen.minimum_master_nodes: 1
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    indices.memory.index_buffer_size: 30%
  ES_JAVA_OPTS: -Xms8196m -Xmx8196m
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esnode
spec:
  serviceName: elasticsearch-api
  replicas: 3
  selector:
    matchLabels:
      app: es-cluster
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: es-cluster
    spec:
      schedulerName: stork
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
      - name: elasticsearch
        resources:
          requests:
            memory: 8Gi
            cpu: "1"
          limits:
            cpu: "2"
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: es-config
              key: ES_JAVA_OPTS
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        ports:
        - containerPort: 9200
          name: es-http
        - containerPort: 9300
          name: es-transport
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: elasticsearch-config
        configMap:
          name: es-config
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      storageClassName: elasticsearch-sc-read-write
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 250Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-load
  labels:
    app: es-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-load
  template:
    metadata:
      labels:
        app: es-load
    spec:
      containers:
      - name: es-load
        image: portworx/torpedo-esload:1.1
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
          - /bin/bash
          - -c
          - "./esload.sh --es_address esnode-0.elasticsearch-api.$POD_NAMESPACE.svc.cluster.local:9200 --indices 10 --documents 750 --seconds 172800 --not-green --clients 3 --max-fields-per-document 200 --no-cleanup"
      restartPolicy: Always

