---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-load-readupdate
  labels:
    app: es-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-load
  template:
    metadata:
      labels:
        app: es-load
    spec:
      containers:
      - name: es-load-readupdate
        image: docker.pwx.dev.purestorage.com/portworx/elasticsearch_read_update
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
          - /bin/bash
          - -c
          - "./esreadupdate.sh --es_address esnode-0.elasticsearch-api.$POD_NAMESPACE.svc.cluster.local:9200"
      restartPolicy: Always
