kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: elasticsearch-sc-read-write
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "2"
   nodiscard: "true"
allowVolumeExpansion: true
