apiVersion: apps/v1
kind: Deployment
metadata:
  name: virt-launcher-sim-dep
spec:
  {{ if .Replicas }}
  replicas: {{ .Replicas }}
  {{ else }}
  replicas: 3{{ end }}
  selector:
    matchLabels:
      app: virt-launcher-sim-app
  template:
    metadata:
      labels:
        app: virt-launcher-sim-app
        kubevirt.io: virt-launcher
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - virt-launcher-sim-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: sv4test
        image: portworx/sharedv4-test:torpedo
        imagePullPolicy: Always
        command: ["python", "/app/fileio.py"]
        args: ["--lock", "--interval=0.25", "$(SHARED_FILE)", "$(LOCAL_FILE)"]
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SHARED_FILE
            value: "/shared-vol/$(MY_POD_NAME)"
          - name: LOCAL_FILE
            value: "/local-vol/$(MY_POD_NAME)"
        volumeMounts:
        - name: virt-launcher-sim-vol
          mountPath: /shared-vol
        - name: local-vol
          mountPath: /local-vol
      - name: sv4test-reader
        image: portworx/sharedv4-test:torpedo
        imagePullPolicy: Always
        command: ["python", "/app/reader.py"]
        # sleeping for 9 seconds from 3 * number of pods * seconds
        args: ["--interval=9", "$(LOCAL_FILE)"]
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: LOCAL_FILE
            value: "/local-vol/$(MY_POD_NAME)"
        volumeMounts:
        - name: local-vol
          mountPath: /local-vol
      volumes:
      - name: virt-launcher-sim-vol
        persistentVolumeClaim:
          claimName: virt-launcher-sim-pvc
      - name: local-vol
        emptyDir: {}
