##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: virt-launcher-sim-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  sharedv4: "true"
allowVolumeExpansion: true
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: virt-launcher-sim-pvc
spec:
  storageClassName: virt-launcher-sim-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

