##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-nginx-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  sharedv4: "true"
allowVolumeExpansion: true
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: px-nginx-pvc
spec:
  storageClassName: px-nginx-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
