kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  {{ if .Replicas }}
  replicas: {{ .Replicas }}
  {{ else }}
  replicas: 3{{ end }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /usr/share/nginx/html
        - name: nginx-persistent-storage-enc
          mountPath: /usr/share/nginx/html-enc
      volumes:
      - name: nginx-persistent-storage
        persistentVolumeClaim:
          claimName: px-nginx-pvc-sharedv4
      - name: nginx-persistent-storage-enc
        persistentVolumeClaim:
          claimName: px-nginx-pvc-enc-sharedv4
