kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: elasticsearch-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   nodiscard: "true"
allowVolumeExpansion: true
