kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: elasticsearch-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  {{ if .Repl }}
  repl: "{{ .Repl }}"
  {{ else }}
  repl: "3"{{ end }}
  nodiscard: "true"
allowVolumeExpansion: true
