##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-overlapping-io-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  priority_io: "high"
  io_profile: "db_remote"
  repl: "3"
  fs: "xfs"
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-overlapping-io-pvc
spec:
  storageClassName: fio-overlapping-io-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi