kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mount-fa-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: mount-fa-sc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mount-fb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
  storageClassName: mount-fb-sc
