---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-fa-ext4-pod
spec:
  # Specify a volume that uses the claim defined in pvc.yaml
  volumes:
  - name: nginx-vol
    persistentVolumeClaim:
        claimName: nginx-fa-ext4-pvc
  containers:
  - name: nginx
    image: nginx
    # Configure a mount for the volume We define above
    volumeMounts:
    - name: nginx-vol
      mountPath: /dev/xvda
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-raw-block
  labels:
    app: "nginx-raw-block"
spec:
  # Specify a volume that uses the claim defined in pvc.yaml
  volumes:
    - name: pure-vol
      persistentVolumeClaim:
        claimName: fa-pvc-block
  containers:
    - name: nginx
      image: nginx
      # Configure a device mount for the volume we defined above
      volumeDevices:
        - name: pure-vol
          devicePath: /dev/xvda
      ports:
        - containerPort: 80