kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: portworx-rawblock-fa-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: portworx-rawblock-fa