apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-sc
parameters:
  repl: "2"
  sharedv4: "true"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate