##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  aggregation_level: "1"
  io_profile: "journal"
allowVolumeExpansion: true
