apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
          volumeMounts:
            - name: mysql-portworx
              mountPath: /var/lib/mysql
            - name: mysql-csi
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: mysql-portworx
          persistentVolumeClaim:
            claimName: mysql-portworx-pvc
        - name: mysql-csi
          persistentVolumeClaim:
            claimName: mysql-csi-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_PASSWORD
              value: postgrespassword
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-portworx
              mountPath: /var/lib/postgresql/data
            - name: postgres-csi
              mountPath: /etc/postgresql/conf.d
      volumes:
        - name: postgres-portworx
          persistentVolumeClaim:
            claimName: postgres-portworx-pvc
        - name: postgres-csi
          persistentVolumeClaim:
            claimName: postgres-csi-pvc
