kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace-pvc-sharedv4svc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: px-file-sc-sharedv4svc
