---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: createoption-fa-ext4-sc
parameters:
  backend: "pure_block"
  csi.storage.k8s.io/fstype: ext4
  createoptions: -b 2048
provisioner: pxd.portworx.com 
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nosuid
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-fa
provisioner: pxd.portworx.com
parameters:
  backend: "pure_block"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

