kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-sc
provisioner: pxd.portworx.com
parameters:
  backend: "pure_block"
  max_iops: "1000"
  max_bandwidth: "1G"
  fs: "ext4"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true