apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            echo "Hello World" > /mnt/data/hello.txt
        volumeMounts:
        - name: hello-world-pvc
          mountPath: /mnt/data
      volumes:
      - name: hello-world-pvc
        persistentVolumeClaim:
          claimName: hello-world-pvc
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "job-sc"