apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-debian-template-pvc
  namespace: openshift-virtualization-os-images
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: http://kubevirt-disk-registry.pwx.dev.purestorage.com/more_images/debian-12-4.qcow2
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    pvc.source: "cloned"
spec:
  storageClassName: sc-sharedv4svc-nolock-wait-first-consumer
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi