---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdbench-sv4-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vdbench-sv4-svc
  template:
    metadata:
      labels:
        app: vdbench-sv4-svc
    spec:
      containers:
        - name: vdbench
          image: srinav/ocp-vdbench:v1
          imagePullPolicy: IfNotPresent
          command: ["./bench_runner.sh"]
          {{ if .ClaimsCount }}
          args: ["Basic", "5400", "datadir", "1" , "{{ .ClaimsCount }}"]
          {{ end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
          {{- range $val := Iterate .ClaimsCount }}
            - name: vdbench-persistent-storage-{{ $val }}
              mountPath: /datadir{{ $val }}
          {{- end }}
      volumes:
      {{- range $val := Iterate .ClaimsCount }}
        - name: vdbench-persistent-storage-{{ $val }}
          persistentVolumeClaim:
            claimName: vdbench-pvc-sv4-svc-{{ $val }}
      {{- end }}
